<form action="index" method="POST" id="Listxml_Recordtype_Add" enctype="multipart/form-data" autocomplete="off">
<table width='100%'  border='0' cellspacing='0' cellpadding='0' class="table_title">
	<!--tao tac hidden!-->
	<tr>
		<td style="padding-left:7px;text-align:left;">
			<?php echo $this->formHidden("hdn_deleted_exist_file_id_list","",null); ?>
			<?php echo $this->formHidden("hdn_deleted_new_file_id_list","",null); ?>
			<?php echo $this->formHidden("hdn_xml_tag_list","",null); ?>
			<?php echo $this->formHidden("hdn_xml_value_list","",null); ?>
			<?php echo $this->formHidden("hdn_XmlTagValueList","",null); ?>
			<!--Bien hdn_deleted_exist_file_id_list dung de ...-->	
			<?php echo $this->formHidden("hdn_deleted_exist_file_id_list","",null); ?>	
			<?php echo $this->formHidden("hdn_object_id","",null); ?>			
			<?php echo $this->formHidden("hdn_update","",null); ?>		
		</td>
	</tr>
</table>
<?php 
	//Cac mang goi tu Controller
	$arrConst = $this->arrConst;
	$arrResult = $this->arrResult; ?>
<div style="height:3px;"></div>
<div id ="contentXml" >
	<div id="header_conten" style="height: 15px;padding-bottom:15px;">
		<h1 class="large_label"><?=$this->bodyTitle;?> 
			<div style="text-align:right; float:right;">
				<a  class="small_link" onClick = "btn_save_listreport(document.getElementsByName('hdn_xml_tag_list'),document.getElementsByName('hdn_xml_value_list'));"><?=$arrConst['_GHI'] ?>&nbsp;|</a> 
				<a  class="small_link"  onclick="actionUrl('../index/');">&nbsp;<?=$arrConst['_QUAY_LAI'] ?>&nbsp;</a>
			</div>
		</h1>
	</div>
<!--Form nhap TTHC !-->
	<div id="body_conten1">
		<div>
			<label >Tên báo cáo<span class="requiein">*</span></label>
			<input class = "normal_textbox" style="width:65%"  type="text"  id ="C_NAME" name="C_NAME" option = "false"  value="" message="<?php echo "Phải xác định tên báo cáo!";?>">			
		</div>				
		<div>
			<label >File XML mô tả thuộc tính chung<span class="requiein">*</span></label>
			<div>
				<dd id = "file_from_server">
					<?=$this->formText('txt_xml_file_name',"",array('type'=>'text','style'=>'display:inline;','size'=>77, 'class'=>'normal_textbox', 'optional'=>true,'onKeyDown'=>'change_focus(document.forms(0),this)', ));?>
					<?=$this->formButton("popupDialog","Browse",array("type"=>"button",'style'=>'display:inline;',"class"=>"add_large_button","onClick"=>"openmypage(); return false"))?>	
				</dd>
			</div>			
		</div>		
		<div>					
			<!--Goi mot Digloa bang javascript-->				
		 	 <div id="somediv" style="display:none">
				<?php echo $this->divDialog;?>
			 </div>	
		</div>		
		<div>
			<label><?=$arrConst['_THU_TU'] ?><span class="requiein">*</span></label>
			<input class = "normal_textbox" style="width:15%" id ="C_ORDER" name="C_ORDER" type="text"  option = "false"  value="<?=$this->iOrder;?>"  message="<?php echo "Phải xác định thứ tự!";?>"    onchange="IsNumeric(this);">			
			&nbsp; &nbsp; <input id ="C_STATUS" name="C_STATUS" type="checkbox"  checked> <span ><?=$arrConst['_HOAT_DONG'] ?> </span>				
		</div>	
		<div class="line"></div>	
		<div>
			<label >Báo cáo cho các TTHC</label>
			<div style="width:65%;">
				<table cellpadding="0" cellspacing="0" width="100%" border="0">
					<tr>
						<td>
							<?php	
							$arrRecordType = $this->arrRecordType;
							global $dspDiv, $readonlyInEditMode, $disabledInEditMode, $formFielName;
							$this->dspDiv = 1; //Chia lam 2 phan
							$this->readonlyInEditMode = true; $this->disabledInEditMode = true;
							$this->formFielName	= "C_RECORD_TYPE_LIST";
							$spRetHtml = "<div style='display:none'><input type='textbox' id='$this->formFielName' name='$this->formFielName' value='' hide='true' readonly optional = true xml_data=false xml_tag_in_db='' message=''></div>";
							echo $spRetHtml . Extra_Xml::_generateHtmlForMultipleCheckbox($arrRecordType, 'C_CODE','C_NAME','','','200px');
							?>	
						</td>
					</tr>
				</table>	
			</div>	
		</div>		
	</div>
</div>			
<!--Hien thi nut!-->			
<table 	width='99%'  border='0' cellspacing='0' cellpadding='0' align="center" class="table_title">		
	<tr>
		<td align="center">	
			<?=$this->formButton("btn_update","Ghi",array("type"=>"button","class"=>"add_large_button","onClick"=>"btn_save_listreport(document.getElementsByName('hdn_xml_tag_list'),document.getElementsByName('hdn_xml_value_list'));"))?>								
			<?=$this->formsubmit('button','Quay lại',array("onClick"=>"actionUrl('../index/');","class"=>"add_large_button"))?>
		</td>
	</tr>			
</table>
</form>
<script type="text/javascript">
	function openmypage(){ 
		divwin=dhtmlwindow.open("divbox", "div", "somediv", "EFY.COM.VN", "width=450px,height=300px,left=300px,top=100px,resize=1,scrolling=1")
	}
</script>