<form action="index" method="POST" id="Listxml_Recordtype_Add" enctype="multipart/form-data" autocomplete="off">
<table width='100%'  border='0' cellspacing='0' cellpadding='0' class="table_title">
	<!--tao tac hidden!-->
	<tr>
		<td style="padding-left:7px;text-align:left;">
			<?php echo $this->formHidden("hdn_deleted_exist_file_id_list","",null); ?>
			<?php echo $this->formHidden("hdn_deleted_new_file_id_list","",null); ?>
			<?php echo $this->formHidden("hdn_xml_tag_list","",null); ?>
			<?php echo $this->formHidden("hdn_xml_value_list","",null); ?>
			<?php echo $this->formHidden("hdn_XmlTagValueList","",null); ?>
			<!--Bien hdn_deleted_exist_file_id_list dung de ...-->	
			<?php echo $this->formHidden("hdn_deleted_exist_file_id_list","",null); ?>	
			<?php echo $this->formHidden("hdn_object_id",$this->sListReportId,null); ?>
			<?php echo $this->formHidden("hdn_report_col_id",$this->sListReportColId,null); ?>						
			<?php echo $this->formHidden("hdn_update","",null); ?>
			<?php echo $this->formHidden("hdn_object_id_list","",null); ?>
		</td>
	</tr>
</table>
<?php 
	//Cac mang goi tu Controller
	$arrConst = $this->arrConst;
	$arrResult = $this->arrInput;
	$arrListCol = $this->arrListCol;	
	$arrReportColInfo = $this->arrReportColInfo;
	//var_dump($arrListCol);
	if($this->bStatus){
		$sCheck = "checked";
	}else{
		$sCheck = "";
	}?>
<div style="height:3px;"></div>
<div id ="contentXml" >
	<div id="header_conten" style="height: 10px;padding-bottom:0px;">
		<h1 class="large_title">DANH SÁCH CÁC TRƯỜNG DỮ LIỆU</h1>
	</div>
	<div id="body_conten1">
		<div class="line"></div>	
		<div>
			<label >Tên báo cáo<span class="requiein">*</span></label>
			<input class = "normal_textbox" style="width:65%"  type="text"  id ="C_NAME" name="C_NAME" option = "false"  value="<?=$arrResult[0]['C_NAME']?>" message="<?php echo "Phải xác định tên báo cáo!";?>">			
		</div>	
	</div>
	<div id="viewAllSentDocument">
		<table cellpadding="0" cellspacing="0" border="0" width="99%" align="center" class="list_table2" id="table1">
			<?php			
			$delimitor = $this->delimitor;//Lay ky tu phan cach giua cac phan tu
			//Hien thi cac cot cua bang hien thi du lieu
				$StrHeader = explode("!~~!", Efy_Library::_GenerateHeaderTable("3%" . $delimitor . "7%" . $delimitor . "30%". $delimitor . "14%" . $delimitor . "14%" . $delimitor . "14%" . $delimitor . "14%"
												,'<input type="checkbox" name="chk_all_item_id"  onclick="checkbox_all_item_id(document.forms[0].chk_item_id);">' . $delimitor .$arrConst['_THU_TU'] . $delimitor . "Tiêu đề" . $delimitor . "Dịnh dạng". $delimitor . "Độ rộng" . $delimitor . "Căn chỉnh" . $delimitor . $arrConst['_TINH_TRANG']
												,$delimitor));
			echo $StrHeader[0];				
			echo $StrHeader[1]; //Hien thi <col width = 'xx'><...		
			//Dinh nghia URL
			$sCurrentStyleName = "round_row";	
			for($index = 0;$index < sizeof($arrListCol) ;$index++){
				$sPk						= $arrListCol[$index]['PK_LIST_REPORT_COL'];			
				$iOrder						= $arrListCol[$index]['C_ORDER'].'&nbsp;';						
				$sTitle 					= $arrListCol[$index]['C_TITLE'].'&nbsp;';
				$sFormat 					= $arrListCol[$index]['C_FORMAT'].'&nbsp;';
				$sAlign 					= $arrListCol[$index]['C_ALIGN'].'&nbsp;';
				$sWidth 					= $arrListCol[$index]['C_WIDTH'].'&nbsp;';
				$sStatus		 			= $arrListCol[$index]['C_STATUS'];
				If($sStatus == "HOAT_DONG"){
					$sStatus = "Hoạt động";
				}else{
					$sStatus = "Không hoạt động";
				}
				if ($sCurrentStyleName == "odd_row"){
					$sCurrentStyleName = "round_row";
				}else{
					$sCurrentStyleName = "odd_row";					
				}
				$check = false;
				if($sPk==$this->sListReportColId){
					$sCurrentStyleName = $sCurrentStyleName . " selected";
					$check = true;
				}
				?>					
				<tr class="<?=$sCurrentStyleName?>">	
					<td align="center" style="padding-left:3px;padding-right:3px;" class="normal_label">					
						<?=$this->formCheckbox('chk_item_id',$sPk, array('checked' => $check,'onclick' =>'selectrow(this)'));?>					
					</td>
					<td align="center"  onclick="colitem_onclick('<?=$sPk?>','')" style="padding-left:3px;padding-right:3px;"  class="normal_label" >
						<?=$iOrder?>
					</td>								
					<!--Hien ket qua xu ly!-->	
					<td align="left"  onclick="colitem_onclick('<?=$sPk?>','')" style="padding-left:3px;padding-right:3px;" class="normal_label"><?= $sTitle?></td>
					<td align="left"  onclick="colitem_onclick('<?=$sPk?>','')" style="padding-left:3px;padding-right:3px;" class="normal_label"><?= $sFormat?></td>
					<td align="center"  onclick="colitem_onclick('<?=$sPk?>','')" style="padding-left:3px;padding-right:3px;" class="normal_label"><?= $sWidth?></td>
					<td align="center"  onclick="colitem_onclick('<?=$sPk?>','')" style="padding-left:3px;padding-right:3px;" class="normal_label"><?= $sAlign?></td>
					<td align="center" onclick="colitem_onclick('<?=$sPk?>','')" style="padding-left:3px;padding-right:3px;" class="normal_label"><?= $sStatus ?></td>	
				</tr><?php
			}					
			//Tu dien cac dong trang trong truong hop du lieu tra ve < so row _CONST_NUMBER_OF_ROW_PER_LIST	
				echo Efy_Library::_addEmptyRow($this->iCountElement,5 -sizeof($arrListCol),$sCurrentStyleName,7);
			?>
		</table>	
		<!--Hien thi trang can xem!-->
	</div>	
	<!--Hien thi nut!-->			
	<table 	width='99%'  border='0' cellspacing='0' cellpadding='0' align="center" class="table_title">		
		<tr>
			<td align="center">	
				<?=$this->formButton("btn_add","Thêm",array("type"=>"button","class"=>"add_large_button","onClick"=>"resetupdate_onclick();"))?>
				<?=$this->formButton("btn_delete",$arrConst['_XOA'],array("type"=>"button","class"=>"add_large_button","onClick"=>"btn_delete_onclick(document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id_list'),'../deletecol/');")); ?>								
				<?=$this->formsubmit('button','Quay lại',array("onClick"=>"actionUrl('../index/');","class"=>"add_large_button"))?>
			</td>
		</tr>			
	</table>
	<div id="header_conten" style="height: 10px;padding-bottom:0px;">
		<h1 class="large_title">CẬP NHẬT TRƯỜNG DỮ LIỆU</h1>
	</div>	
	<div id="body_conten1">				
		<div class="line"></div>	
		<div>
			<label >Tiêu đề<span class="requiein">*</span></label>
			<input class = "normal_textbox" style="width:65%"  type="text"  id ="C_TITLE" name="C_TITLE" option = "false"  value="<?=$arrReportColInfo[0]['C_TITLE']?>" message="<?php echo "Phải xác định tiêu đề trường!";?>">			
		</div>
		<div>
			<label >Định dạng dữ liệu<span class="requiein">*</span></label>
			<select style="width:24%;" id="C_DATA_TYPE" name="C_DATA_TYPE" option = "false" class="normal_textbox" message="<?php echo "Phải xác định kiểu dữ liệu!";?>">
				<option id="" name = "" value="">-- Chọn kiểu dữ liệu --</option><?php
				$arrDataType = $this->arrDataType;
				echo Efy_Library::_generateSelectOption($arrDataType,'C_CODE','C_CODE','C_NAME',$arrReportColInfo[0]['C_FORMAT']);?>
			</select>		
			<span>Độ rộng trường</span><span class="requiein">*</span>
			<input class = "normal_textbox" style="width:10%"  type="text"  id ="C_WIDTH" name="C_WIDTH" option = "false" isnumber value="<?=$arrReportColInfo[0]['C_WIDTH']?>" isnumeric="true" message="<?php echo "Phải xác định độ rộng trường!";?>">
			<span>Căn chỉnh</span><span class="requiein">*</span>
			<select style="width:15%;" id="C_ALIGN_TYPE" name="C_ALIGN_TYPE" option = "false" class="normal_textbox" message="<?php echo "Phải xác định kiểu căn chỉnh!";?>">
				<option id="" name = "" value="">-- Chọn kiểu căn chỉnh --</option><?php
				$arrAlign = $this->arrAlign;
				echo Efy_Library::_generateSelectOption($arrAlign,'C_CODE','C_CODE','C_NAME',$arrReportColInfo[0]['C_ALIGN']);?>
			</select>
		</div>
		<div>
			<label >Dữ liệu lấy từ<span class="requiein">*</span></label>
			<select style="width:24%;" id="C_DATA_SOU" name="C_DATA_SOU" option = "false" class="normal_textbox" message="<?php echo "Phải xác định nguồn dữ liệu!";?>">
				<option id="" name = "" value="">-- Chọn nguồn dữ liệu --</option><?php
				$arrDataSou = $this->arrDataSou;
				echo Efy_Library::_generateSelectOption($arrDataSou,'C_CODE','C_CODE','C_NAME',$arrReportColInfo[0]['C_DATA_SOURCE']);?>
			</select>		
			<span>Tên trường, thẻ</span><span class="requiein">*</span>
			<input class = "normal_textbox" style="width:10%"  type="text"  id ="C_DATA_SOU_NAME" name="C_DATA_SOU_NAME" option = "false"  value="<?=$arrReportColInfo[0]['C_COL_TAB_NAME']?>" message="<?php echo "Phải xác định tên thẻ hoặc tên trường chứa dữ liệu!";?>">
			<span>Hàm xử lý</span>
			<select style="width:15%;" id="C_FUN_NAME" name="C_FUN_NAME" optional = "true" class="normal_textbox" >
				<option id="" name = "" value="">-- Chọn hàm --</option><?php
				$arrDataFun = $this->arrDataFun;
				echo Efy_Library::_generateSelectOption($arrDataFun,'C_CODE','C_CODE','C_NAME',$arrReportColInfo[0]['C_FUN_NAME']);?>
			</select>
		</div>
		<div>
			<label >Thống kê</label>
			<select style="width:15%;" id="C_CALCULATE" name="C_CALCULATE" optional = "true" class="normal_textbox" >
				<option id="" name = "" value="">-- Chọn kiểu thống kê --</option><?php
				$arrCalculate = $this->arrCalculate;
				echo Efy_Library::_generateSelectOption($arrCalculate,'C_CODE','C_CODE','C_NAME',$arrReportColInfo[0]['C_CALCULATE']);?>
			</select>		
			<input class = "normal_textbox" style="width:49%"  type="text"  id ="C_CONDITION" name="C_CONDITION" optional = "true"  value="<?=$arrReportColInfo[0]['C_CONDITION']?>" message="<?php echo "Phải xác định tên báo cáo!";?>">	
		</div>	
		<div>
			<label><?=$arrConst['_THU_TU'] ?><span class="requiein">*</span></label>
			<input class = "normal_textbox" style="width:15%" id ="C_ORDER" name="C_ORDER" type="text"  option = "false"  value="<?=$this->iOrder;?>"  message="<?php echo "Phải xác định thứ tự!";?>" isnumeric = "true">			
			&nbsp; &nbsp; <input id ="C_STATUS" name="C_STATUS" type="checkbox" <?=$sCheck; ?>> <span ><?=$arrConst['_HOAT_DONG'] ?> </span>				
		</div>		
		<div>
			<label >Áp dụng cho TTHC</label>
			<div style="width:65%;">
				<table cellpadding="0" cellspacing="0" width="100%" border="0">
					<tr>
						<td>
							<?php	
							$arrRecordType = $this->arrRecordType;
							global $dspDiv, $readonlyInEditMode, $disabledInEditMode, $formFielName;
							$this->dspDiv = 1; //Chia lam 2 phan
							$this->readonlyInEditMode = true; $this->disabledInEditMode = true;
							$this->formFielName	= "C_RECORD_TYPE_LIST";
							$spRetHtml = "<div style='display:none'><input type='textbox' id='$this->formFielName' name='$this->formFielName' value='' hide='true' readonly optional = true xml_data=false xml_tag_in_db='' message=''></div>";
							echo $spRetHtml . Extra_Xml::_generateHtmlForMultipleCheckbox($arrRecordType,'C_CODE','C_NAME',$arrReportColInfo[0]['C_RECORDTYPE_CODE_LIST'],'','200px');
							?>	
						</td>
					</tr>
				</table>	
			</div>	
		</div>		
	</div>
</div>			
<!--Hien thi nut!-->			
<table 	width='99%'  border='0' cellspacing='0' cellpadding='0' align="center" class="table_title">		
	<tr>
		<td align="center">	
			<?=$this->formButton("btn_update","Ghi",array("type"=>"button","class"=>"add_large_button","onClick"=>"btn_save_listreport(document.getElementsByName('hdn_xml_tag_list'),document.getElementsByName('hdn_xml_value_list'));"))?>								
			<?=$this->formsubmit('button','Quay lại',array("onClick"=>"actionUrl('../index/');","class"=>"add_large_button"))?>
		</td>
	</tr>			
</table>
</form>
<script type="text/javascript">
	function colitem_onclick(p_item_value,p_url){		
		row_onclick(document.getElementById('hdn_report_col_id'), p_item_value, p_url);
	}
	function resetupdate_onclick(){		
		$('#hdn_report_col_id').val('');
		$('#C_TITLE').val('');
		$('#C_DATA_TYPE').val('');
		$('#C_WIDTH').val('');
		$('#C_ALIGN_TYPE').val('');
		$('#C_DATA_SOU').val('');
		$('#C_DATA_SOU_NAME').val('');
		$('#C_FUN_NAME').val('');
		$('#C_CALCULATE').val('');
		$('#C_CONDITION').val('');
		len = document.getElementsByName('chk_item_id').length;
		for(i = 0; i< len; i++){
			document.getElementsByName('chk_item_id')[i].checked = false;
		}
		$('td').parent().removeClass('selected');
		$('#C_TITLE').focus();	
	}
</script>