<form action="index" method="POST" autocomplete="off" name="form">
<div><?php
	$arrConst = $this->arrConst;
	$arrRecordType = $this->arrRecordType;
	$arrCate = $this->arrCate;
	?>
	<table width='100%'  border='0' cellspacing='0' cellpadding='0' class="table_title">
		<tr>
			<td class="large_title" style="padding-left:7px;text-align:left;">
				<!--Cac doi tuong hidden tren form-->
				<?php echo $this->formHidden("hdn_object_id_list","",null); ?>
				<?php echo $this->formHidden("hdn_filter_xml_tag_list",$this->filterXmlTagList,null); ?>
				<?php echo $this->formHidden("hdn_filter_xml_value_list",$this->filterXmlValueList,null); ?>
				<?php echo $this->formHidden("hdn_record_number_page",$this->numRowOnPage,null); ?>	
				<?php echo $this->formHidden("hdn_object_id","",null); ?>
				<?php echo $this->formHidden("hdn_XmlTagValueList",$this->XmlTagValueList,null); ?>	
				<!--Bien hdn_deleted_exist_file_id_list dung de ...-->	
				<?php echo $this->formHidden("hdn_deleted_exist_file_id_list","",null); ?>
				<?php echo $this->formHidden("hdn_cate","",null); ?>	
				<!--Cac doi tuong hidden tren form-->
				<?=	$this->bodyTitle ;?>
			</td>
		</tr>
	</table>
	<div id="filter">			
		<table cellpadding="0" cellspacing="0" width="98%" border="0">
			<col width="100%" align="left"/>			
			<tr>
				<td  style="padding-left:10px;padding-top:10px">
					<input type="text" id="sFullTextSearch" name="sFullTextSearch"  autocomplete="off" class="textbox" size="99%" value="<?= $this->listTypeName;?>">
					<input type="button" value="Tìm kiếm" class="add_large_button"  onchange="handler(event)" onclick="actionUrl('');"> 
				</td>
			</tr>
		</table>
	</div>
	<table width='98%'  border='0' cellspacing='0' cellpadding='0' class="table_title">
		<tr>
			<td class="large_title" style="padding-left:7px;text-align:left;">&nbsp;
				
			</td>
			<td style="text-align:right;" valign="bottom">
				<a   class="small_link" onclick="actionUrl('../add/'); "><?= $arrConst['_THEM'] ?> | </a>  
				<a   class="small_link" onclick="btn_update_onclick(document.getElementsByName('chk_item_id'),'../edit/');"><?= $arrConst['_SUA'] ?>  |</a> 
				<a   class="small_link" onclick="btn_update_onclick(document.getElementsByName('chk_item_id'),'../collist/');">Danh sách trường dữ liệu |</a>
				<a   class="small_link" onClick = "btn_delete_onclick(document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id_list'),'../delete/');"><?= $arrConst['_XOA'] ?></a>
			</td>
		</tr>
	</table>
	<div id="viewAllSentDocument">
		<table cellpadding="0" cellspacing="0" border="0" width="99%" align="center" class="list_table2" id="table1">
			<?php			
			$delimitor = $this->delimitor;//Lay ky tu phan cach giua cac phan tu
			//Hien thi cac cot cua bang hien thi du lieu
				$StrHeader = explode("!~~!", Efy_Library::_GenerateHeaderTable("3%" . $delimitor . "10%" . $delimitor . "67%" . $delimitor . "20%"
												,'<input type="checkbox" name="chk_all_item_id"  onclick="checkbox_all_item_id(document.forms[0].chk_item_id);">' . $delimitor .$arrConst['_THU_TU'] . $delimitor . "Tên báo cáo" . $delimitor . $arrConst['_TINH_TRANG']
												,$delimitor));
			echo $StrHeader[0];				
			echo $StrHeader[1]; //Hien thi <col width = 'xx'><...		
			//Dinh nghia URL
			$sCurrentStyleName = "round_row";	
			for($index = 0;$index < sizeof($arrRecordType) ;$index++){
				$sPk						= $arrRecordType[$index]['PK_LIST_RECORD'];			
				$iOrder						= $arrRecordType[$index]['C_ORDER'];						
				$sName 						= Efy_Function_RecordFunctions::searchStringColor($this->sFullTextSearch,$arrRecordType[$index]['C_NAME']).'&nbsp;';
				$sStatus		 			= $arrRecordType[$index]['C_STATUS'];
				If($sStatus == "HOAT_DONG"){
					$sStatus = "Hoạt động";
				}else{
					$sStatus = "Không hoạt động";
				}
				if ($sCurrentStyleName == "odd_row"){
					$sCurrentStyleName = "round_row";
				}else{
					$sCurrentStyleName = "odd_row";					
				}?>					
				<tr class="<?=$sCurrentStyleName?>" <?= $sColor ?> >	
					<td align="center" style="padding-left:3px;padding-right:3px;" class="normal_label">					
						<?=$this->formCheckbox('chk_item_id',$sPk, array('checked' => false,'onclick' =>'selectrow(this)'));?>					
					</td>
					<td align="center"  ondblclick="item_onclick('<?=$sPk?>','../edit/')" onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$sPk?>');" style="padding-left:3px;padding-right:3px;"  class="normal_label" >
						<?=$iOrder?>
					</td>								
					<!--Hien ket qua xu ly!-->	
					<td align="left"  ondblclick="item_onclick('<?=$sPk?>','../edit/')"  onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$sPk?>');"  style="padding-left:3px;padding-right:3px;" class="normal_label"><?= $sName?></td>
					<td align="center" ondblclick="item_onclick('<?=$sPk?>','../edit/')" onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$sPk?>');"  style="padding-left:3px;padding-right:3px;" class="normal_label"><?= $sStatus ?></td>	
				</tr><?php
			}					
			//Tu dien cac dong trang trong truong hop du lieu tra ve < so row _CONST_NUMBER_OF_ROW_PER_LIST	
				echo Efy_Library::_addEmptyRow($this->iCountElement,15 -sizeof($arrRecordType),$sCurrentStyleName,4);
			?>
		</table>	
		<!--Hien thi trang can xem!-->
	</div>
	<?php echo $this->search_textselectbox ;?>
	<table width='100%'  border='0' cellspacing='0' cellpadding='0' align="center">
		<tr>
			<td style="padding-top: 5px; padding-bottom: 5px;" align="center" valign="middle">
				<input id="btn_add" name="btn_add" type="button" class="add_large_button" value="<?= $arrConst['_THEM']?>" onclick="actionUrl('../add/');">
				<input type="button" class="add_large_button" value="<?= $arrConst['_SUA']?>" onclick="btn_update_onclick(document.getElementsByName('chk_item_id'),'../edit/');">
				<input type="button" class="add_large_button" value="Danh sách trường dữ liệu" onclick="btn_update_onclick(document.getElementsByName('chk_item_id'),'../collist/');">
				<?php echo $this->formButton("btn_delete",$arrConst['_XOA'],array("type"=>"button","class"=>"add_large_button","onClick"=>"btn_delete_onclick(document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id_list'),'../delete/');")). "&nbsp;"; ?>
			</td>	
		</tr>
	</table>
</div>
</form>
<script type="text/javascript">
var keyEnter="13";
var x='';	
function handler(e){
	//IE return :event.keyCode; FF return : e.which;
	var  x=(window.event)?event.keyCode:e.which; 
	if (x==13){	//Enter					
				document.getElementsByTagName('form')[0].action = '';
				document.getElementsByTagName('form')[0].submit();
	}
}	
if (!document.all){
	window.captureEvents(Event.KEYPRESS);
	window.onkeypress=handler;
}else{
	document.onkeypress = handler;
}
</script>



