<form action="index" method="POST" name="frmLogin">	
	<?php echo $this->formHidden("hdn_option","",null); ?>
	<?php echo $this->formHidden("hdn_autorem","0",null); ?>
	<?php
		$arrConst = $this->arrConst;
		$sUrlEdit  = "../edit/";
		$hdhOption= $this->hdh_option;
		$sUserName= $this->txt_usename;
		$sPassWord= $this->txt_password;
		$sUserNameTemp = $this->sUserNameTemp;
	?>
<table cellpadding="0" cellspacing="0" align="center" width="96%" bgcolor="#ffffff">
	<tr class='nen_dao_left'>
    	<td colspan="2" class="top_banner" height="70px" valign="bottom">ỦY BAN NHÂN DÂN HUYỆN LỆ THỦY<br /><span>Địa chỉ: TT Kiến Giang - huyện Lệ Thủy - tỉnh Quảng Bình</span> </td>
    </tr>
    <tr>
    	<td height="20px"></td>
    </tr>
	<tr>
    	<td width="100%" bgcolor="#ffffff" >
        	<table align="center" cellpadding="0" cellspacing="0" class = 'nen_dao_xuan'>
            	<tr>
                    <td colspan="2" class="tieu_de" align="center" width="100%" valign="top">H&#7878; TH&#7888;NG PH&#7846;N M&#7872;M M&#7896;T C&#7916;A &#272;I&#7878;N T&#7916;</td>
                </tr>
                <tr>
                	<td colspan="2" height="50px"></td>
                </tr>
                <tr>
                	<td class="icon_ttdh"></td>
                	<td class="tt_dieu_hanh" valign="top">
                    <span>Ti&#7871;p nh&#7853;n v&#224; tr&#7843; k&#7871;t qu&#7843;<br /><p>
                    - Ti&#7871;p nh&#7853;n h&#7891; s&#417;, in gi&#7845;y bi&#234;n nh&#7853;n, in phi&#7871;u b&#224;n giao, chuy&#7875;n h&#7891; s&#417; ph&#242;ng ban chuy&#234;n m&#244;n gi&#7843;i quy&#7871;t.<br />
                    - Tr&#7843; k&#7871;t qu&#7843; v&#224; thu l&#7879; ph&#237; gi&#7843;i quy&#7871;t theo quy &#273;&#7883;nh.</p>                    
                    </td>
                </tr>
                <tr>
                	<td colspan="2" height="30px"></td>
                </tr>
                <tr>
                	<td class="icon_qlvb"></td>
                	<td class="qlvb" valign="top">
                    <span>Th&#7909; l&#253; gi&#7843;i quy&#7871;t</span><br /><p>
                    Ph&#226;n c&#244;ng th&#7909; l&#253; h&#7891; s&#417;, c&#7853;p nh&#7853;t ti&#7871;n &#273;&#7897; th&#7909; l&#253; h&#7891; s&#417;, chuy&#7875;n x&#7917; l&#253; h&#7891; s&#417; (chuy&#7875;n v&#7873; m&#7897;t c&#7917;a y&#234;u c&#7847;u b&#7893; sung ho&#7863;c t&#7915; ch&#7889;i gi&#7843;i quy&#7871;t), tr&#236;nh duy&#7879;t h&#7891; s&#417;.</p>
                    </td>
                </tr>
                <tr>
                	<td colspan="2" height="30px"></td>
                </tr>
                <tr>
                	<td class="icon_ecs"></td>
                	<td class="mot_cua" valign="top">
                    <span>Ph&#234; duy&#7879;t h&#7891; s&#417;</span><br /><p>
                    Xem x&#7871;t ti&#7871;n &#273;&#7897; v&#224; k&#7871;t qu&#7843; th&#7909; l&#253; h&#7891; s&#417;, duy&#7879;t h&#7891; s&#417;.</p>
                    </td>
                </tr>
            </table>         
        </td>
    	<td>        
            <table width="26.9%" align="right" cellpadding="0" cellspacing="0">
                <tr bgcolor="#27559B">
                    <td>
                        <table width="90%" align="center" bgcolor="#fffbe5" style="border: #f1ebcd 1px solid; ">
                            <tr>
                                <td><img src="<?= Efy_Init_Config::_setWebSitePath()?>public/images/img_dangnhap1.gif" />
                                </td>
                            </tr>
                            
                            <tr>
                            	<td height="2px"></td>
                            </tr>																
                            <!--Username-->
                            <tr>
                                <td  class="normal_label" style="padding-left:11px; font-weight:bold;" ><?=$arrConst['_TEN_DANG_NHAP'];?> </td>
                            </tr>
                            <tr>
                                <td align="center"><input type="text" align= "center" style="width:90%;" id="txt_usename" name="txt_usename" size="50" value="<? echo $sUserNameTemp; ?>"  option = "false" class="textbox normal_label" message="Phải nhập tên đăng nhập!" onKeyDown="change_focus_in_login(document.forms['frmLogin'],this,event)"></td>
                            </tr>
                            <tr>
                                <td class="normal_label" style="padding-left:11px; font-weight:bold;"><?=$arrConst['_MAT_KHAU'];?> </td>
                            </tr>
                            <tr>
                                <td align="center"><input type="password" align= "center" style="width:90%" id="txt_password" name="txt_password" size="50" value="<?=$this->txt_password;?>"  option = "false" class="textbox normal_label" message="Phải nhập mật khẩu!" onKeyDown="change_focus_in_login(document.forms['frmLogin'],this,event)"></td>
                            </tr>
                            <tr>
                                <td class="ghi_nho_mk" style="padding-left:10px;" valign="top"><input type="checkbox" optional = "true" name="ghinhomatkhau"  id="ghinhomatkhau" onKeyDown="change_focus_on_firefox(document.forms['frmLogin'],this,event)" /><label for="ghinhomatkhau" style="cursor:pointer;">Ghi nh&#7899; &#273;&#259;ng nh&#7853;p </label></td>
                            </tr>
                            <tr>
                                <td  align="center" class="body">
                            	   <button name="btn_login" id="btn_login" type="button" class="add_large_button" onClick="btn_save_onclick()", onKeyDown="change_focus_in_login(document.forms['frmLogin'],this,event)">&#272;&#259;ng nh&#7853;p</button>  
                                </td>
                            </tr>
                            <tr>
                            	<td height="5px"></td>
                            </tr>																
                            <tr class="anh">
                                <td class="ho_tro_kt"  height="60px">H&#7895; tr&#7907; k&#7929; thu&#7853;t <br /><span>Hotline: 0485 875 921<br />Email: tech@efy.com.vn</span></td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
     <tr>
    	<td colspan="2" height="15px"></td>
    </tr>
    <tr>
    	<td colspan="2" class="footer" align="center">Copyright &copy; 2011 - C&#244;ng ty C&#7893; ph&#7847;n C&#244;ng ngh&#7879; Tin H&#7885;c EFY Vi&#7879;t Nam</td>
    </tr>
</table>					
</form>
<script language="JavaScript">
set_focus(document.forms[0]);
if(document.getElementById('txt_usename').value ==''){
	document.getElementById('txt_usename').focus();	
}else{
	document.getElementById('txt_password').focus();
	document.getElementById('txt_password').select();
}
shortcut.add("Ctrl+K",function() {
	document.getElementById('txt_password').focus();
	document.getElementById('txt_password').select();
});
window.dialogHeight = "270pt";
window.dialogWidth = "420pt";
window.dialogTop = "80pt"; 
function btn_save_onclick(){
	if (verify(document.forms[0])){
		document.forms[0].hdn_option.value = "1";
		if(document.forms[0].ghinhomatkhau.checked){
			document.forms[0].hdn_autorem.value = '1';
		}
		actionUrl('');
		}
	}	
	
var x='';
function handler(e){
//IE return :event.keyCode; FF return : e.which;
var x=(window.event)?event.keyCode:e.which;
if (x==13){ //Enter
//btn_enrollment_wait('');
}

}
if (!document.all){
window.captureEvents(Event.KEYPRESS);
window.onkeypress=handler;
}else{
document.onkeypress = handler;
} 
 
if(<?=$this->sCheckReme?>){
	document.forms[0].ghinhomatkhau.checked = true;	
}else{
	document.forms[0].ghinhomatkhau.checked = false;
}
</script>
