<?php
$objrecordfun = new Efy_Function_RecordFunctions();
$sRecordIdList = $this->sRecordIdList;
$arrinfoRecordType = $this->arrinfoRecordType;
//Can bo thu ly
$sHandleList = $arrinfoRecordType['C_HANDLER_ID_LIST'];
$arrHandleList = explode(',',$sHandleList);
$sUnitId = $objrecordfun->_get_item_attr_by_id($_SESSION['arr_all_staff'],$_SESSION['staff_id'],'unit_id');
?>
<form action="index" method="POST" id="frmSubmitorder" autocomplete="off" enctype="multipart/form-data">
    <?php echo $this->formHidden("hdn_record_id_list",$this->sRecordIdList,null); ?>
    <!--Bien hdn_deleted_new_file_id_list dung de luu Id cua nhung doi tuong file dinh kem se xoa-->
    <?php echo $this->formHidden("hdn_deleted_new_file_id_list","",null); ?>
    <!--Bien hdn_deleted_exist_file_id_list dung de ...-->
    <?php echo $this->formHidden("hdn_deleted_exist_file_id_list","",null); ?>
    <?php echo $this->formHidden("hdn_update","1",null); ?>

    <div style="width: 99%;padding-left: 5px;">
        <div class="normal_title">DANH SÁCH HỒ SƠ CHUYỂN XỬ LÝ</div>
        <div class="general_information" id="general_information">
            <?=$this->general_information?>
        </div>
        <div class="normal_title">NỘI DUNG XỬ LÝ</div>
        <div id="contentXml" style="margin: 0;">
            <div id="header_update_form">
                <div style="padding-top: 15px;">
                    <label>Hình thức xử lý<span class="requiein">*</span></label>
                    <div style="display: inline-block;width: 75%;">
                        <div style="display: inline-block;width: 100%;">
                            <input style="float: left;" type="radio" class="normal_radiobutton" value="PHAN_CONG" checked="checked" name="chk_process_type" id="chk_process_type1">
                            <label style="float: left;padding-left: 5px;width: 90%;" for="chk_process_type1" class="normal_label">Phân công cán bộ thụ lý</label>
                        </div>
                        <div id="div_handle" style="display: inline-block;width: 94%;margin: 5px;">
                            <fieldset class="normal_label" style="border: 1px solid #dddddd;">
                                <legend style="border: 1px solid #DDDDDD;padding: 3px;box-shadow: 1px 2px 3px #888888;">Chọn cán bộ</legend>
                                <?
                                foreach($arrHandleList as $key => $sHandleid) {
                                    $sHandlename = $objrecordfun->getNamePositionStaffByIdList($sHandleid);
                                    $sunitid = $objrecordfun->_get_item_attr_by_id($_SESSION['arr_all_staff'], $sHandleid,'unit_id');
                                    if($sunitid==$sUnitId) {
                                    ?>
                                    <div style="display: inline-block;width: 100%; margin-left: 20px; margin-top: 3px;">
                                        <input style="float: left;" type="radio" class="normal_radiobutton" value="<?=$sHandleid;?>" <?=$checkHand?> name="chk_handle" id="chk_handle<?=$key;?>">
                                        <label style="float: left;padding-left: 5px;" for="chk_handle<?=$key;?>" class="normal_label"><?=$sHandlename;?> </label>
                                    </div>
                                <? }
                                } ?>
                            </fieldset>
                        </div>
                    </div>
                </div>
                <div id="div_limit_date" style="padding-top: 15px;">
                    <label>Hạn xử lý</label>
                    <input style="width:15%;font-family: arial;font-size: 10pt;" type="text" class="textbox" name="limit_date" id="limit_date">
                </div>
                <div style="padding-top: 15px;">
                    <label>Ý kiến<span class="requiein">*</span></label>
                    <textarea style="width:70%;font-family: arial;font-size: 10pt;" name="idea" id="idea" class="normal_textarea">Chuyển cán bộ chuyên môn thụ lý!</textarea>
                </div>
                <div style="padding-top: 15px;">
                    <label>File đính kèm</label>
                    <div style="display: inline-block;width: 75%;"><?php echo $this->AttachFile;?></div>
                </div>
                <div id="clear"></div>
            </div>
        </div>
    </div>
    <div style="width: 99%;padding-top: 12px;text-align: center;">
        <input type="button" style="margin-left:0px;" name="btnSubmit" id="btnSubmit" value="Cập nhật" class="add_large_button">
        <input type="button" style="margin-left:0px;" name="btnback" id="btnback" value="Quay lại" class="add_large_button">
    </div>
</form>
<script type="text/javascript">
    var baseUrl = "<?=$this->baseUrl();?>";
    var obj_record_approve = new record_approve(baseUrl, 'record', 'assign');
    jQuery(document).ready(function ($) {
        obj_record_approve.loadAddEven();
    });
</script>