<?php
$dir = $this->baseUrl() . '/public/js/jquery_file_upload/';
?>
<link rel="stylesheet" href="<?= $dir ?>css/jquery.fileupload.css">
<script src="<?= $dir ?>js/jquery.min.js" type="text/javascript"></script>
<script src="<?= $dir ?>js/vendor/jquery.ui.widget.js" type="text/javascript"></script>
<!--
-->
<script src="<?= $dir ?>js/tmpl.min.js" type="text/javascript"></script>
<script src="<?= $dir ?>js/load-image.min.js" type="text/javascript"></script>
<script src="<?= $dir ?>js/canvas-to-blob.min.js" type="text/javascript"></script>
<script src="<?= $dir ?>js/jquery.blueimp-gallery.min.js" type="text/javascript"></script>
<script src="<?= $dir ?>js/jquery.iframe-transport.js" type="text/javascript"></script>
<script src="<?= $dir ?>js/jquery.fileupload.js" type="text/javascript"></script>
<script src="<?= $dir ?>js/jquery.fileupload-process.js" type="text/javascript"></script>
<script src="<?= $dir ?>js/jquery.fileupload-image.js" type="text/javascript"></script>
<script src="<?= $dir ?>js/jquery.fileupload-audio.js" type="text/javascript"></script>
<script src="<?= $dir ?>js/jquery.fileupload-video.js" type="text/javascript"></script>
<script src="<?= $dir ?>js/jquery.fileupload-validate.js" type="text/javascript"></script>
<script src="<?= $dir ?>js/jquery.fileupload-ui.js" type="text/javascript"></script>

<script src="<?= $dir ?>js/md5.min.js" type="text/javascript"></script>
<script src="<?= $dir ?>js/main.js" type="text/javascript"></script>

<div class="fileupload">
    <div>
		<span class="btn btn-success fileinput-button">
            <i class="glyphicon glyphicon-plus"></i>
			<span>Chọn tệp tin đính kèm...</span>
			<input type="file" multiple="" method="POST" enctype="multipart/form-data" name="files[]">
		</span>

        <div class="files">
            <div class="file_container template-download fade">
                <div class="left">
                    <span class="fa fa-check"></span>
                </div>
                <div class="center">
                    <p file_name="1435775001!~~!IMG_0342.JPG" class="file_report upload_complete">
                        <a href="http://localhost:85/mkntc-nd-00/main/file/download?id=1435775001%21~~%21IMG_0342.JPG"
                           target="_blank">IMG_0342.JPG</a>
                    </p>
                </div>
                <div class="right">
                    <!--<span title = "Xóa tệp tin" class="fa fa-trash delete glyphicon glyphicon-trash" data-type="POST" data-url="/mkntc-nd-00/main/file/upload/?file=1435775001%21~~%21IMG_0342.JPG&amp;_method=DELETE"></span>-->
                    <button data-type="POST"
                            data-url="/mkntc-nd-00/main/file/upload/?file=1435775001%21~~%21IMG_0342.JPG&amp;_method=DELETE"
                            class="btn btn-danger delete">
                        <i class="glyphicon glyphicon-trash"></i>
                        <span>Xóa</span>
                    </button>
                    <input type="checkbox" name="delete" value="1" class="toggle">
                </div>

            </div>
        </div>
    </div>
</div>

<!-- The template to display files available for download -->
<script id="template-upload" type="text/x-tmpl">
<!-- The template to display files available for upload -->
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <div class = "file_container template-upload fade">
    	<div class = "left">
    		<span class = "percent"></span>
    	</div>
    	<div class = "center">
    		<p class = "file_uploading" id = "_{%=md5(file.name)%}">{%=file.name%}</p>
    	</div>
    	<div class = "right">
    	{% if (!i) { %}
        	<button class="btn btn-warning cancel">
                <i class="glyphicon glyphicon-ban-circle"></i>
                <span>Loại bỏ</span>
            </button>
        {% } %}
    	</div>
    </div>
{% } %}



</script>
<script id="template-download" type="text/x-tmpl">
<!-- The template to display files available for download -->
<table>
<colgroup><col width="10%"><col width="75%"><col width="15%"></colgroup>
{% for (var i=0, file; file=o.files[i]; i++) { %}
	<div class = "file_container template-download fade in">
	    {% if (file.error) { %}
	    	<div class = "left">
	    	</div>
	    	<div class = "center">
	    		<p class = "file_report">
	    			<span class="label label-danger upload_error">Tải tệp tin không thành công</span>
	    		</p>
	    	</div>
	    {% } %}
	    {% if (file.deleteUrl) { %}


	    	<div class = "left">
	    		<span class="fa fa-check"></span>
	    	</div>
	    	<div class = "center">
	    		<p class = "file_report upload_complete" file_name = "{%=file.name%}">
	    			<a target="_blank" href = "{%=file.url%}">{%=file.view_name%}</a>
	    		</p>
	    	</div>
	    	<div class = "right">
	    		<!--<span title = "Xóa tệp tin" class="fa fa-trash delete glyphicon glyphicon-trash" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"></span>-->
				<button class="btn btn-danger delete" data-url="{%=file.deleteUrl%}" data-type="{%=file.deleteType%}">
				<i class="glyphicon glyphicon-trash"></i>
				<span>Xóa</span>
				</button>
				<input class="toggle" type="checkbox" value="1" name="delete">
	    	</div>
	    {% } else { %}
	    	<div class = "right">
	        		<button class="btn btn-warning cancel">
                        <i class="glyphicon glyphicon-ban-circle"></i>
                        <span>Loại bỏ</span>
                    </button>
	        </div>
	    {% } %}
   	</div>
{% } %}
</table>


</script>
<script>
    var uploading = 0;
    var done2submit = 0;
    var trueConfirm = 0;
    var deleteMouseDownFired = false;
    var globalDeleteConfirmed = false;
    var files = [
        {
            "name": "fileName.jpg",
            "size": 775702,
            "type": "image/jpeg",
            "url": "http://mydomain.com/files/fileName.jpg",
            "deleteUrl": "http://mydomain.com/files/fileName.jpg",
            "deleteType": "DELETE"
        },
        {
            "name": "file2.jpg",
            "size": 68222,
            "type": "image/jpeg",
            "url": "http://mydomain.com/files/file2.jpg",
            "deleteUrl": "http://mydomain.com/files/file2.jpg",
            "deleteType": "DELETE"
        }
    ];
    $(function () {
        $('.fileupload').each(function () {
            $(this).fileupload({
                dropZone: $(this),
                url: baseUrl + '/main/file/upload/',
                type: 'POST',
                method: 'POST',
                dataType: 'json',
                maxChunkSize: 1000000,//100M
                autoUpload: true,
                acceptFileTypes: /(\.|\/)(gif|jpe?g|png|pdf|doc|docx|xls|xlsx|rar|zip|7z|xml)$/i,
                progress: function (e, data) {
                    var progress = parseInt(data.loaded / data.total * 100, 10);
                    data.context.find('span.percent').text(progress + '%');
                },
                submit: function (e, data) {
                    done2submit = 0;
                    uploading++;
                },
                always: function (e, data) {
                    uploading--;
                    if (data.textStatus == 'success') {
                        var errors = $('span.upload_error').length;
                        if (uploading == 0 && done2submit == 1 && errors == 0) {
                            $('form#frmRefuse #btn_saveHS').trigger('click');
                        }
                        else {
                            if (errors > 0 && done2submit == 1) {
                                jAlert('Có ' + errors + ' tệp tin tải lên không thành công. Vui lòng thử lại', 'Thông báo');
                            }
                        }
                    }
                }

            })
                .bind(
                'fileuploaddestroy',
                function (e, data) {
                    if (deleteMouseDownFired) {
                        if (globalDeleteConfirmed) {
                            return true;
                        }
                        return false;
                    }
                    else {
                        return confirm("Delete this file ?");
                    }
                })
        });
    });
</script>