<form action="index" method="POST" autocomplete="off" name="form">
<div><?php
	$arrConst = $this->arrConst;
	$arrRecordType = $this->arrRecordType;
	$arrCate = $this->arrCate;
    $arrStatus = $this->arrStatus;
	?>
	<table width='100%'  border='0' cellspacing='0' cellpadding='0' class="table_title">
		<tr>
			<td class="large_title" style="padding-left:7px;text-align:left;">
				<!--Cac doi tuong hidden tren form-->
				<?php echo $this->formHidden("hdn_object_id_list","",null); ?>
				<?php echo $this->formHidden("hdn_filter_xml_tag_list",$this->filterXmlTagList,null); ?>
				<?php echo $this->formHidden("hdn_filter_xml_value_list",$this->filterXmlValueList,null); ?>
				<?php echo $this->formHidden("hdn_record_number_page",$this->numRowOnPage,null); ?>	
				<?php echo $this->formHidden("hdn_object_id","",null); ?>
				<?php echo $this->formHidden("hdn_XmlTagValueList",$this->XmlTagValueList,null); ?>	
				<!--Bien hdn_deleted_exist_file_id_list dung de ...-->	
				<?php echo $this->formHidden("hdn_deleted_exist_file_id_list","",null); ?>
				<?php echo $this->formHidden("hdn_cate","",null); ?>	
				
				<!--Cac doi tuong hidden tren form-->
				<?=	$this->bodyTitle ;?>
			</td>
		</tr>
	</table>
	<div id="filter">			
		<table cellpadding="0" cellspacing="0" width="98%" border="0">
			<col width="100%" align="left"/>			
			<tr>
				<td  style="padding-left:10px;padding-top:10px">
					<input type="text" id="sFullTextSearch" name="sFullTextSearch"  autocomplete="off" class="textbox" size="99%" value="<?= $this->sFullTextSearch ?>">
				</td>
			</tr>
            <tr>
                <td  style="padding-left:10px;">
                    <select  id="C_CATE" name="C_CATE"   option = "false"  style="width:34%;" class="textbox normal_label"  message="<?php echo "Phải xác định lĩnh vực";?>" onchange="save_select_box(this);" >
                        <option id="" name = "" value=""  >-- Lấy tất cả lĩnh vực --</option>
                        <?php echo Extra_Util::_generateSelectOption($arrCate,'C_CODE','C_CODE','C_NAME',$arrResult['C_CATE']);?>
                    </select>
                    <select  id="sStatus" name="sStatus"   option = "false"  style="width:33%;" class="textbox normal_label" >
                        <?php echo Extra_Util::_generateSelectOption($arrStatus,'code','code','name',$this->sStatus);?>
                    </select>
                    <input type="button" value="Tìm kiếm" class="add_large_button"  onchange="handler(event)" onclick="actionUrl('');">
                </td>
            </tr>
		</table>
	</div>
	<table width='99%'  border='0' cellspacing='0' cellpadding='0' class="table_title">
		<tr>
			<td class="large_title" style="padding-left:7px;text-align:left;">&nbsp;
				
			</td>
			<td style="text-align:right;" valign="bottom">
                <a   class="small_link" onclick="btn_update_onclick(document.getElementsByName('chk_item_id'),'../config'); ">Cấu hình</a>
                <?php if($this->sOwnerCode == $this->sOwnerCodeRoot){?>
                <a   class="small_link" onclick="actionUrl('../add'); "> | <?= $arrConst['_THEM'] ?> | </a>
				<a   class="small_link" onclick="btn_update_onclick(document.getElementsByName('chk_item_id'),'../edit');"><?= $arrConst['_SUA'] ?>  |</a> 
				<a   class="small_link" onClick = "btn_delete_recordtype(document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id_list'),'../delete/');"><?= $arrConst['_XOA'] ?></a>
                <?php }?>
			</td>
		</tr>
	</table>
	<div id="viewAllSentDocument">
		<table cellpadding="0" cellspacing="0" border="0" width="98%" align="center" class="list_table2" id="table1">
			<?php			
			$delimitor = $this->delimitor;//Lay ky tu phan cach giua cac phan tu
			//Hien thi cac cot cua bang hien thi du lieu
				$StrHeader = explode("!~~!", Extra_Util::_GenerateHeaderTable("3%" . $delimitor . "10%" . $delimitor . "17%" . $delimitor . "50%" . $delimitor . "20%"
												,'<input type="checkbox" name="chk_all_item_id"  onclick="checkbox_all_item_id(document.forms[0].chk_item_id);">' . $delimitor .$arrConst['_THU_TU']  . $delimitor . $arrConst['_MA_HO_SO'] . $delimitor . $arrConst['_TEN_HO_SO'] . $delimitor . 'Trạng thái'
												,$delimitor));
			echo $StrHeader[0];				
			echo $StrHeader[1]; //Hien thi <col width = 'xx'><...		
			//Dinh nghia URL
			$sUrView  = "view";
			$sCurrentStyleName = "round_row";	
			for($index = 0;$index < sizeof($arrRecordType) ;$index++){
				$sPk						= $arrRecordType[$index]['PK_RECORDTYPE'];			
				$iOrder						= $arrRecordType[$index]['C_ORDER'];	
				$sCode						= Extra_Ecs::searchCharColor($this->sFullTextSearch,$arrRecordType[$index]['C_CODE']).'&nbsp;';
				$sName 						= Extra_Ecs::searchStringColor($this->sFullTextSearch,$arrRecordType[$index]['C_NAME']).'&nbsp;';
				$sStatus		 			= $arrRecordType[$index]['C_STATUS'];
				$sRecordType		 		= $arrRecordType[$index]['C_RECORD_TYPE'];
				If($sStatus == "HOAT_DONG"){
					$sStatus = "Hoạt động";
				}else{
					$sStatus = "Không hoạt động";
				}
				If($sRecordType == "LIEN_THONG"){
					$sColor = " style='color:#0682b6;' ";
				}else{
					$sColor = "";
				}
				if ($sCurrentStyleName == "odd_row"){
					$sCurrentStyleName = "round_row";
				}else{
					$sCurrentStyleName = "odd_row";					
				}?>					
				<tr class="<?=$sCurrentStyleName?>" <?= $sColor ?> >	
					<td align="center" style="padding-left:3px;padding-right:3px;" class="normal_label">					
						<?=$this->formCheckbox('chk_item_id',$sPk, array('checked' => false,'onclick' =>'selectrow(this)'));?>					
					</td>
					<td align="center"  ondblclick="item_onclick('<?=$sPk?>','../edit')" onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$sPk?>');" style="padding-left:3px;padding-right:3px;"  class="normal_label" >
						<?=$iOrder?>
					</td>								
					<!--Hien thi trich yeu!-->					
					<td align="center"   ondblclick="item_onclick('<?=$sPk?>','../edit')" onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$sPk?>');"  style="padding-left:3px;padding-right:3px;" class="normal_label"><?=$sCode ?></td>
					<!--Hien ket qua xu ly!-->	
					<td align="left"  ondblclick="item_onclick('<?=$sPk?>','../edit')"  onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$sPk?>');"  style="padding-left:3px;padding-right:3px;" class="normal_label"><?=  $sName?></td>
					<td align="center" ondblclick="item_onclick('<?=$sPk?>','../edit')" onclick="set_hidden(this,document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id'),'<?=$sPk?>');"  style="padding-left:3px;padding-right:3px;" class="normal_label"><?= $sStatus ?></td>	
				</tr><?php
			}					
			//Tu dien cac dong trang trong truong hop du lieu tra ve < so row _CONST_NUMBER_OF_ROW_PER_LIST	
				echo Extra_Util::_addEmptyRow($this->iCountElement,15 -sizeof($arrRecordType),$sCurrentStyleName,5);
			?>
		</table>	
		<!--Hien thi trang can xem!-->
	</div>
	
	<?php echo $this->search_textselectbox ;?>
	<table width='100%'  border='0' cellspacing='0' cellpadding='0' align="center">
		<tr>
			<td style="padding-top: 5px; padding-bottom: 5px;" align="center" valign="middle">
                <input id="btn_config" name="btn_config" type="button" class="add_large_button" value="Cấu hình" onclick="btn_update_onclick(document.getElementsByName('chk_item_id'),'../config');">
                <?php if($this->sOwnerCode == $this->sOwnerCodeRoot){?>
				<input id="btn_add" name="btn_add" type="button" class="add_large_button" value="<?= $arrConst['_THEM']?>" onclick="actionUrl('../add');">
				<input type="button" class="add_large_button" value="<?= $arrConst['_SUA']?>" onclick="btn_update_onclick(document.getElementsByName('chk_item_id'),'../edit');">
				<?php echo $this->formButton("btn_delete",$arrConst['_XOA'],array("type"=>"button","class"=>"add_large_button","onClick"=>"btn_delete_recordtype(document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id_list'),'../delete/');")). "&nbsp;"; ?>
                <?php } ?>
			</td>	
		</tr>
	</table>
</div>
</form>
<script type="text/javascript">
var keyEnter="13";
var x='';	
function handler(e){
	//IE return :event.keyCode; FF return : e.which;
	var  x=(window.event)?event.keyCode:e.which; 
	if (x==13){	//Enter					
				document.getElementsByTagName('form')[0].action = '';
				document.getElementsByTagName('form')[0].submit();
	}
}	
if (!document.all){
	window.captureEvents(Event.KEYPRESS);
	window.onkeypress=handler;
}else{
	document.onkeypress = handler;
}
</script>
<script>
function save_select_box(index){	
	document.getElementById('hdn_cate').value = index.value;	
}
document.getElementById('C_CATE').value = '<?php echo $_SESSION['hdn_cate'];?>';
</script>


