
<form action="index" method="POST" id="frmAddListType" enctype="multipart/form-data">
	<table cellpadding="0" cellspacing="0" width="100%" border="0">
		<!--tao tac hidden!-->
		<tr>
			<td>
			<!--Luu gia tri kiem tra cho cap nhat -->
			<?php echo $this->formHidden("hdn_update",'',null); ?>						
			</td>
		</tr>
	</table>
	<table width='98%'  border='0' cellspacing='0' cellpadding='0' class="table_title">
		<tr>
			<td class="large_title" style="padding-left:7px;text-align:left;">
				<?=$this->bodyTitle;?><br>				
			</td>
		</tr>
	</table><br />
	<div id="content" style="border-bottom:1px solid #3399FF;padding-bottom:5px;margin-bottom:10px;border-top:1px solid #3399FF;">
		
		<div id="body_content">
			<div>
				<div><label class="lbl_title normal_label">File cần phục hồi</label></div>
				<div>
					<dd id = "file_from_server">
						<?=$this->formText('txt_xml_file_name',$this->arrInput['C_XML_FILE_NAME'],array('type'=>'text','style'=>'display:inline;','size'=>77, 'class'=>'normal_textbox', 'optional'=>true,'onKeyDown'=>'change_focus(document.forms(0),this)', ));?>
						<?=$this->formButton("popupDialog","Browse",array("type"=>"button",'style'=>'display:inline;',"class"=>"add_large_button","onClick"=>"openmypage(); return false"))?>	
					</dd>
					<dd id = "file_form_clien" style = "display:none;"><?=$this->formFile('C_XML_FILE_NAME',$this->arrInput['C_XML_FILE_NAME'],array('size'=>50));?></dd>
				</div>	
			</div>
			<div>						
				<!--Goi mot Digloa bang javascript-->				
			 	 <div id="somediv" style="display:none">
					<?php echo $this->divDialog;?>
				 </div>	
			</div>
			
		</div>
		<div id = "button">
			<button name="btn_backup" id="btn_restore" type="button" style="Width:12%" value="Phục hồi dữ liệu" class="add_large_button" onClick="restore_click('<?php echo $this->sDatabaseName?>','<?php echo $this->sPathbackup?>',document.getElementById('txt_xml_file_name').value,'<?php echo $this->urlbackup?>');">Phục hồi dữ liệu</button>												
		</div>
	</div>
</form>
<div id = "ajax_loader" style = "display:none;">
	<img src = "<?=$this->baseUrl?>images/ajax-loader1.gif" /><br>
	<div style = "color:blue;font-weight:bold;text-align:center;width:100%;">Đang phục hồi dữ liệu</div>
</div>
<script type="text/javascript">
	function openmypage(){ 
		divwin=dhtmlwindow.open("divbox", "div", "somediv", "EFY.COM.VN", "width=450px,height=300px,left=300px,top=100px,resize=1,scrolling=1")
	}
	function restore_click(p_databasename,p_path,p_file,p_url){
		if(p_file==''){
			alert("Nhập tên file");
			document.getElementById('txt_fileName').focus();
			return;
		}
		$('#ajax_loader').modal({close:false, maxHeight:50, maxWidth:235,autoResize:true});
		$.ajax({
			  url: p_url,type: 'POST',dataType: 'html',
			  data:'database=' + p_databasename
			  + '&fileName=' + p_path + p_file,
			  success: function(data){
				$.modal.close();
				alert(data);
		      }
		 });
	}

</script>
<?php //} 
//else 
//	echo 'Bạn không có quyền truy cập chức năng này';
?>