<!DOCTYPE html>
<html>
<?php
$sysConst = Zend_Registry::get('__sysConst__');
$userIdentity = G_Account::getInstance()->getIdentity();
$urlmini = $this->baseUrl . 'min/index.php?f=';
?>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $sysConst->appName; ?></title>
    <link rel="Shortcut Icon" href="<?= $this->baseUrl ?>images/logo/logo.ico" type="image/x-icon"/>
    <link rel="stylesheet" href="<?= $this->baseUrl ?>js/ui/jquery-ui.css">
    <link rel="stylesheet" href="<?= $this->baseUrl ?>js/component/scrollbar/jquery.mCustomScrollbar.css">
    <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl ?>css/skill.css">
    <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl ?>css/jAlerts/jquery.alerts.css">
    <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl ?>css/fg.menu.css">
    <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl ?>css/chosen/chosen.css">
    <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl ?>css/skill_2.css">
    <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl?>css/jquery.autocomplete.css">
    
    <script src="<?= $urlmini . 'js/util.js' ?>" type="text/javascript"></script>
    <script src="<?= $this->baseUrl ?>js/jquery-1.10.2.min.js" type="text/javascript"></script>

    <script src="<?= $this->baseUrl ?>js/component/scrollbar/jquery.mCustomScrollbar.concat.min.js" type="text/javascript"></script>

    <?php
    $src = $urlmini . 'js/jquery-migrate-1.2.1.min.js';
    $src .= ',js/html5.js';
    $src .= ',js/jquery.base64.js';    
    ?>

    <script src="<?= $src ?>" type="text/javascript"></script>

    <?php
    $src = $urlmini . 'js/ui/jquery-ui.js';
    $src .= ',js/ui/external/jquery.ui.datepicker-vi.js';
    ?>

    <script src="<?= $src ?>" type="text/javascript"></script>
    <?php
    $src = 'js/process/paging.js,js/process/layout.js';
    ?>
    <script src="<?= $urlmini . $src ?>" type="text/javascript"></script>
    <?php
    $src = $urlmini . 'js/epilgrim.sessionTimeoutHandler.js';
    $src .= ',js/jquery.autocomplete.min.js';
    ?>
    <script src="<?= $src ?>" type="text/javascript"></script>
    
    <?php
    $src = $urlmini . 'js/jquery.alerts.js';
    $src .= ',js/chosen/chosen.jquery.js';
    $src .= ',js/libXml.js';
    $src .= ',js/jquery.md5.js';
    ?>

    <script src="<?= $src ?>" type="text/javascript"></script>
    
    <!--Dinh nghia hang so dung chung cho JS!-->
    <?= $this->JSPublicConst; ?>
    <?= $this->LoadAllFileJsCss; ?>
    <?php
    if (isset($sysConst->analyticsTracking) && $sysConst->analyticsTracking == 1) {
        include_once(dirname(__FILE__) . "/scripts/analyticstracking.phtml");
    } else { ?>
        <script type="text/javascript">
            function ga() {
            }
        </script>
    <?php
    }
    ?>

</head>
<body>
<script>
    var baseUrl = '<?=$this->baseUrl();?>';
</script>
<header>
    <div class="header_area">
        <div class="col col_logo">
            <div class="logo">
                <a href="">
                    <img STYLE="height: 100%;max-width: 100%;width: 100%;" src="<?= $this->baseUrl ?>images/img_skin/logo.png">
                </a>
            </div>
            <div class="title">
                <p class="adress">
                    <?= $sysConst->ownerFullName ?>
                </p>

                <p class="name_app">
                    <?= $sysConst->appName ?>
                </p>
            </div>
        </div>
        <!-- <div class="col col_add_tienich">
             <a href="">
                 <span class="icon_menu_ti"></span>
                 <span class="text">Tiện ích +</span>
             </a>
         </div>-->
        <div class="col col_right">
            <div class="acc">
                <a href="#">
                    <span class="name_acc"><?= $userIdentity->sFullName; ?></span>
                    <span class="avatar_acc" id="accout_info">
                        <img STYLE="max-width: 100%;"
                             src="<?= $this->baseUrl(); ?>/account/profile/getavatar">
                    </span>
                </a>

                <div class="gb_u"></div>
            </div>
            <div id="gb" class="gb_w gb_ba" tabindex="0" aria-hidden="false" aria-label="Thông tin tài khoản"
                 img-loaded="1">
                <div class="gb_z">
                    <div class="gb_z">
                        <a target="_blank" href="<?= $this->baseUrl(); ?>/account/profile/avatar/" class="gb_A gb_dc">
                            <div title="" class="gb_g gbip"></div>
                            <span class="gb_C">Thay đổi ảnh</span>
                        </a>

                        <div class="gb_B">
                            <div
                                class="gb_D"><?= $userIdentity->sFullName; ?></div>
                            <div class="gb_y"><a target="_blank" href="<?= $this->baseUrl(); ?>/account/profile/index/">Thông
                                    tin cá nhân</a></div>
                            <div class="gb_y"><a target="_blank"
                                                 href="<?= $this->baseUrl(); ?>/account/profile/changepass/">Thay đổi mật
                                    khẩu</a></div>
                            <a href="<?= $this->baseUrl(); ?>/dang-xuat/" class="gb_ac gbp1 gb_a">Thoát</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="noti">
                <ul>
                    <li>
                        <a rel="noti_box" class="icon_bell"></a>
                    </li>
                </ul>

                <div id="noti_box">
                    <div class="jewelBeeperHeader">
                        <div class="beeperNubWrapper"><div class="beeperNub"></div></div>
                    </div>

                    <div class="uiHeader uiHeaderBottomBorder jewelHeader">
                        <h3 aria-hidden="true" class="uiHeaderTitle">Thông báo</h3>
                    </div>

                    <div class="_33p">
                        <div class="list uiScrollableAreaWrap content mCustomScrollbar light" data-mcs-theme="minimal-dark"></div>
                    </div>

                    <div class="view_all">
                        <a href="<?= $this->baseUrl(); ?>/nhacviec">Xem tất cả</a>
                    </div>
                </div>
            </div>
            <!-- <div class="search">
                 <input class="txtData" type="text" onkeypress="" name="q" value="">
                 <span class="icon_search"></span>
             </div>-->
        </div>
    </div>
</header>
<div id="wrapper">
    <div class="wrapper_area home home_user">
        <div class="col col_01">
            <?= $this->layout()->menu; ?>
        </div>
        <div class="col col_02">
            <div class="main_content" id="main" style="overflow: hidden;">
                <?= $this->layout()->content; ?>
            </div>
        </div>
    </div>
</div>

<!-- Note -->
<div style="clear: both;"></div>
<div id="note-process" class="vY nq" style="display: none;">
    <div id="file_export">
        <div title="Tên file bao gồm ngày, tháng, năm, giờ, phút giây" class="file_export-title"></div>
        <a class="file_export-icon"></a>

        <p class="file_export_close"></p>
    </div>
    <div id="smallLoadIcon"></div>
    <div id="fade"></div>
    <div id="modalnotify">
        <img id="loader" src="<?= $this->baseUrl ?>images/img_skin/loading.gif" />
    </div>
</div>
<a href="javascript:ScrollTo()" id="gotop"></a>
<footer>
    <?= $this->layout()->footer; ?>
</footer>
</body>
<script type="text/javascript">
    $(document).ready(function () {
        $(window).scroll(function () {
            if ($(window).scrollTop() > 500) {
                $("#gotop").fadeIn("slow");
            } else {
                $("#gotop").fadeOut("slow");
            }
        })
    })
</script>
<script type="text/javascript">
    var getModulLeft = '<?= $this->getStatusLeftMenu ?>';
    var currentResource = '<?= $this->currentResource ?>';
    $(function() {
        $('.wrapper_area .categories').gmenu({callbackInit: function() {
            $('li#' + currentResource).trigger('click')
        }})
        $('body').process_layout({timeReconnect: 30000})
        <?php
            if (G_Account::getInstance()->hasIdentity()) { ?>
                $('body').sessionTimeoutHandler({
                     keepAliveUrl :           baseUrl + '/797919b5a9c95dfae9b06cf3086e40c1',
                     retrieveTimeLeftUrl :    baseUrl + '/dee5dfbe8ebdcd017a3f7fe1dedfc821',
                     logoutUrl :              baseUrl + '/dang-xuat',
                     checkTimeBeforeRedirect:  true
                 });
        <?php 
            }
        ?>
    });

    var __isActive;
    window.onfocus = function () { 
      __isActive = true; 
    }
    window.onblur = function () { 
      __isActive = false; 
    }
</script>