<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $this->appName; ?></title>
    <link rel="Shortcut Icon" href="<?= $this->baseUrl ?>images/logo/logo.ico" type="image/x-icon"/>
    <link rel="stylesheet" href="<?= $this->baseUrl ?>css/skill.css" type="text/css" media="all"/>
    <link rel="stylesheet" href="<?= $this->baseUrl ?>css/responsive.css" type="text/css" media="all"/>
    <link rel="stylesheet" type="text/css" href="<?= $this->baseUrl ?>css/jAlerts/jquery.alerts.css">
    <script src="<?= $this->baseUrl ?>js/jquery-1.10.2.min.js" type="text/javascript"></script>
    <script src="<?= $this->baseUrl ?>js/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>    
    <script src="<?= $this->baseUrl ?>js/jquery.alerts.js" type="text/javascript"></script>
</head>
<?php
$sysConst = Zend_Registry::get('__sysConst__');
?>
<body>
<div id="bg"></div>
<header>
    <div class="header_area_login">
        <ul class="list_app">
            <li>
                <a href="">
                    <img title="Thiết kế Website - Cổng thông tin điện tử"
                         src="<?= $this->baseUrl ?>images/img_content/CTT_WEBSITE.png">
                </a>
            </li>
            <li>
                <a href="">
                    <img title="Phần mềm quản lý tiếp công dân - Xử lý đơn thư khiếu nại, tố cáo"
                         src="<?= $this->baseUrl ?>images/img_content/DONTHU.png">
                </a>
            </li>
            <li>
                <a href="">
                    <img title="Phần mềm hỗ trợ kê khai hồ sơ một cửa"
                         src="<?= $this->baseUrl ?>images/img_content/HTKKHS.png">
                </a>
            </li>
            <li>
                <a href="">
                    <img title="Phần mềm một cửa điện tử" src="<?= $this->baseUrl ?>images/img_content/MOTCUA.png">
                </a>
            </li>
            <li>
                <a href="">
                    <img title="Phần mềm quản lý văn bản - Điều hành"
                         src="<?= $this->baseUrl ?>images/img_content/QLVBDH.png">
                </a>
            </li>

            <li>
                <a href="">
                    <img title="Phần mềm quản lý Cán bộ công chức"
                         src="<?= $this->baseUrl ?>images/img_content/CBCC.png">
                </a>
            </li>
            <li>
                <a href="">
                    <img title="Phần mềm một cửa Bảo hiểm" src="<?= $this->baseUrl ?>images/img_content/ecsBH.png">
                </a>
            </li>
            <li>
                <a href="">
                    <img title="Phần mềm quản lý Hộ tịch" src="<?= $this->baseUrl ?>images/img_content/QLHT.png">
                </a>
            </li>
            <li>
                <a href="">
                    <img title="Phần mềm quản lý Thi đua khen thưởng"
                         src="<?= $this->baseUrl ?>images/img_content/TDKT.png">
                </a>
            </li>
            <li>
                <a href="">
                    <img title="Phần mềm quản lý Trường học" src="<?= $this->baseUrl ?>images/img_content/QLTH.png">
                </a>
            </li>
        </ul>
    </div>
</header>
<div id="wrapper">
    <div class="wrapper_area login">
        <?= $this->layout()->content; ?>
    </div>
</div>
<footer>
    <div class="footer_area footer_login">
        <p>HỖ TRỢ KỸ THUẬT</p>

        <p>
            <span>Hotline: <?= $sysConst->supportMobile ?></span>
            <span>Email: <?= $sysConst->supportEmail ?></span>
            <span><a href="">Download Teamview (Hỗ trợ từ xa)</a></span>
        </p>

        <p class="name_company"><?= $sysConst->copyright ?></p>
    </div>
</footer>
<style>
    footer {
        right: 0;
        bottom: 0;
        left: 0;
        width: 100%;
        height: auto;
    }
</style>
</body>