<?php
    $objrecordfun = new Efy_Function_RecordFunctions();
    $arrinfoRecordType = $this->arrinfoRecordType;
    $sApproveLevel = $this->sApproveLevel;
    //Can bo thu ly
    $sHandleList = $arrinfoRecordType['C_HANDLER_ID_LIST'];
    $arrHandleList = explode(',',$sHandleList);
    $icountHand = sizeof($arrHandleList);
    $checkHand = '';
    if($icountHand===1){
        $checkHand = 'checked="checked"';
    }
    //lanh dao
    $sLeaderList = $arrinfoRecordType['C_APPROVE_LEADER_ID_LIST'];
    $sRoleList = $arrinfoRecordType['C_ROLES_CODE_LIST'];
    $arrLeader = explode(',',$sLeaderList);
    $arrRole = explode(',',$sRoleList);
    $arrLeaderLv2 = array();
    $arrLeaderLv3 = array();
    foreach($arrLeader as $key => $sLeaderid) {
        if($arrRole[$key]=='DUYET_CAP_HAI'){
            array_push($arrLeaderLv2,$sLeaderid);
        }
        if($arrRole[$key]=='DUYET_CAP_BA'){
            array_push($arrLeaderLv3,$sLeaderid);
        }
    }

    $icountLeaderLv2 = sizeof($arrLeaderLv2);
    $checkLeaderLv2 = '';
    if($icountLeaderLv2===1){
        $checkLeaderLv2 = 'checked="checked"';
    }

    $icountLeaderLv3 = sizeof($arrLeaderLv3);
    $checkLeaderLv3 = '';
    if($icountLeaderLv3===1){
        $checkLeaderLv3 = 'checked="checked"';
    }
?>
<form action="" method="POST" id="frmSubmitorder" autocomplete="off" enctype="multipart/form-data">
    <?php echo $this->formHidden("hdn_record_id_list",$this->sRecordIdList,null); ?>
    <!--Bien hdn_deleted_new_file_id_list dung de luu Id cua nhung doi tuong file dinh kem se xoa-->
    <?php echo $this->formHidden("hdn_deleted_new_file_id_list","",null); ?>
    <!--Bien hdn_deleted_exist_file_id_list dung de ...-->
    <?php echo $this->formHidden("hdn_deleted_exist_file_id_list","",null); ?>
    <?php echo $this->formHidden("hdn_update","1",null); ?>

    <div style="width: 99%;padding-left: 5px;">
        <div class="normal_title">DANH SÁCH HỒ SƠ DUYỆT</div>
        <div class="general_information" id="general_information">
            <?=$this->general_information?>
        </div>
        <div class="normal_title">NỘI DUNG DUYỆT</div>
        <div id="contentXml" style="margin: 0;">
            <div id="header_update_form">
                <div style="padding-top: 15px;">
                    <label>Hình thức xử lý<span class="requiein">*</span></label>
                    <div style="display: inline-block;width: 75%;">
                        <? if(($sApproveLevel!='DUYET_CAP_BA')&&($icountLeaderLv3 > 0)){?>
                        <div style="display: inline-block;width: 100%;">
                            <input style="float: left;" type="radio" class="normal_radiobutton" value="TRINH_LD_DONVI" name="chk_process_type" id="chk_process_type0">
                            <label style="float: left;padding-left: 5px;width: 90%;" for="chk_process_type0" class="normal_label">Trình lãnh đạo đơn vị</label>
                        </div>
                        <div id="div_LeaderLv3" style="display: inline-block;width: 94%;margin: 5px;">
                            <fieldset class="normal_label" style="border: 1px solid #dddddd;">
                                <legend style="border: 1px solid #DDDDDD;padding: 3px;box-shadow: 1px 2px 3px #888888;">Chọn lãnh đạo</legend>
                                <?
                                foreach($arrLeaderLv3 as $key => $sHandleid) {
                                    $sHandlename = $objrecordfun->getNamePositionStaffByIdList($sHandleid);
                                    ?>
                                    <div style="display: inline-block;width: 100%; margin-left: 20px; margin-top: 3px;">
                                        <input style="float: left;" type="radio" class="normal_radiobutton" value="<?=$sHandleid;?>" <?=$checkLeaderLv3;?> name="chk_LeaderLv3" id="chk_LeaderLv3<?=$key;?>">
                                        <label style="float: left;padding-left: 5px;" for="chk_LeaderLv3<?=$key;?>" class="normal_label"><?=$sHandlename;?> </label>
                                    </div>
                                <?
                                }
                                ?>
                            </fieldset>
                        </div>
                        <? } ?>

                        <? if(($sApproveLevel=='DUYET_CAP_MOT')&&($icountLeaderLv2 > 0)){?>
                        <div style="display: inline-block;width: 100%;">
                            <input style="float: left;" type="radio" class="normal_radiobutton" value="TRINH_LD_PHONG" name="chk_process_type" id="chk_process_type1">
                            <label style="float: left;padding-left: 5px;width: 90%;" for="chk_process_type1" class="normal_label">Trình lãnh đạo phòng</label>
                        </div>
                        <div id="div_LeaderLv2" style="display: inline-block;width: 94%;margin: 5px;">
                            <fieldset class="normal_label" style="border: 1px solid #dddddd;">
                                <legend style="border: 1px solid #DDDDDD;padding: 3px;box-shadow: 1px 2px 3px #888888;">Chọn lãnh đạo</legend>
                                <?
                                foreach($arrLeaderLv2 as $key => $sHandleid) {
                                    $sHandlename = $objrecordfun->getNamePositionStaffByIdList($sHandleid);
                                    ?>
                                    <div style="display: inline-block;width: 100%; margin-left: 20px; margin-top: 3px;">
                                        <input style="float: left;" type="radio" class="normal_radiobutton" value="<?=$sHandleid;?>" <?=$checkLeaderLv2;?> name="chk_LeaderLv2" id="chk_LeaderLv2<?=$key;?>">
                                        <label style="float: left;padding-left: 5px;" for="chk_LeaderLv2<?=$key;?>" class="normal_label"><?=$sHandlename;?> </label>
                                    </div>
                                <?
                                }
                                ?>
                            </fieldset>
                        </div>
                        <? } ?>

                        <? if($sApproveLevel=='DUYET_CAP_BA'){?>
                        <div style="display: inline-block;width: 100%;">
                            <input style="float: left;" type="radio" class="normal_radiobutton" value="LD_DONVI_CAPPHEP" name="chk_process_type" id="chk_process_type21">
                            <label style="float: left;padding-left: 5px;width: 90%;" for="chk_process_type21" class="normal_label">Duyệt, chuyển một cửa trả kết quả</label>
                        </div>
                        <? }else{?>
                        <div style="display: inline-block;width: 100%;">
                            <input style="float: left;" type="radio" class="normal_radiobutton" value="LD_PHONG_CAPPHEP" name="chk_process_type" id="chk_process_type22">
                            <label style="float: left;padding-left: 5px;width: 90%;" for="chk_process_type22" class="normal_label">Duyệt, chuyển một cửa trả kết quả</label>
                        </div>
                        <? } ?>

                        <div style="display: inline-block;width: 100%;">
                            <input style="float: left;" type="radio" class="normal_radiobutton" value="DUYET_CHUYEN_PHONG_BAN" checked="checked" name="chk_process_type" id="chk_process_type3">
                            <label style="float: left;padding-left: 5px;width: 90%;" for="chk_process_type3" class="normal_label">Duyệt, chuyển cán bộ phụ trách</label>
                        </div>

                        <? if($sApproveLevel!='DUYET_CAP_BA'){?>
                        <div style="display: inline-block;width: 100%;">
                            <input style="float: left;" type="radio" class="normal_radiobutton" value="LD_PHONG_TRALAI" name="chk_process_type" id="chk_process_type4">
                            <label style="float: left;padding-left: 5px;width: 90%;" for="chk_process_type4" class="normal_label">Trả lại tiếp tục thụ lý</label>
                        </div>

                        <div style="display: inline-block;width: 100%;">
                            <input style="float: left;" type="radio" class="normal_radiobutton" value="LD_PHONG_TRALAI_VPDK" name="chk_process_type" id="chk_process_type8">
                            <label style="float: left;padding-left: 5px;width: 90%;" for="chk_process_type8" class="normal_label">Trả lại lãnh đạo VPĐK QSDĐ</label>
                        </div>

                        <div style="display: inline-block;width: 100%;">
                            <input style="float: left;" type="radio" class="normal_radiobutton" value="CHUYEN_CAN_BO_XL" name="chk_process_type" id="chk_process_type5">
                            <label style="float: left;padding-left: 5px;width: 90%;" for="chk_process_type5" class="normal_label">Chuyển cán bộ thụ lý</label>
                        </div>
                        <div id="div_handle" style="display: inline-block;width: 94%;margin: 5px;">
                            <fieldset class="normal_label" style="border: 1px solid #dddddd;">
                                <legend style="border: 1px solid #DDDDDD;padding: 3px;box-shadow: 1px 2px 3px #888888;">Chọn cán bộ</legend>

                                <?
                                foreach($arrHandleList as $key => $sHandleid) {
                                    $sHandlename = $objrecordfun->getNamePositionStaffByIdList($sHandleid);
                                    ?>
                                    <div style="display: inline-block;width: 100%; margin-left: 20px; margin-top: 3px;">
                                        <input style="float: left;" type="radio" class="normal_radiobutton" value="<?=$sHandleid;?>" <?=$checkHand?> name="chk_handle" id="chk_handle<?=$key;?>">
                                        <label style="float: left;padding-left: 5px;" for="chk_handle<?=$key;?>" class="normal_label"><?=$sHandlename;?> </label>
                                    </div>
                                <?
                                }
                                ?>
                            </fieldset>
                        </div>

                        <div style="display: inline-block;width: 100%;">
                            <input style="float: left;" type="radio" class="normal_radiobutton" value="LD_PHONG_TUCHOI" name="chk_process_type" id="chk_process_type6">
                            <label style="float: left;padding-left: 5px;width: 90%;" for="chk_process_type6" class="normal_label">Từ chối, không cấp phép</label>
                        </div>
                        <? } ?>

                        <? if($sApproveLevel=='DUYET_CAP_BA'){?>
                        <div style="display: inline-block;width: 100%;">
                            <input style="float: left;" type="radio" class="normal_radiobutton" value="LD_DONVI_TUCHOI" name="chk_process_type" id="chk_process_type7">
                            <label style="float: left;padding-left: 5px;width: 90%;" for="chk_process_type7" class="normal_label">Từ chối, không cấp phép</label>
                        </div>
                        <? } ?>
                    </div>
                </div>
                <div style="padding-top: 15px;">
                    <label>Ý kiến<span class="requiein">*</span></label>
                    <textarea style="width:70%;font-family: arial;font-size: 10pt;" name="idea" id="idea" class="normal_textarea">Duyệt, chuyển cán bộ phụ trách thụ lý hồ sơ!</textarea>
                </div>
                <div style="padding-top: 15px;">
                    <label>File đính kèm</label>
                    <div style="display: inline-block;width: 75%;"><?php echo $this->AttachFile;?></div>
                </div>
                <div id="clear"></div>
            </div>
        </div>
    </div>
    <div style="width: 99%;padding-top: 12px;text-align: center;">
        <input type="button" style="margin-left:0px;" name="btnSubmit" id="btnSubmit" value="Cập nhật" class="add_large_button">
        <input type="button" style="margin-left:0px;" name="btnback" id="btnback" value="Quay lại" class="add_large_button">
    </div>
</form>
<script type="text/javascript">
    var baseUrl = "<?=$this->baseUrl();?>";
    var obj_record_approve = new record_approve(baseUrl, 'record', 'approve');
    jQuery(document).ready(function ($) {
        obj_record_approve.loadApproveEven();
    });
</script>