<?php
$arrResult = $this->arrResult;
?>
<table class="list-table-data" cellpadding="0" cellspacing="0" border="0" align="center" id="table-data">
    <col width="3%">
    <col width="15%">
    <col width="20%">
    <col width="10%">
    <col width="5%">
    <col width="10">
    <col width="10%">
    <col width="10%">
    <col width="17%">
    <tr class="header">
        <td class="" align="center">STT</td>
        <td class="" align="center">Phòng ban</td>
        <td class="" align="center">Công việc</td>
        <td class="" align="center">Ngày bắt đầu</td>
        <td class="" align="center">Số ngày</td>
        <td class="" align="center">Hạn giải quyết</td>
        <td class="" align="center">Ngày hoàn thành</td>
        <td class="" align="center">T/g đã thực hiện</td>
        <td class="" align="center">Cán bộ xử lý</td>
    </tr>
    <?php echo $this->sHtmlTr; ?>
</table>