<table width="100%" cellpadding="0" cellspacing="0" align="center" height="35px" class="footeronnet_info_table" id="tbl_footer">
	<tr id="tr_footer" height="30px" valign="bottom">
		 <td  style="color:#993300;" >&nbsp;<b><?php echo "C&#244;ng ty C&#7893; ph&#7847;n C&#244;ng ngh&#7879; Tin h&#7885;c EFY Vi&#7879;t Nam"?></b></td>	
	</tr>
	<tr id="tr_footer" height="30px">
		 <td align="left" valign="top">&nbsp;<?php echo "Tel: 0485 875 921 - Fax: (84-4)2872290"?>&nbsp;-&nbsp;Email:<a href="mailto:contact@efy.com.vn"><?php echo "contact@efy.com.vn"?></a>&nbsp;&nbsp;&nbsp;Website: <a href="http://www.efy.com.vn" target="_blank"><?php echo "http://www.efy.com.vn"?></a></td>
	</tr>			
</table>	
