<table width="100%" cellpadding="0" cellspacing="0" align="center" class="footer_info_table" id="tbl_footer">
    <tr id="tr_footer">
        <td class="detail">
            <div style="float:left; background-repeat: no-repeat;  background-position: left center;    margin-left: 30px;
             padding-left: 40px;padding-top: 10px;height: 38px;">
                <b><?="Công ty Cổ phần Công nghệ Hanco"?></b>
                <br>Email: <a href="chienbn@gmail.com"><?php echo "chienbn@gmail.com"?></a>&nbsp;&nbsp;&nbsp;
                Website: <a href="http://www.hancotech.com.vn" target="_blank"><?php echo "http://www.hancotech.com.vn"?></a>
                <br>
            </div>

        </td>
    </tr>
</table>
<script type="text/javascript" >
    $(document).ready(function(){
        if ($.browser.msie){
            var browserHeight = document.documentElement.offsetHeight;//lấy chiều cao khung trình duyệt trên IE
        }else{
            var browserHeight = window.innerHeight; //lấy chiều cao khung trình duyệt trên các trình duyệt khác
        }
        var headerHeight = $('.bannerhead').height();//lấy chiều cao header
        var footerHeight = $('.footer_info_table').height();//lấy chiều cao footer
        var menuHeight = $('.top_menu_table').height();//lấy chiều cao menu
        var contentHeight = $('.anmenu').height();//lấy chiều cao content
        var minContentHeight = browserHeight - headerHeight -footerHeight- menuHeight;//tính chiều cao cho phần nội dung
        $('.anmenu').css({"height": minContentHeight - 5});//gán min-height bằng chiều cao tính được (cho FF, Chrome,...)
        if ($.browser.msie){
            if(contentHeight <  minContentHeight){
                $('.anmenu').css({"height": minContentHeight - 5});
            }else{
                $('.anmenu').css({"height": contentHeight});
            }
        }//gán height bằng chiều cao tính được (cho IE)
    });
</script>