<?php
function _generate_day_of_week($p_lang, $status = ''){
    $RetStr = date("l, d/m/y");
    $pday = date("l");
    if($p_lang == 1){
        switch($pday){
            case "Sunday";
                $RetStr = "Ch&#7911; nh&#7853;t";
                break;
            case "Monday";
                $RetStr = "Th&#7913; hai";
                break;
            case "Tuesday";
                $RetStr = "Th&#7913; ba";
                break;
            case "Wednesday";
                $RetStr = "Th&#7913; t&#432;";
                break;
            case "Thursday";
                $RetStr = "Th&#7913; n&#259;m";
                break;
            case "Friday";
                $RetStr = "Th&#7913; s&#225;u";
                break;
            case "Saturday";
                $RetStr = "Th&#7913; b&#7843;y";
        }
        if($status == 'on'){
            $RetStr = $RetStr.", ngày ".date("d/m/y");
        }else{
            $RetStr = $RetStr.", ".date("d/m/y");
        }
    }
    return $RetStr;
}
//Ham Const
$objconfig = new Extra_Init();
$arrConst	=	$objconfig->_setProjectPublicConst();
$sOwnerCode	= $_SESSION['OWNER_CODE'];
$sOwnerCodeRoot = $objconfig->_getOwnerCode();
$objfunction = new Extra_Ecs();
?>
<!--He thong Menu ngang-->
<table width="100%" cellpadding="0" cellspacing="0" class="top_menu_table">
    <tr>
        <td class="thungay">
            <div><?=_generate_day_of_week(1);?></div>
        </td>
        <td>
            <ul>
                <!--Nhac viec-->
                <?php $urlRe = $this->baseUrl . "../record/reminder/index"; ?>
                <li  id="header_reminder" style="cursor:pointer;" onclick="href('<?= $urlRe?>');"><?=$arrConst['_NHAC_VIEC']?></li>
                <?php
                if($objfunction->eCSPermisstionReceiverForRecordType($_SESSION['staff_id'],$_SESSION['arr_all_record_type'])&&($sOwnerCode==$sOwnerCodeRoot)){
                    $urlRe = $this->baseUrl . "../record/receiveonnet/index/";?>
                    <li id ="header_receiveonnet" align="left" style="cursor:pointer;" onclick="href('<?=$urlRe;?>')"><?=$arrConst['_HS_QUA_MANG']?></li>
                <?php }?>
                <?php
                if($objfunction->eCSPermisstionReceiverForRecordType($_SESSION['staff_id'],$_SESSION['arr_all_record_type'])){
                    $urlRe = $this->baseUrl . "../record/orderonnet/index";?>
                    <li id ="header_orderonnet" align="left" style="cursor:pointer;" onclick="href('<?=$urlRe;?>')">Đăng ký giao dịch</li>
                <?php }?>
                <!--TN&TKQ--><?php
                if($objfunction->eCSPermisstionReceiverForRecordType($_SESSION['staff_id'],$_SESSION['arr_all_record_type'])){
                    if($sOwnerCode==$sOwnerCodeRoot){
                        $urlRe = $this->baseUrl . "../record/receive/index";
                    }else{
                        $urlRe = $this->baseUrl . "../record/wreceive/index";
                    }
                    ?>
                    <li id ="header_receive" align="left" style="cursor:pointer;" onclick="href('<?=$urlRe;?>')"><?=$arrConst['_TN_TKQ']?></li><?php
                }?>

                <!--Thụ lý--><?php
                if($objfunction->eCSPermisstionHandlerForRecordType($_SESSION['staff_id'],$_SESSION['arr_all_record_type'])&&($sOwnerCode==$sOwnerCodeRoot)){
                    $urlRe = $this->baseUrl . "../record/handle/index"; ?>
                    <li id="header_handle" align="left" style="cursor:pointer;" onclick="href('<?=$urlRe;?>')"><?=$arrConst['_THU_LY']?></li><?php
                }?>

                <!--Phê duyệt--><?php
                if($objfunction->eCSPermisstionApproveForRecordType($_SESSION['staff_id'],'',$_SESSION['arr_all_record_type'])){
                    if($sOwnerCode==$sOwnerCodeRoot){
                        $urlRe = $this->baseUrl . "../record/approve/index";
                    }else{
                        $urlRe = $this->baseUrl . "../record/wapprove/index";
                    }?>
                    <li id="header_approve" align="left" style="cursor:pointer;" onclick="href('<?=$urlRe;?>')"><?=$arrConst['_PHE_DUYET']?></li><?php
                }?>

                <!--Tra cứu-->
                <?php $urlRe = $this->baseUrl . "../record/search/general/"; ?>
                <li id="header_search" align="left" style="cursor:pointer;" onclick="href('<?=$urlRe;?>')"><?=$arrConst['_TRA_CUU']?></li>

                <!--Báo cáo-->
                <?php $urlRe = $this->baseUrl . "../record/normalreport/index/"; ?>
                <li id="header_report" align="left" style="cursor:pointer;" onclick="href('<?=$urlRe;?>')"><?=$arrConst['_BAO_CAO']?></li>

                <!--He thong danh muc-->
                <?php
                if($_SESSION['STAFF_PERMISSTION']==Extra_Init::_setPermisstionSystem(1)){
                    $urlRe = $this->baseUrl . "../listxml/recordtype/index/"; ?>
                    <li  id ="header_list" align="left" style="cursor:pointer;" onclick="href('<?=$urlRe;?>')"><?=$arrConst['_DANH_MUC']?></li>	<?php
                }?>

                <!--TRANG CHU-->
                <?PHP $urlRe = 'http://'.$_SERVER['HTTP_HOST'].'/qlvbdh/web/home/index/?sliid=li1&sleftmenu=mn_0_0_0';?>
                <li  id ="header_home" align="left" style="cursor:pointer;" onclick="href('<?=$urlRe;?>')">Thông tin điều hành</a></li>
				
				<!--HUONG DAN-->
                <?PHP $urlRe = 'http://'.$_SERVER['HTTP_HOST'].'/mcdt/hdsd.doc';?>
                <li  id ="header_home" align="left" style="cursor:pointer;" onclick="href('<?=$urlRe;?>')">HDSD</a></li>

                <!--TAI FILE CONVERT WORD 2003 -> 2007-->
                <?PHP $urlRe = 'http://'.$_SERVER['HTTP_HOST'].'/mcdt/ConverdWord2003.rar';?>
                <li  id ="header_home" align="left" style="cursor:pointer;" onclick="href('<?=$urlRe;?>')">Đọc file docx</a></li>

                <!--THOAT-->
                <?php $urlRe = $this->baseUrl . "../logout/index";?>
                <li  id ="header_logout" align="left" style="cursor:pointer;" onclick="href('<?=$urlRe;?>')"><?=$arrConst['_THOAT']?></li>
            </ul>
        </td>
    </tr>
</table>
<script type="text/javascript">
    /* Các hàm định nghĩa cho menu con*/
    function otab(child_id){
        document.write('<table class = "pushdown_menu_table"' + 'id="' + child_id +'" border="0" cellspacing="0" cellpadding="0">');
    }
    function submn(submn_label,submn_text){
        document.write('<tr><td  onclick="window.location.href=\'<?=$this->baseUrl;?>'+submn_label+'/\'" onmouseover="this.className=\'hoverClass\'" onmouseout="this.className=\'outverClass\'" ><img src="<?= $this->baseUrl?>images/anh_menu_level_2.gif"/>'+'  '+submn_text+'</td></tr>');
    }//
    function ctab(){
        document.write('</table>');
    }<?php
    $sCurrentModulCode = $this->currentModulCode;
    //Nhac viec
    if ($sCurrentModulCode == "REMINDER"){ ?>
    document.getElementById('header_reminder').className="visited";<?php
    }
    if ($sCurrentModulCode == "RECORD"){ ?>
    document.getElementById('header_receive').className="visited";<?php
    }
    //ho so qua mang
    if ($sCurrentModulCode == "RECEIVE-ON-NET"){ ?>
    document.getElementById('header_receiveonnet').className="visited";<?php
    }
    if ($sCurrentModulCode == "ORDER-ON-NET"){ ?>
    document.getElementById('header_orderonnet').className="visited";<?php
    }
    //Danh muc
    if ($sCurrentModulCode == "LIST"){ ?>
    document.getElementById('header_list').className="visited";<?php
    }
    //Phe duyet
    if ($sCurrentModulCode == "ASSIGN"){ ?>
    document.getElementById('header_approve').className="visited";<?php
    }
    //Thu ly
    if ($sCurrentModulCode == "HANDLE"){ ?>
    document.getElementById('header_handle').className="visited";<?php
    }
    //Bao cao
    if ($sCurrentModulCode == "REPORTS"){ ?>
    document.getElementById('header_report').className="visited";<?php
    }
    //Tra cuu
    if ($sCurrentModulCode == "SEARCH"){ ?>
    document.getElementById('header_search').className="visited";<?php
    }
    ?>
    function href(url){
        window.location.href = url;
    }
</script>
