<?php
//Ham Const
$objconfig = new Extra_Init();
$arrConst = $objconfig->_setProjectPublicConst();
$sOwnerCode = $_SESSION['OWNER_CODE'];
$sOwnerCodeRoot = $objconfig->_getOwnerCode();
?>
<div id="Iddiv_leftmenu">
    <!--Menu trai cua Ho so qua mang-->
    <div id="left_receiveonnet" style="display:none;">
        <table width="100%" cellpadding="0" cellspacing="0" border="0" class="body3">
            <tr>
                <td valign="top">
                    <table width="98%" cellpadding="0" cellspacing="0" align="center" class="left_menu_table">
                        <!--Cau lenh If...Else phan quyen-->
                        <tr>
                            <td id="left_receiveonnet_preliminary" class="level1">
                                <a href="<?php echo $this->baseUrl; ?>../record/receiveonnet/index/">HS tiếp nhận sơ
                                    bộ</a>
                            </td>
                        </tr>
                        <tr>
                            <td id="left_receiveonnet_supplementrecordlist" class="level1">
                                <a href="<?php echo $this->baseUrl; ?>../record/receiveonnet/supplementrecordlist/">HS
                                    chờ bổ sung</a>
                            </td>
                        </tr>
                        <tr>
                            <td id="left_receiveonnet_officialrecordlist" class="level1">
                                <a href="<?php echo $this->baseUrl; ?>../record/receiveonnet/officialrecordlist/">HS
                                    tiếp nhận chính thức</a>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </div>

    <div id="left_order" style="display:none;">
        <table width="100%" cellpadding="0" cellspacing="0" border="0" class="body3">
            <tr>
                <td valign="top">
                    <table width="98%" cellpadding="0" cellspacing="0" align="center" class="left_menu_table">
                        <!--Cau lenh If...Else phan quyen-->
                        <tr>
                            <td id="left_order_chuaduyet" class="level1">
                                <a href="<?php echo $this->baseUrl; ?>../record/orderonnet/index">Đăng ký chờ duyệt</a>
                            </td>
                        </tr>
                        <tr>
                            <td id="left_order_daduyet" class="level1">
                                <a href="<?php echo $this->baseUrl; ?>../record/orderonnet/approved">Đăng ký đã duyệt</a>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </div>
    <!--Menu trai cua TN&TKQ-->
    <? if ($sOwnerCode == $sOwnerCodeRoot) { ?>
        <div id="left_receive" style="display:none;">
            <table width="100%" cellpadding="0" cellspacing="0" border="0" class="body3">
                <tr>
                    <td valign="top">
                        <table width="98%" cellpadding="0" cellspacing="0" align="center" class="left_menu_table">
                            <!--Cau lenh If...Else phan quyen-->
                            <tr>
                                <td id="left_receive_receive" class="level1">
                                    <a href="<?php echo $this->baseUrl; ?>../record/receive/index">HS &#273;&#227; ti&#7871;p
                                        nh&#7853;n</a>
                                </td>
                            </tr>
                            <tr>
                                <td id="left_receive_transition" class="level1">
                                    <a href="<?php echo $this->baseUrl; ?>../record/receive/transition">HS li&#234;n th&#244;ng
                                        ch&#7901; nh&#7853;n</a>
                                </td>
                            </tr>
                            <tr>
                                <td id="left_receive_additional" class="level1">
                                    <a href="<?php echo $this->baseUrl; ?>../record/receive/additional">HS ch&#7901; b&#7893;
                                        sung</a>
                                </td>
                            </tr>
                            <tr>
                                <td id="left_receive_processing" class="level1">
                                    <a href="<?php echo $this->baseUrl; ?>../record/receive/processing">HS &#273;ang gi&#7843;i
                                        quy&#7871;t</a>
                                </td>
                            </tr>
                            <tr>
                                <td id="left_receive_result" class="level1">
                                    <a href="<?php echo $this->baseUrl; ?>../record/receive/result">HS ch&#7901; TKQ</a>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </div>
    <? } else { ?>
        <div id="left_receive" style="display:none;">
            <table width="100%" cellpadding="0" cellspacing="0" border="0" class="body3">
                <tr>
                    <td valign="top">
                        <table width="98%" cellpadding="0" cellspacing="0" align="center" class="left_menu_table">
                            <tr>
                                <td id="left_receive_receive" class="level1">
                                    <a href="<?php echo $this->baseUrl; ?>../record/wreceive/index">HS &#273;&#227; ti&#7871;p
                                        nh&#7853;n</a>
                                </td>
                            </tr>
                            <tr>
                                <td id="left_receive_additional" class="level1">
                                    <a href="<?php echo $this->baseUrl; ?>../record/wreceive/additional">HS ch&#7901; b&#7893;
                                        sung</a>
                                </td>
                            </tr>
                            <tr>
                                <td id="left_receive_processing" class="level1">
                                    <a href="<?php echo $this->baseUrl; ?>../record/wreceive/processing">HS trình lãnh
                                        đạo</a>
                                </td>
                            </tr>
                            <tr>
                                <td id="left_receive_transition" class="level1">
                                    <a href="<?php echo $this->baseUrl; ?>../record/wreceive/transition">HS liên thông
                                        huyện</a>
                                </td>
                            </tr>
                            <tr>
                                <td id="left_receive_result" class="level1">
                                    <a href="<?php echo $this->baseUrl; ?>../record/wreceive/result">HS ch&#7901;
                                        TKQ</a>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </div>
    <? } ?>
    <!--Menu trai cua Thụ lý -->
    <div id="left_handle" style="display:none;">
        <table width="100%" cellpadding="0" cellspacing="0" border="0" class="body3">
            <tr>
                <td valign="top">
                    <table width="98%" cellpadding="0" cellspacing="0" align="center" class="left_menu_table">
                        <!--Cau lenh If...Else phan quyen-->
                        <tr>
                            <td id="left_handle_main" class="level1">
                                <a href="<?php echo $this->baseUrl; ?>../record/handle/index">HS c&#7847;n gi&#7843;i
                                    quy&#7871;t</a>
                            </td>
                        </tr>
                        <tr>
                            <td id="left_handle_additional" class="level1">
                                <a href="<?php echo $this->baseUrl; ?>../record/handle/list">HS ch&#7901; b&#7893;
                                    sung</a>
                            </td>
                        </tr>
                        <tr>
                            <td id="left_handle_transition" class="level1">
                                <a href="<?php echo $this->baseUrl; ?>../record/handle/transition">HS liên thông</a>
                            </td>
                        </tr>
                        <tr>
                            <td id="left_handle_approved" class="level1">
                                <a href="<?php echo $this->baseUrl; ?>../record/handle/approved">HS &#273;&#227; tr&#236;nh
                                    k&#253;</a>
                            </td>
                        </tr>
                        <tr>
                            <td id="left_handle_result" class="level1">
                                <a href="<?php echo $this->baseUrl; ?>../record/handle/result">HS &#273;&#227; c&#243; k&#7871;t
                                    qu&#7843;</a>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </div>
    <!--Menu trai cua Phê duyệt -->
    <? if ($sOwnerCode == $sOwnerCodeRoot) { ?>
        <div id="left_approve" style="display:none;">
            <table width="100%" cellpadding="0" cellspacing="0" border="0" class="body3">
                <tr>
                    <td valign="top">
                        <table width="98%" cellpadding="0" cellspacing="0" align="center" class="left_menu_table">
                            <!--Cau lenh If...Else phan quyen-->
                            <?
                            if (Extra_Ecs::eCSPermisstionApproveForRecordType($_SESSION['staff_id'], 'DUYET_CAP_BA', $_SESSION['arr_all_record_type']) != 'DUYET_CAP_BA') {
                                ?>
                                <tr>
                                    <td id="left_approve_assignWait" class="level1">
                                        <a href="<?php echo $this->baseUrl; ?>../record/assign/index">HS ch&#7901; ph&#226;n
                                            c&#244;ng</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td id="left_approve_assign" class="level1">
                                        <a href="<?php echo $this->baseUrl; ?>../record/assign/assigned">HS &#273;&#227;
                                            ph&#226;n c&#244;ng</a>
                                    </td>
                                </tr>
                            <? } ?>
                            <tr>
                                <td id="left_approve_approveWait" class="level1">
                                    <a href="<?php echo $this->baseUrl; ?>../record/approve/index">HS ch&#7901; duy&#7879;t</a>
                                </td>
                            </tr>
                            <tr>
                                <td id="left_approve_approved" class="level1">
                                    <a href="<?php echo $this->baseUrl; ?>../record/approve/approved">HS đã duyệt</a>
                                </td>
                            </tr>
                            <tr>
                                <td id="left_approve_transition" class="level1">
                                    <a href="<?php echo $this->baseUrl; ?>../record/approve/transition">HS liên thông</a>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </div>
    <? } else { ?>
        <div id="left_approve" style="display:none;">
            <table width="100%" cellpadding="0" cellspacing="0" border="0" class="body3">
                <tr>
                    <td valign="top">
                        <table width="98%" cellpadding="0" cellspacing="0" align="center" class="left_menu_table">
                            <tr>
                                <td id="left_approve_approveWait" class="level1">
                                    <a href="<?php echo $this->baseUrl; ?>../record/wapprove/index">HS chờ duyệt</a>
                                </td>
                            </tr>
                            <tr>
                                <td id="left_approve_approved" class="level1">
                                    <a href="<?php echo $this->baseUrl; ?>../record/wapprove/approved">HS đã duyệt</a>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </div>
    <? } ?>
    <!--Menu trai cua Tra cứu -->
    <div id="left_search" style="display:none;">
        <table width="100%" cellpadding="0" cellspacing="0" border="0" class="body3">
            <tr>
                <td valign="top">
                    <table width="98%" cellpadding="0" cellspacing="0" align="center" class="left_menu_table">
                        <!--Cau lenh If...Else phan quyen-->
                        <tr>
                            <td id="left_search_general" class="level1">
                                <a href="<?php echo $this->baseUrl; ?>../record/search/general">S&#7889; li&#7879;u t&#7893;ng
                                    h&#7907;p</a>
                            </td>
                        </tr>
                        <tr>
                            <td id="left_search_record" class="level1">
                                <a href="<?php echo $this->baseUrl; ?>../record/search/index">T&#236;m ki&#7871;m h&#7891;
                                    s&#417;</a>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </div>
    <!--Menu trai cua bao cao -->
    <div id="left_report" style="display:none;">
        <table width="100%" cellpadding="0" cellspacing="0" border="0" class="body3">
            <tr>
                <td valign="top">
                    <table width="98%" cellpadding="0" cellspacing="0" align="center" class="left_menu_table">
                        <? if ($_SESSION['STAFF_PERMISSTION'] == Extra_Init::_setPermisstionSystem(1)) { ?>
                            <tr>
                                <td id="left_report_general" class="level1">
                                    <a href="<?php echo $this->baseUrl; ?>../record/normalreport/general/">Báo cáo
                                        chung</a>
                                </td>
                            </tr>
                        <? } ?>
                        <tr>
                            <td id="left_report_recordtype" class="level1">
                                <a href="<?php echo $this->baseUrl; ?>../record/normalreport/index/">Báo cáo theo từng
                                    TTHC</a>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </div>
    <!--Menu trai cua menu danh muc-->
    <div id="left_list" style="display:none">
        <table width="100%" cellpadding="0" cellspacing="0" class="body3">
            <tr>
                <td valign="top">
                    <table width="98%" cellpadding="0" cellspacing="0" align="center" class="left_menu_table">
                        <tr>
                            <td id="left_list_recordtype" class="level1">
                                <a href="<?php echo $this->baseUrl; ?>../listxml/recordtype/index/"><?= $arrConst['_DM_TTHC'] ?></a>
                            </td>
                        </tr>
                        <tr>
                            <td id="left_list_listtype" class="level1">
                                <a href="<?php echo $this->baseUrl; ?>../listxml/listtype/index/"><?= $arrConst['_DM_LOAI'] ?></a>
                            </td>
                        </tr>
                        <tr>
                            <td id="left_list_list" class="level1">
                                <a href="<?php echo $this->baseUrl; ?>../listxml/list/index/"><?= $arrConst['_DM_DOITUONG'] ?></a>
                            </td>
                        </tr>
                        <tr>
                            <td id="left_list_report" class="level1">
                                <a href="<?php echo $this->baseUrl; ?>../listxml/report/index/"><?= $arrConst['_DM_BAOCAO'] ?></a>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </div>
    <!-- thong tin nguoi dang nhap -->
    <div><?php echo $_SESSION['INFORMATION_STAFF_LOGIN']; ?></div>
</div>
<!--Xu ly JS!-->
<script type="text/javascript">
    function showHideMenu(p_id) {
        var objfrm = document.getElementsByTagName('div');
        for (i = 0; i < objfrm.length; i++) {
            e = objfrm[i].getAttribute('id');
            if (objfrm[i].getAttribute('value') == "true") {
                if (e == p_id) {
                    var pStyle = eval("document.getElementById('" + p_id + "').style.display");
                    if (pStyle == "none") {
                        eval("document.getElementById('" + p_id + "').style.display = '" + "block'");
                    } else {
                        eval("document.getElementById('" + p_id + "').style.display = '" + "none'");
                    }
                }
            }
        }
    }

    var sCurrentModulCode = '<?php echo $this->currentModulCode; ?>';
    var scurrentModulCodeForLeft = '<?php echo $this->currentModulCodeForLeft; ?>';
    if(sCurrentModulCode=='REPORTS'){
        $('#left_report').show();
        if(scurrentModulCodeForLeft=='NORMAL_REPORTS'){
            $('#left_report_recordtype').addClass('level1_visited');
        }
        if(scurrentModulCodeForLeft=='REPORTS'){
            $('#left_report_general').addClass('level1_visited');
        }
    }

    if(sCurrentModulCode=='LIST'){
        $('#left_list').show();
        if(scurrentModulCodeForLeft=='RECORDTYPE'){
            $('#left_list_recordtype').addClass('level1_visited');
        }
        if(scurrentModulCodeForLeft=='LISTTYPE'){
            $('#left_list_listtype').addClass('level1_visited');
        }
        if(scurrentModulCodeForLeft=='LIST'){
            $('#left_list_list').addClass('level1_visited');
        }
        if(scurrentModulCodeForLeft=='PERMISSION'){
            $('#left_list_permission').addClass('level1_visited');
        }
        if(scurrentModulCodeForLeft=='BACKUP'){
            $('#left_list_backup').addClass('level1_visited');
        }
        if(scurrentModulCodeForLeft=='RESTORE'){
            $('#left_list_restore').addClass('level1_visited');
        }
    }

    if(sCurrentModulCode=='RECEIVE-ON-NET'){
        $('#left_receiveonnet').show();
        if(scurrentModulCodeForLeft=='PRELIMINARY'){
            $('#left_receiveonnet_preliminary').addClass('level1_visited');
        }
        if(scurrentModulCodeForLeft=='SUPPLEMENT'){
            $('#left_receiveonnet_supplementrecordlist').addClass('level1_visited');
        }
        if(scurrentModulCodeForLeft=='OFFICIAL'){
            $('#left_receiveonnet_officialrecordlist').addClass('level1_visited');
        }
    }

    if(sCurrentModulCode=='ORDER-ON-NET'){
        $('#left_order').show();
        if(scurrentModulCodeForLeft=='CHUADUYET'){
            $('#left_order_chuaduyet').addClass('level1_visited');
        }
        if(scurrentModulCodeForLeft=='DADUYET'){
            $('#left_order_daduyet').addClass('level1_visited');
        }
    }

    if(sCurrentModulCode=='RECORD'){
        $('#left_receive').show();
        if(scurrentModulCodeForLeft=='RECEIVED-RECORD'){
            $('#left_receive_receive').addClass('level1_visited');
        }
        if(scurrentModulCodeForLeft=='RECEIVED-TRANSITION'){
            $('#left_receive_transition').addClass('level1_visited');
        }
        if(scurrentModulCodeForLeft=='RECEIVED-RESULT'){
            $('#left_receive_result').addClass('level1_visited');
        }
        if(scurrentModulCodeForLeft=='RECEIVED-ADDITIONAL'){
            $('#left_receive_additional').addClass('level1_visited');
        }
        if(scurrentModulCodeForLeft=='RECEIVED-PROCESSING'){
            $('#left_receive_processing').addClass('level1_visited');
        }
    }

    if(sCurrentModulCode=='HANDLE'){
        $('#left_handle').show();
        if(scurrentModulCodeForLeft=='HANDLE-RECORD'){
            $('#left_handle_main').addClass('level1_visited');
        }
        if(scurrentModulCodeForLeft=='HANDLE-RESULT'){
            $('#left_handle_result').addClass('level1_visited');
        }
        if(scurrentModulCodeForLeft=='HANDLE-ADDITIONAL'){
            $('#left_handle_additional').addClass('level1_visited');
        }
        if(scurrentModulCodeForLeft=='HANDLE-APPROVED'){
            $('#left_handle_approved').addClass('level1_visited');
        }
        if(scurrentModulCodeForLeft=='HANDLE-TRANSITION'){
            $('#left_handle_transition').addClass('level1_visited');
        }
    }

    if(sCurrentModulCode=='ASSIGN'){
        $('#left_approve').show();
        if(scurrentModulCodeForLeft=='ASSIGN-RECORD'){
            $('#left_approve_assignWait').addClass('level1_visited');
        }
        if(scurrentModulCodeForLeft=='ASSIGNED-RECORD'){
            $('#left_approve_assign').addClass('level1_visited');
        }
        if(scurrentModulCodeForLeft=='APPROVE'){
            $('#left_approve_approveWait').addClass('level1_visited');
        }
        if(scurrentModulCodeForLeft=='APPROVED'){
            $('#left_approve_approved').addClass('level1_visited');
        }
        if(scurrentModulCodeForLeft=='APPROVE-TRANSITION'){
            $('#left_approve_transition').addClass('level1_visited');
        }
    }

    if(sCurrentModulCode=='SEARCH'){
        $('#left_search').show();
        if(scurrentModulCodeForLeft=='index'){
            $('#left_search_record').addClass('level1_visited');
        }
        if(scurrentModulCodeForLeft=='link'){
            $('#left_search_link').addClass('level1_visited');
        }
        if(scurrentModulCodeForLeft=='general'){
            $('#left_search_general').addClass('level1_visited');
        }
        if(scurrentModulCodeForLeft=='status'){
            $('#left_search_general').addClass('level1_visited');
        }
    }
</script>