<?php
	//Ham Const
    $objconfig = new Efy_Init_Config();
	$arrConst	=	$objconfig->_setProjectPublicConst();
    $sOwnerCode	= $_SESSION['OWNER_CODE'];
    $sOwnerCodeRoot = $objconfig->_getOwnerCode();
?>
<div id="Iddiv_leftmenu">	
	<!--Menu trai cua Ho so qua mang-->
	<div id ="left_receiveonnet" style="display:none;">
		<table width="100%" cellpadding="0"  cellspacing="0" border="0" class="body3">		
			<tr>
				<td valign="top">
					<table width="98%" cellpadding="0"  cellspacing="0" align="center"  class="left_menu_table">	
						<!--Cau lenh If...Else phan quyen-->			
							<tr>  
								<td id ="left_receiveonnet_preliminary" class="level1" >						
									<a href="<?php echo $this->baseUrl;?>../record/receiveonnet/index/">HS tiếp nhận sơ bộ</a>
								</td>
							</tr>	
							<tr>  
								<td id ="left_receiveonnet_supplementrecordlist" class="level1" >						
									<a href="<?php echo $this->baseUrl;?>../record/receiveonnet/supplementrecordlist/">HS chờ bổ sung</a>
								</td>
							</tr>	
							<tr>  
								<td id ="left_receiveonnet_officialrecordlist" class="level1" >						
									<a href="<?php echo $this->baseUrl;?>../record/receiveonnet/officialrecordlist/">HS tiếp nhận chính thức</a>
								</td>
							</tr>	
					</table>
				</td>						
			</tr>
		</table>	
	</div>	
	<!--Menu trai cua TN&TKQ-->
    <? if($sOwnerCode==$sOwnerCodeRoot){?>
	    <div id ="left_receive" style="display:none;">
		<table width="100%" cellpadding="0"  cellspacing="0" border="0" class="body3">		
			<tr>
				<td valign="top">
					<table width="98%" cellpadding="0"  cellspacing="0" align="center"  class="left_menu_table">	
						<!--Cau lenh If...Else phan quyen-->			
							<tr>  
								<td id ="left_receive_receive" class="level1" >						
									<a href="<?php echo $this->baseUrl;?>../record/receive/index">HS &#273;&#227; ti&#7871;p nh&#7853;n</a>
								</td>
							</tr>	
                            <tr>
								<td id ="left_receive_transition" class="level1" >						
									<a href="<?php echo $this->baseUrl;?>../record/receive/transition">HS li&#234;n th&#244;ng ch&#7901; nh&#7853;n</a>
								</td>
							</tr>
							<tr>
								<td id ="left_receive_additional" class="level1" >						
									<a href="<?php echo $this->baseUrl;?>../record/receive/additional">HS ch&#7901; b&#7893; sung</a>
								</td>
							</tr>
							<tr>  
								<td id ="left_receive_processing" class="level1" >						
									<a href="<?php echo $this->baseUrl;?>../record/receive/processing">HS &#273;ang gi&#7843;i quy&#7871;t</a>
								</td>
							</tr>
							<tr>  
								<td id ="left_receive_result" class="level1" >						
									<a href="<?php echo $this->baseUrl;?>../record/receive/result">HS ch&#7901; TKQ</a>
								</td>
							</tr>
					</table>
				</td>						
			</tr>
		</table>	
	</div>
    <? }else{ ?>
        <div id ="left_receive" style="display:none;">
            <table width="100%" cellpadding="0"  cellspacing="0" border="0" class="body3">
                <tr>
                    <td valign="top">
                        <table width="98%" cellpadding="0"  cellspacing="0" align="center"  class="left_menu_table">
                            <tr>
                                <td id ="left_receive_receive" class="level1" >
                                    <a href="<?php echo $this->baseUrl;?>../record/wreceive/index">HS &#273;&#227; ti&#7871;p nh&#7853;n</a>
                                </td>
                            </tr>
                            <tr>
                                <td id ="left_receive_additional" class="level1" >
                                    <a href="<?php echo $this->baseUrl;?>../record/wreceive/additional">HS ch&#7901; b&#7893; sung</a>
                                </td>
                            </tr>
                            <tr>
                                <td id ="left_receive_processing" class="level1" >
                                    <a href="<?php echo $this->baseUrl;?>../record/wreceive/processing">HS trình lãnh đạo</a>
                                </td>
                            </tr>
                            <tr>
                                <td id ="left_receive_transition" class="level1" >
                                    <a href="<?php echo $this->baseUrl;?>../record/wreceive/transition">HS liên thông huyện</a>
                                </td>
                            </tr>
                            <tr>
                                <td id ="left_receive_result" class="level1" >
                                    <a href="<?php echo $this->baseUrl;?>../record/wreceive/result">HS ch&#7901; TKQ</a>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </div>
    <? } ?>
	<!--Menu trai cua Thụ lý -->
	<div id ="left_handle" style="display:none;">
		<table width="100%" cellpadding="0"  cellspacing="0" border="0" class="body3">		
			<tr>
				<td valign="top">
					<table width="98%" cellpadding="0"  cellspacing="0" align="center"  class="left_menu_table">	
						<!--Cau lenh If...Else phan quyen-->			
							<tr>
								<td id ="left_handle_main" class="level1" >						
									<a href="<?php echo $this->baseUrl;?>../record/handle/index">HS c&#7847;n gi&#7843;i quy&#7871;t</a>
								</td>
							</tr>
							<tr>
								<td id ="left_handle_additional" class="level1" >						
									<a href="<?php echo $this->baseUrl;?>../record/handle/list">HS ch&#7901; b&#7893; sung</a>
								</td>
							</tr>
							<tr>  
								<td id ="left_handle_approved" class="level1" >
									<a href="<?php echo $this->baseUrl;?>../record/handle/approved">HS &#273;&#227; tr&#236;nh k&#253;</a>
								</td>
							</tr>
                            <tr>
								<td id ="left_handle_result" class="level1" >
									<a href="<?php echo $this->baseUrl;?>../record/handle/result">HS &#273;&#227; c&#243; k&#7871;t qu&#7843;</a>
								</td>
							</tr>
					</table>
				</td>						
			</tr>
		</table>	
	</div>
	<!--Menu trai cua Phê duyệt -->
    <? if($sOwnerCode==$sOwnerCodeRoot){?>
	<div id ="left_approve" style="display:none;">
		<table width="100%" cellpadding="0"  cellspacing="0" border="0" class="body3">		
			<tr>
				<td valign="top">
					<table width="98%" cellpadding="0"  cellspacing="0" align="center"  class="left_menu_table">	
						<!--Cau lenh If...Else phan quyen-->	
						<?
						if(Efy_Function_RecordFunctions::eCSPermisstionApproveForRecordType($_SESSION['staff_id'],'DUYET_CAP_BA',$_SESSION['arr_all_record_type'])!='DUYET_CAP_BA'){ 		
							?>
							<tr>  
								<td id ="left_approve_assignWait" class="level1" >						
									<a href="<?php echo $this->baseUrl;?>../record/assign/index">HS ch&#7901; ph&#226;n c&#244;ng</a>
								</td>
							</tr>
							<tr>
								<td id ="left_approve_assign" class="level1" >
									<a href="<?php echo $this->baseUrl;?>../record/assign/assigned">HS &#273;&#227; ph&#226;n c&#244;ng</a>
								</td>
							</tr>
						<? }?>
							<tr>
								<td id ="left_approve_approveWait" class="level1" >						
									<a href="<?php echo $this->baseUrl;?>../record/approve/index">HS ch&#7901; duy&#7879;t</a>
								</td>
							</tr>
                            <tr>
                                <td id ="left_approve_approved" class="level1" >
                                    <a href="<?php echo $this->baseUrl;?>../record/approve/approved">HS đã duyệt</a>
                                </td>
                            </tr>
					</table>
				</td>						
			</tr>
		</table>	
	</div>
    <? }else{ ?>
        <div id ="left_approve" style="display:none;">
            <table width="100%" cellpadding="0"  cellspacing="0" border="0" class="body3">
                <tr>
                    <td valign="top">
                        <table width="98%" cellpadding="0"  cellspacing="0" align="center"  class="left_menu_table">
                            <tr>
                                <td id ="left_approve_approveWait" class="level1" >
                                    <a href="<?php echo $this->baseUrl;?>../record/wapprove/index">HS chờ duyệt</a>
                                </td>
                            </tr>
                            <tr>
                                <td id ="left_approve_approved" class="level1" >
                                    <a href="<?php echo $this->baseUrl;?>../record/wapprove/approved">HS đã duyệt</a>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </div>
    <? } ?>
	<!--Menu trai cua Tra cứu -->
	<div id ="left_search" style="display:none;">
		<table width="100%" cellpadding="0"  cellspacing="0" border="0" class="body3">		
			<tr>
				<td valign="top">
					<table width="98%" cellpadding="0"  cellspacing="0" align="center"  class="left_menu_table">	
						<!--Cau lenh If...Else phan quyen-->			
                        <tr>
                            <td id ="left_search_general" class="level1" >
                                <a href="<?php echo $this->baseUrl;?>../record/search/general">S&#7889; li&#7879;u t&#7893;ng h&#7907;p</a>
                            </td>
                        </tr>
                        <tr>
                            <td id ="left_search_record" class="level1" >
                                <a href="<?php echo $this->baseUrl;?>../record/search/index">T&#236;m ki&#7871;m h&#7891; s&#417;</a>
                            </td>
                        </tr>
					</table>
				</td>						
			</tr>
		</table>	
	</div>	
	<!--Menu trai cua bao cao -->
	<div id ="left_report" style="display:none;">
		<table width="100%" cellpadding="0"  cellspacing="0" border="0" class="body3">		
			<tr>
				<td valign="top">
					<table width="98%" cellpadding="0"  cellspacing="0" align="center"  class="left_menu_table">
                        <?  if($_SESSION['STAFF_PERMISSTION']==Efy_Init_Config::_setPermisstionSystem(1)){ ?>
                        <tr>
                            <td id ="left_report_general" class="level1" >
                                <a href="<?php echo $this->baseUrl;?>../record/normalreport/general/">Báo cáo chung</a>
                            </td>
                        </tr>
                        <? } ?>
                        <tr>
                            <td id ="left_report_recordtype" class="level1" >
                                <a href="<?php echo $this->baseUrl;?>../record/normalreport/index/">Báo cáo theo từng TTHC</a>
                            </td>
                        </tr>
					</table>
				</td>						
			</tr>
		</table>	
	</div>
	<!--Menu trai cua menu danh muc-->		
	<div id ="left_list" style="display:none"> 
		<table width="100%" cellpadding="0"  cellspacing="0" class="body3">	
			<tr >
				<td valign="top">
					<table width="98%" cellpadding="0"  cellspacing="0" align="center"  class="left_menu_table">
                        <tr>
                            <td id ="left_list_recordtype" class="level1" >
                                <a href="<?php echo $this->baseUrl;?>../listxml/recordtype/index/"><?=$arrConst['_DM_TTHC']?></a>
                            </td>
                        </tr>
                        <tr>
                            <td id ="left_list_listtype" class="level1" >
                                <a href="<?php echo $this->baseUrl;?>../listxml/listtype/index/"><?=$arrConst['_DM_LOAI']?></a>
                            </td>
                        </tr>
                        <tr>
                            <td id ="left_list_list" class="level1">
                                <a href="<?php echo $this->baseUrl;?>../listxml/list/index/" ><?=$arrConst['_DM_DOITUONG']?></a>
                            </td>
                        </tr>
                        <tr>
                            <td id ="left_list_report" class="level1">
                                <a href="<?php echo $this->baseUrl;?>../listxml/report/index/"><?=$arrConst['_DM_BAOCAO']?></a>
                            </td>
                        </tr>
					</table>
				</td>
			</tr>
		</table>
	</div>
	<!-- thong tin nguoi dang nhap -->
	<div><?php echo $_SESSION['INFORMATION_STAFF_LOGIN'];?></div>
</div>	
<!--Xu ly JS!-->
<script type="text/javascript">
     function showHideMenu(p_id){
        var objfrm = document.getElementsByTagName('div');
        for(i=0; i<objfrm.length; i++){
            e = objfrm[i].getAttribute('id');
            if (objfrm[i].getAttribute('value') == "true"){
                if(e == p_id){
                    var pStyle	= eval("document.getElementById('" + p_id + "').style.display");
                    if (pStyle == "none"){
                        eval("document.getElementById('" + p_id + "').style.display = '" + "block'");
                    }else{
                        eval("document.getElementById('" + p_id + "').style.display = '" + "none'");
                    }
                }
            }
        }
     }

    try{<?php
        // Hien thi menu trai tuong ung voi menu ngang
        $sCurrentModulCode = $this->currentModulCode;
        $getModulLeft = $this->getStatusLeftMenu;
        $scurrentModulCodeForLeft = $this->currentModulCodeForLeft;
        //BAO CAO
        try {
            if ($sCurrentModulCode == "REPORTS"){?>
                document.getElementById('left_report').style.display = 'block';
                <?if($scurrentModulCodeForLeft == "NORMAL_REPORTS"){?>
                    document.getElementById('left_report_recordtype').className = "level1_visited";
                <?}if($scurrentModulCodeForLeft == "REPORTS"){ ?>
                    document.getElementById('left_report_general').className = "level1_visited";
                <?}
            }
        }catch (Exception $ex){;};
        //DANH MUC
        try {
            if ($sCurrentModulCode == "LIST"){?>
                document.getElementById('left_list').style.display = 'block';
                <?if($scurrentModulCodeForLeft == "RECORDTYPE"){?>
                    document.getElementById('left_list_recordtype').className = "level1_visited";
                <?}if($scurrentModulCodeForLeft == "LISTTYPE"){ ?>
                    document.getElementById('left_list_listtype').className = "level1_visited";
                <?}if($scurrentModulCodeForLeft == "LIST"){ ?>
                    document.getElementById('left_list_list').className = "level1_visited";
                <?}if($scurrentModulCodeForLeft == "PERMISSION"){ ?>
                    document.getElementById('left_list_permission').className = "level1_visited";
                <?}if($scurrentModulCodeForLeft == "BACKUP"){ ?>
                    document.getElementById('left_list_backup').className = "level1_visited";
                <?}if($scurrentModulCodeForLeft == "RESTORE"){ ?>
                    document.getElementById('left_list_restore').className = "level1_visited";
                <?}
            }
        }catch (Exception $ex){;};
        //TN HS QUA MANGs
        try {
            if ($sCurrentModulCode == "RECEIVE-ON-NET"){?>
                document.getElementById('left_receiveonnet').style.display = '';
                <?if($scurrentModulCodeForLeft == "PRELIMINARY"){//HS cho tiep nhan so bo?>
                    document.getElementById('left_receiveonnet_preliminary').className = "level1_visited";
                <?}if($scurrentModulCodeForLeft == "SUPPLEMENT"){//HS cho bo sung?>
                    document.getElementById('left_receiveonnet_supplementrecordlist').className = "level1_visited";<?php
                }if($scurrentModulCodeForLeft == "OFFICIAL"){//HS Tiep nhan chinh thuc?>
                    document.getElementById('left_receiveonnet_officialrecordlist').className = "level1_visited";<?php
                }
            }
        }catch (Exception $ex){;};
        //TN&TKQ
        try {
            if ($sCurrentModulCode == "RECORD"){?>
                document.getElementById('left_receive').style.display = '';
                <?if($scurrentModulCodeForLeft == "RECEIVED-RECORD"){?>
                    document.getElementById('left_receive_receive').className = "level1_visited";
                <?}if($scurrentModulCodeForLeft == "RECEIVED-TRANSITION"){?>
                    document.getElementById('left_receive_transition').className = "level1_visited";
                <?}if($scurrentModulCodeForLeft == "RECEIVED-RESULT"){?>
                    document.getElementById('left_receive_result').className = "level1_visited";
                <?}if($scurrentModulCodeForLeft == "RECEIVED-ADDITIONAL"){?>
                    document.getElementById('left_receive_additional').className = "level1_visited";
                <?}if($scurrentModulCodeForLeft == "RECEIVED-PROCESSING"){?>
                    document.getElementById('left_receive_processing').className = "level1_visited";
                <?}
            }
        }catch (Exception $ex){;};
        //Thu ly
        try {
            if ($sCurrentModulCode == "HANDLE"){?>
                document.getElementById('left_handle').style.display = '';
                <?if($scurrentModulCodeForLeft == "HANDLE-RECORD"){?>
                    document.getElementById('left_handle_main').className = "level1_visited";
                <?}if($scurrentModulCodeForLeft == "HANDLE-RESULT"){?>
                    document.getElementById('left_handle_result').className = "level1_visited";
                <?}if($scurrentModulCodeForLeft == "HANDLE-ADDITIONAL"){?>
                    document.getElementById('left_handle_additional').className = "level1_visited";
                <?}if($scurrentModulCodeForLeft == "HANDLE-APPROVED"){?>
                    document.getElementById('left_handle_approved').className = "level1_visited";
                <?}
            }
        }catch (Exception $ex){;};
        //PHE DUYET
        try {
            if ($sCurrentModulCode == "ASSIGN"){?>
                document.getElementById('left_approve').style.display = 'block';
                <?if($scurrentModulCodeForLeft == "ASSIGN-RECORD"){?>
                    document.getElementById('left_approve_assignWait').className = "level1_visited";
                <?}if($scurrentModulCodeForLeft == "ASSIGNED-RECORD"){?>
                    document.getElementById('left_approve_assign').className = "level1_visited";
                <?}
                if($scurrentModulCodeForLeft == "APPROVE"){?>
                    document.getElementById('left_approve_approveWait').className = "level1_visited";
                <?}
                if($scurrentModulCodeForLeft == "APPROVED"){?>
                    document.getElementById('left_approve_approved').className = "level1_visited";
                <?}
                }
            }catch (Exception $ex){;};
    //Tra cuu
    try {
        if ($sCurrentModulCode == "SEARCH"){?>
                document.getElementById('left_search').style.display = 'block';
                <?if($scurrentModulCodeForLeft == "index" ){?>
                    document.getElementById('left_search_record').className = "level1_visited";
                <?}if($scurrentModulCodeForLeft == "link" ){?>
                    document.getElementById('left_search_link').className = "level1_visited";
                <?}if($scurrentModulCodeForLeft == "general" || $scurrentModulCodeForLeft == "status"){?>
                    document.getElementById('left_search_general').className = "level1_visited";
                <?}
            }
        }catch (Exception $ex){;};
        ?>
    }catch(e){;}
</script>