
<form action="index" method="POST" id="frmRecord">	
<!--HIen thi tieu de man hinh danh sach!-->
	<table width='100%' border='0' cellspacing='0' cellpadding='0' style="border-right:#000E7B;" align="center">
		<tr>
			<td style="height:20px;"></td>
		</tr>
		<tr>
        	<td width="12px"></td>
			<td class="nhac_viec_title">
				<?=$this->bodyTitle;?><br>	
			</td>
			 <td width="12px"></td>
        </tr>
        <tr>
        	<td width="12px"></td>
			<td>
				<?php echo $this->Rss;?>
			</td>
			<td width="12px"></td>
        </tr>
	</table>
</form>