<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>HE THONG PHAN MEM MOT CUA DIEN TU</title>
<link rel="icon" href="<?= $this->baseUrl?>images/efy.ico" type="image/x-icon" />
<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl?>style/style.css">
<!--Dinh nghia hang so dung chung cho JS!-->
<?= $this->JSPublicConst;?>
<script src="<?= $this->baseUrl?>js/ajax.js" type="text/javascript"></script>
<script src="<?= $this->baseUrl?>js/util.js" type="text/javascript"></script>
<script src="<?= $this->baseUrl?>js/jquery-1.5.1.js" type="text/javascript"></script>
</head>
<body topmargin="0" leftmargin="0" marginheight="0" marginwidth="0" rightmargin="0" width="100%">
	<div id="all">
        <table  width="100%" cellpadding="0" cellspacing="0" class="body1" border="0">
            <tr>
                <td  width="100%" style="background:#fff;" valign="top">
                    <?=$this->layout()->content;?>
                </td>
            </tr>
        </table>
    </div>
</body>
</html>
