<script type="text/javascript">
    function changepassForm() {
        if ($('#txtOldpass').val() == '') {
            alert('Nhập mật khẩu cũ!');
            $('#txtOldpass').focus();
            return false;
        }
        if ($('#txtNewpass').val() == '') {
            alert('Nhập mật khẩu mới!');
            $('#txtNewpass').focus();
            return false;
        }
        if ($('#txtRenewpass').val() == '') {
            alert('Nhập xác nhận mật khẩu mới!');
            $('#txtRenewpass').focus();
            return false;
        }
        if ($('#txtNewpass').val() != $('#txtRenewpass').val()) {
            alert('Vui lòng xác nhận mật khẩu mới!');
            return false;
        }
        document.getElementById('hdnaction').value = 'changepass';
        document.getElementById('frmchangepass').submit();
    }
</script>
<form action="" method="POST" name="frmchangepass" id="frmchangepass" onsubmit="return changepassForm()">
    <input type="hidden" id="hdnaction" name="hdnaction">

    <div class="changepass">THAY ĐỔI MẬT KHẨU</div>
    <div class="account">
        <div style="text-align:center;padding:0 120px;">
            <div style="text-align:left;">
                <label class="normal_label">Mật khẩu cũ (<span class="requiein">*</span>)</label>
                <input class="textbox" id="txtOldpass" name="txtOldpass" type="password" size="20">
            </div>
            <div style="text-align:left;">
                <label class="normal_label">Mật khẩu mới (<span class="requiein">*</span>)</label>
                <input class="textbox" id="txtNewpass" name="txtNewpass" type="password" size="20">
            </div>
            <div style="text-align:left;">
                <label class="normal_label">Xác nhận mật khẩu mới (<span class="requiein">*</span>)</label>
                <input class="textbox" id="txtRenewpass" name="txtRenewpass" type="password" size="20">
            </div>
        </div>
        <div class="d_button">
            <input type="submit" class="link-button" value="Cập nhật">
            <input type="button" style="margin-left:10px;" class="link-button" value="Quay lại"
                   onclick="window.location='<?= $this->urlback ?>'">
        </div>
    </div>
</form>
<style>
    div.changepass {
        background-color: #E0E0E0;
        background-image: -moz-linear-gradient(#FFFFFF, #E0E0E0);
        border-bottom: 0 none #FFFFFF;
        border-color: #FFFFFF;
        border-radius: 5px 5px 0 0;
        box-shadow: 0 0 2px rgba(0, 0, 0, 0.52);
        color: #C90101;
        font-weight: bold;
        height: 25px;
        text-align: center;
        text-shadow: 1px 1px 1px rgba(255, 255, 255, 0.75);
        margin: 0 10px;
    }

    div.account label {
        float: left;
        width: 160px;
    }

    div.account div {
        width: 400px;
        margin: 0 auto;
        margin-top: 5px;
    }

    div.d_button {
        text-align: center;
    }
</style>
