<div class="row row_01">
    <div class="login_area">
        <div class="head">
            <div class="logo">
                <!--<img src="<?= $this->baseUrl ?>images/img_skin/logo.png">-->
            </div>
            <div class="title">
                <p class="adress">
                    <?= $this->ownerFullName; ?>
                </p>

                <p class="name_app">
                    <?= $this->appName; ?>
                </p>
            </div>
        </div>
        <form id="gaia_loginform" action="" method="post" novalidate="">
            <input type="hidden" id="sCode" name="sCode" value="<?= $this->sCode;?>" />
            <div class="box_login">
                <div class="img_avatar">
                    <img src="<?= $this->baseUrl ?>images/img_skin/avatar_login.png">
                </div>
                <?php
                if ($this->sCode == 1) { ?>
                    <input type="hidden" id="username" name="username" value="<?=$this->username;?>" />
                    <div class="text_field">
                        <label class="title icon_id"></label>
                        <input class="text" type="text" id="auth_code" name="auth_code" value="" autofocus="autofocus"
                               placeholder="Mã xác thực"/>
                    </div>
                    <div class="button">
                        <button class="btn btn_login" type="submit" name="signIn" id="signIn">Xác minh</button>
                    </div>
                <?php
                } else { ?>
                    <input type="hidden" id="username" name="username" value="<?=$this->username;?>" />
                    <div class="text_field">
                        <label class="title icon_pass"></label>
                        <input class="text" type="password" id="password" name="password" placeholder="Nhập mật khẩu mới">
                    </div>
                    <div class="text_field">
                        <label class="title icon_pass"></label>
                        <input class="text" type="password" id="repassword" name="repassword" placeholder="Nhập lại mật khẩu">
                    </div>
                    <div class="button">
                        <button class="btn btn_login" type="submit" name="signIn" id="signIn">Đổi mật khẩu</button>
                    </div>
                <?php
                }
                ?>
            </div>
        </form>

        <div class="forgot_pass" style="font-size:18px;padding-top: 20px; ">
            <a href="<?= $this->baseUrl() . '/index/' ?>">Quay lại đăng nhập</a>
        </div>
        <p class="caption">Liên hệ với chúng tôi để thêm thông tin hỗ trợ dịch vụ và sản phẩm</p>


    </div>
</div>

<script type="text/javascript">
    var message = '<?= $this->message;?>',
        sCode = '<?= $this->sCode;?>'
    if (message != '')  jAlert(message, 'Thông báo', function() {
        if (sCode == 3) {
            window.location.href = '<?=G_Global::getInstance()->urlLogin()?>';
        }
    })
    $('form#gaia_loginform').submit(function () {
        var sCode = $('#sCode').val();
        switch(sCode) {
            case 1:
                if ($('#auth_code').val() == '' || $('#username').val() == '') {
                    return false;
                }
                break;
            default:
                if ($('#password').val() == '' || $('#repassword').val() =='' || $('#username').val() == '' || $('#auth_code').val() == '') {
                    return false;
                }
                if ($('#password').val() != $('#repassword').val()) {
                    jAlert('Nhập lại mật khẩu chưa chính xác!', 'Thông báo');
                    return false;
                }
                break;
        }
    })

    $(document).ready(function(){
        $('#password').val('');
    })
</script>