<div class="row row_01">
    <div class="login_area">
        <div class="head">
            <div class="logo">
            </div>
            <div class="title">
                <p class="adress">
                    <?= $this->ownerFullName; ?>
                </p>

                <p class="name_app">
                    <?= $this->appName; ?>
                </p>
            </div>
        </div>
        <form id="gaia_loginform" action="" method="post">
            <input type="hidden" id="sCode" name="sCode" value="<?= $this->sCode;?>" />
            <div class="box_login">
                <div class="img_avatar">
                    <img src="<?= $this->baseUrl ?>images/img_skin/avatar_login.png">
                </div>
                <?php
                if ($this->sCode == '') { ?>
                    <div class="text_field">
                        <label class="title icon_id"></label>
                        <input class="text" type="text" id="username" name="username" value="" autofocus="autofocus"
                               placeholder="Tên đăng nhập" required/>
                    </div>
                    <div class="text_field">
                        <label class="title icon_email"></label>
                        <input class="text" type="email" id="emailname" name="emailname" placeholder="Địa chỉ email" required>
                    </div>
                    <div class="button">
                        <button class="btn btn_login" type="submit" name="signIn" id="signIn">Lấy mật khẩu</button>
                    </div>
                <?php
                }
                ?>
            </div>
            <?php
                if ($this->sCode == 1) { ?>
                    <div class="box-message">
                        <p><?= $this->message;?></p>
                    </div>
                <?php
                }
                ?>
        </form>

        <div class="forgot_pass" style="font-size:18px;padding-top: 20px; ">
            <a href="<?= $this->baseUrl() . '/index/' ?>">Quay lại đăng nhập</a>
        </div>
        <p class="caption">Liên hệ với chúng tôi để thêm thông tin hỗ trợ dịch vụ và sản phẩm</p>


    </div>
</div>

<script type="text/javascript">
    var message = '<?= $this->message;?>'
    if (message != '')  jAlert(message, 'Thông báo');
</script>