<?php
    $mysession = new Zend_Session_Namespace('authtoken');
    $hash = $mysession->authtoken;
?>
<div class="sign_in_area">
    <div class="button-close">
        <span>Đóng lại</span>
        <span class="button_x">X</span> 
    </div>
    <form id="g4tlogin" name="g4tlogin" class="item" method="POST" autocomplete="off" enctype="multipart/form-data">
        <input type="hidden" name="authtoken" value="<?=$hash?>" />
        <div class="col-email">
            <p>Email</p>
            <input type="email" name="newsletterEmail" id="newsletterEmail" placeholder="" required oninput="InvalidMsg(this);" oninvalid="InvalidMsg(this);" requiredmessage="Bạn phải nhập Email!">
        </div>
        <div class="col-pass">
            <p>Mật khẩu</p>
            <input type="password" name="newsletterpass" id="newsletterpass" placeholder="" required oninvalid="InvalidMsg(this);" oninput="InvalidMsg(this);" requiredmessage="Bạn phải nhập mật khẩu!">
            <div class="checkbox">
                <input class="checkinput chkbox" type="checkbox" checked="checked" name="dwfrm_login_rememberme" id="dwfrm_login_rememberme" value="true" maxlength="2147483647">
                <label for="dwfrm_login_rememberme">Duy trì đăng nhập</label>
            </div>
        </div>
        <div class="button-sign-in">
            <button class="btn-sign-in" type="submit" name="sign_in" >Đăng nhập</button>
        </div>
        <div class="register">
            <P class="head">
                Bạn là thành viên mới, chưa đăng ký
            </P>
            <button class="btn-sign-up" type="button" name="sign_up" >Tạo tài khoản mới</button>
        </div>
        <p class="forgotpass"><a href="">Quên mật khẩu ?</a></p>
    </form>
</div>


<script>
(function ($) {
    $.fn.account_login = function (options) {
        var self = this;

        options = $.extend({
            url: baseUrl + '/login'
        }, options);

        var initialize = function () {
            eventForm();
        };

        function eventForm() {
            $('[name="sign_up"]', self).click(function() {
                $('#sign_in').fadeOut(500);
                $('#sign_up').fadeIn(500);
            })
            $(self).submit(function(event) {

                if ($(self)[0].checkValidity()) {
                    var data = {
                        authtoken: $('[name="authtoken"]', self).val(),
                        newsletterEmail: $.base64.encode($('#newsletterEmail', self).val()),
                        newsletterpass: $.base64.encode($('#newsletterpass', self).val()),
                        dwfrm_login_rememberme: $('#dwfrm_login_rememberme', self).is(':checked')
                    }
                    $.ajax({
                        url: options.url,
                        type: "POST",
                        data: data,
                        dataType: 'json',
                        success: function (rsp) {
                            hideloadpage();
                            if (rsp.logined == 1) {
                                window.location.reload()
                            } else {
                                jAlert(rsp.msg, 'Thông báo');
                            }
                        },
                        beforeSend: function (xhr) {
                            showloadpage();
                        },
                        errors: function () {
                            hideloadpage();
                        }
                    });
                }
                return false;
            })
        }

        // Khoi tao
        initialize.call(this);
    }


})(jQuery);


$(document).ready(function($) {
        $('form#g4tlogin').account_login({
        });
    });
</script>