<?php
    $mysession = new Zend_Session_Namespace('authtoken');
    $hash = $mysession->authtoken;
?>
<div class="box_sign_up">
    <div class="button-close">
        <span>Đóng lại</span>
        <span class="button_x">X</span> 
    </div>
    <p class="head">Đăng ký</p>
    <form action="" method="post" id="RegistrationForm" novalidate="novalidate">
        <input type="hidden" name="authtoken" value="<?=$hash?>" />
        <fieldset>
            <div class="formfields">
                <div class="formfield">
                    <div class="label">
                        <span class="requiredindicator">*</span>
                        <span class="labeltext">Họ</span>
                    </div><!-- END: label -->
                    <div class="value">
                        <input class="textinput customername required" id="customer_firstname" type="text" name="customer_firstname" value="" maxlength="19">
                    </div>
                    <div class="clear"><!-- FOAT CLEAR --></div>
                </div><!-- END: firstname -->
                <div class="formfield">
                    <div class="label">
                        <span class="requiredindicator">*</span>
                        <span class="labeltext">Tên</span>
                    </div><!-- END: label -->
                    <div class="value">
                        <input class="textinput customername required" id="customer_lastname" type="text" name="customer_lastname" value="" maxlength="20">
                    </div>
                    <div class="clear"><!-- FOAT CLEAR --></div>
                </div>
            </div><!-- END: formfields -->
            
            <div class="formfields">
                <div class="formfield accountbirthday">
                    <div class="label">ngày sinh</div>
                    
                    <div class="value">
                        <select class="selectbox day" id="birthday_day" name="birthday_day">
                            <option class="selectoption" label="Ngày" value="">Ngày</option>
                            <?php
                            $day = date('Y');
                            for ($i=1; $i <= 31; $i++) { 
                                $index = ($i<10 ? '0'.$i : $i);
                            ?>
                                <option class="selectoption" label="<?=$index?>" value="<?=$i?>"><?=$index?></option>
                            <?php
                            }
                            ?>
                            
                        </select>
                    </div>
                    <div class="value">
                            <select class="selectbox month" id="birthday_month" name="birthday_month">
                                    <option class="selectoption" label="Tháng" value="">Tháng</option>
                                    <?php
                                    $day = date('Y');
                                    for ($i=1; $i <= 12; $i++) { 
                                        $index = 'Tháng ' . $i;
                                    ?>
                                        <option class="selectoption" label="<?=$index?>" value="<?=$i?>"><?=$index?></option>
                                    <?php
                                    }
                                    ?>
                            </select>
                    </div>
                    
                    
                    <div class="value">
                        <select class="selectbox year" id="birthday_year" name="birthday_year">
                            <option class="selectoption" label="Năm" value="">Năm</option>
                            <?php
                            $year = date('Y');
                            for ($i=15; $i < 60; $i++) { 
                                $index = $year-$i;
                            ?>
                                <option class="selectoption" label="<?=$index?>" value="<?=$index?>"><?=$index?></option>
                            <?php
                            }
                            ?>
                        </select>
                    </div>
                    <div class="clear"><!-- FLOAT CLEAR --></div>
                </div><!-- END: birthday -->
            
                <div class="formfield gender">
                    <div class="label">Giới tính</div>
                    <div class="value"> 
                            <input name="customer_gender" type="radio" class="radio" id="2" value="2">Nữ
                            <input name="customer_gender" type="radio" class="radio" id="1" value="1" checked="checked" >Nam
                    </div><!-- END: value -->
                    <div class="clear"><!-- FLOAT CLEAR --></div>
                </div><!-- END: Gender -->
                
                <div class="formfield">
                    <div class="label">
                        <span class="labeltext" for="customer_idcard">Số CMND</span>
                    </div><!-- END: label -->
                    <div class="value">
                        <input class="textinput" id="customer_idcard" type="text" name="customer_idcard" value="" alt="">
                    </div>
                    <div class="clear"><!-- FOAT CLEAR --></div>
                </div>

            
                <div class="formfield">
                    <div class="label">
                        <span class="labeltext">Số điện thoại</span>
                    </div><!-- END: label -->
                    <div class="value">
                        <input class="textinput" id="customer_mobile" type="text" name="customer_mobile" value="" alt="us_phone">
                    </div>
                    <div class="mobilealerts">Điền số điên thoại của bạn để chúng tôi gửi những thông tin mới và hữu ích nhất</div>
                    <div class="clear"><!-- FOAT CLEAR --></div>
                </div>
                <div class="formfield">
                    <div class="label">
                        <span class="requiredindicator">*</span>
                        <span class="labeltext">Email</span>
                    </div><!-- END: label -->
                    <div class="value">
                        <input class="textinput email required" id="customer_email" type="text" name="customer_email" value="" maxlength="50">
                    </div>
                    <div class="clear"><!-- FOAT CLEAR --></div>
                </div>
                <div class="formfield">
                    <div class="label">
                            <span class="requiredindicator">*</span>
                            <span class="labeltext">Nhập lại Email</span>
                    </div><!-- END: label -->
                    <div class="value">
                            <input class="textinput email required" id="customer_emailconfirm" type="text" name="customer_emailconfirm" value="" maxlength="50">
                    
                    </div>
                    <div class="clear"><!-- FOAT CLEAR --></div>
                </div>
                <div class="formfield">
                    <div class="label">
                        <span class="requiredindicator">*</span>
                        <span class="labeltext">Mật khẩu</span>
                    </div><!-- END: label -->
                    <div class="value">
                        <input class="textinputpw required" id="login_password" type="password" name="login_password" value="" maxlength="20" autocomplete="off">
                    </div>
                    <div class="clear"><!-- FOAT CLEAR --></div>
                </div>
                <div class="formfield">
                    <div class="label">
                            <span class="requiredindicator">*</span>
                            <span class="labeltext">Nhập lại mật khẩu</span>
                    </div><!-- END: label -->
                    <div class="value">
                            <input class="textinputpw required" id="login_passwordconfirm" type="password" name="login_passwordconfirm" value="" maxlength="20" autocomplete="off">
                    </div>
                    <div class="clear"><!-- FOAT CLEAR --></div>
                </div>
                <div class="formfield">
                    <div class="emailsignupcheckbox">
                        <div class="checkbox">
                            <input class="checkinput" type="checkbox" checked="checked" name="customer_addtoemaillist" id="customer_addtoemaillist" value="true" maxlength="2147483647">
                        </div>
                    </div>  
                    <div class="emailsignup">
                        <span>Đăng ký nhận tin nhắn từ Chúng tôi</span>
                    </div>
                    <div class="clear"><!-- FOAT CLEAR --></div>
                </div>

                <div class="formfield">
                    <div class="label">
                            <span class="requiredindicator">*</span>
                            <span class="labeltext">Mã xác nhận</span>
                    </div><!-- END: label -->
                    <div class="value">
                            <input class="textinputpw required" id="captcha[input]" type="text" name="captcha[input]" value="" maxlength="20" autocomplete="off">
                    </div>
                    <div class="capcha">
                        <input name="captcha[id]" type="hidden" value="<?= $this->captchId ?>" />
						<a class="img_capcha" id="getCaptcharImg" style="cursor: pointer;height: 80px;width: 195px;" title="Click để lấy ảnh khác">
                            <img id = "captcha" src="" alt="Mã capcha" />
                        </a>
                    </div>
                    <div class="clear"><!-- FOAT CLEAR --></div>
                </div>
                <div class="formactions">
                    <button class="registrationcreateaccount mediumbutton" type="submit" value="Apply" name="profile_confirm"><span>ĐĂNG KÝ</span></button>
                </div>
                <div id="registrationformaction"></div> 
            </div><!-- END: formfields -->
        </fieldset>
    </form>
</div>


<script>
(function ($) {
    $.fn.account_register = function (options) {
        var self = this;

        options = $.extend({
            url_register: baseUrl + '/account/index/register',
            captchaUrl: baseUrl + '/captcha',
            captcharImg: baseUrl + '/io/export'
        }, options);

        var initialize = function () {
            eventForm();
        };

        function eventForm() {
            $('#getCaptcharImg',self).click(function(){
                getCaptcha();
            })
            $(self).submit(function(event) {

                if ($(self)[0].checkValidity()) {
                    if ($('#login_password').val() != $('#login_passwordconfirm').val()) {
                        document.getElementById('rePassWord').setCustomValidity('Nhập lại mật khẩu chưa chính xác!');
                        return false;
                    } else {
                        document.getElementById('login_passwordconfirm').setCustomValidity('');
                    }
                }

                submitForm();
                return false;
            })
        }

        function submitForm() {
            var login_password = $('#login_password', self).val(),
                login_passwordconfirm = $('#login_passwordconfirm', self).val();
            $('#login_password', self).val($.base64.encode(login_password));
            $('#login_passwordconfirm', self).val($.base64.encode(login_passwordconfirm));
            $.ajax({
                    url: options.url_register,
                    type: "POST",
                    data: $(self).serialize(),
                    dataType: 'json',
                    success: function (rsp) {
                        $('#login_password', self).val(login_password);
                        $('#login_passwordconfirm', self).val(login_passwordconfirm);
                        hideloadpage();
                        jAlert(rsp.msg, 'Thông báo');
                        if (rsp.error == false) {
                            $('#RegistrationForm')[0].reset();
                            $('.button-close').trigger('click')
                        }
                    },
                    beforeSend: function (xhr) {
                        showloadpage();
                    },
                    errors: function () {
                        hideloadpage();
                    }
            });
        }
        function getCaptcha(){
            $.ajax({                
                  url: options.captchaUrl, type: 'GET', dataType: 'html',
                  success: function(data){
                     $('#captcha', self).attr('src', options.captcharImg + '/'+ data.toString() + '.png');
                     $('input[name="captcha[id]"]', self).val(data.toString());
                  }
             });
        }
        
        // Khoi tao
        initialize.call(this);
    }


})(jQuery);
</script>


<script type = "text/javascript">
    $(document).ready(function($) {
        $('form#RegistrationForm').account_register({
        });
    });

</script>