<div class="row row_01">
    <div class="login_area">
        <div class="head">
            <div class="logo">
                <!--<img src="<?= $this->baseUrl ?>images/img_skin/logo.png">-->
            </div>
            <div class="title">
                <p class="adress">
                    uỷ ban nhân dân huyện Phú Lương
                </p>

                <p class="name_app">
                    Phần mềm hỗ trợ kê khai hồ sơ đất
                </p>
            </div>
        </div>

        <p class="" style="font-size:28px;padding-top: 20px;color: #fff; ">Vui lòng kiểm tra email để lấy mật khẩu!</p>

        <div class="forgot_pass" style="font-size:18px;padding-top: 20px; ">
            <a href="<?= $this->baseUrl() . '/index/' ?>">Quay lại đăng nhập</a>
        </div>
        <p class="caption">Liên hệ với chúng tôi để thêm thông tin hỗ trợ dịch vụ và sản phẩm</p>

    </div>
</div>
