<script>
    if (typeof(site_search) != 'function') {
        var arrJsCss = $.parseJSON('<?=$this->arrJsCss; ?>');
        loadfileJsCss(arrJsCss);
    }
</script>
<?php
$arrRecord = $this->arrRecord;
$arrRecordWork = $this->arrRecordWork;
?>
<div class="row_01">
    <div class="header">
        <p class="title">Tra cứu trạng thái hồ sơ</p>
    </div>
    <div class="content">
        <div class="cl_left">
            <form id="frm_search_index" accept-charset="utf-8" action="" method="POST" autocomplete="off">
                <div class="search_bar">
                    <div class="search_bar_area">
                        <input class="textinput code required" id="customer_code" type="text" name="customer_code" value="<?=$this->customer_code;?>" placeholder="Nhập mã số biên nhận" maxlength="50">
                        <input type="submit" value="Tra cứu" class="button-submit">
                    </div>
                </div>
                <?php
                if ($arrRecord) { ?>
                <div class="search_result">
                    <p class="title">Thông tin hồ sơ</p>
                    <table id="table-data" class="list-table-data" cellspacing="0" cellpadding="0" border="0" align="center">
                        <colgroup><col width="25%"><col width="75%"></colgroup>
                        <tbody>
                            <tr class="normal_label">
                                <td>Tên TTHC</td><td><?=$arrRecord['C_RECORDTYPE_NAME']?></td>
                            </tr>
                            <tr class="normal_label">
                                <td>Mã hồ sơ</td><td><?=$arrRecord['C_CODE']?></td>
                            </tr>
                            <tr class="normal_label">
                                <td>Ngày tiếp nhận</td><td><?=date('d/m/Y H:i:s', strtotime($arrRecord['C_RECEIVED_DATE']))?></td>
                            </tr>
                            <tr class="normal_label">
                                <td>Ngày hẹn</td><td><?=date('d/m/Y H:i:s', strtotime($arrRecord['C_APPOINTED_DATE']))?></td>
                            </tr>
                            <tr class="normal_label">
                                <td>Cán bộ thụ lý hồ sơ</td><td></td>
                            </tr>
                            <tr class="normal_label">
                                <td>Trạng thái xử lý</td><td><?=$arrRecord['C_CURRENT_STATUS']?></td>
                            </tr>
                        </tbody>
                    </table>

                    <p class="title">Tiến độ giải quyết công việc</p>
                    <table id="table-work" class="list-table-data" cellspacing="0" cellpadding="0" border="0" align="center">
                        <colgroup><col width="5%"><col width="20%"><col width="25%"><col width="25%"><col width="25%"></colgroup>
                        <tbody style="min-width: 500px;">
                            <tr class="header">
                                <td>STT</td>
                                <td>Ngày thực hiện</td>
                                <td>Công việc</td>
                                <td>Kết quả giải quyết</td>
                                <td>Cán bộ thực hiện</td>
                            </tr>
                        <?php
                        $htmls = '';
                        for ($i=0; $i < count($arrRecordWork); $i++) { 
                            $htmls .= '<tr>';
                            $htmls .= '<td data-th="STT">'. ($i+1) .'</td>';
                            $htmls .= '<td data-th="Ngày thực hiện">'.date('d/m/Y H:i:s', strtotime($arrRecordWork[$i]['C_WORK_DATE'])).'</td>';
                            $htmls .= '<td data-th="Công việc">'. $arrRecordWork[$i]['C_WORKTYPE_NAME'] .'</td>';
                            $htmls .= '<td data-th="Kết quả giải quyết">'. $arrRecordWork[$i]['C_RESULT'] .'</td>';
                            $htmls .= '<td data-th="Cán bộ thực hiện">'. $arrRecordWork[$i]['C_POSITION_NAME'] .'</td>';
                            $htmls .= '</tr>';
                        }

                        echo $htmls;
                        ?>    
                            
                        </tbody>
                    </table>
                </div>
            <?php
                } else { ?>
                <p class="sum_message"><?php echo $this->summessage?></p>
                <div class="img_help" style="border: 1px solid #ddd;">
                    <img src="<?php echo $this->baseUrl()?>/public/images/img_content/img_help_tracuu.png">
                </div>
            <?php
                }
            ?>
            </form>
        </div>
       <!--  <div class="cl_right">
            <div class="images">
                <img src="<?php echo $this->baseUrl()?>/public/images/img_content/search_img.png">
            </div>
        </div> -->
    </div>
</div>

<script>
    $('form#frm_search_index').submit(function() {
        if ($('#customer_code').val() == '') {
            $('#customer_code').focus()
            return false;
        }
    })
</script>

<style>
.wrapper_area .main_content .search_result p.title {font-weight: bold;padding-top: 15px;padding-bottom: 5px;}
.wrapper_area .main_content p.sum_message{color: red;font-style: italic;padding-top: 15px;padding-bottom: 5px;}
</style>