<?php
$arrConst = $this->arrConst;
?>
<form action="index" method="POST" id="frmAddList" autocomplete="off">
    <table cellpadding="0" cellspacing="0" width="100%" border="0">
        <!--tao tac hidden!-->
        <tr>
            <!--Sinh mot hidden luu ID loai danh muc!-->
            <?php echo $this->formHidden("hdn_id_listtype", $this->iIdListType, null); ?>
            <!--Sinh mot hidden luu ID danh muc doi tuong!-->
            <?php echo $this->formHidden("hdn_list_id", $this->iIdList, null); ?>
            <!--Bien hdn_xml_tag_list dung de luu danh sach cac THE XML tuong ung voi cac THUOC TINH cua mot doi tuong dang duoc cap nhat-->
            <?php echo $this->formHidden("hdn_xml_tag_list", '', null); ?>
            <!--Bien hdn_xml_value_list dung de luu danh sach cac gia tri cua cac THE XML tuong ung voi cac THUOC TINH cua mot doi tuong-->
            <?php echo $this->formHidden("hdn_xml_value_list", '', null); ?>
            <!--Sinh mot hidden luu list ID ma NSD chon!-->
            <?php echo $this->formHidden("hdn_object_id_list", "", null); ?>
            <!--Hidden luu gia tri cua list tag va list value (TagList|{*^*}|ValueList) -->
            <?php echo $this->formHidden("hdn_XmlTagValueList", $this->XmlTagValueList, null); ?>
            <!--Bien hdn_filter_xml_tag_list dung de luu danh sach cac THE XML tuong ung voi cac tieu thuc loc tren giao dien DANH SACH DOI TUONG-->
            <?php echo $this->formHidden("hdn_filter_xml_tag_list", $this->filterXmlTagList, null); ?>
            <!--Bien hdn_filter_xml_tag_list dung de luu gia tri cua cac THE XML tuong ung voi cac tieu thuc loc tren giao dien DANH SACH DOI TUONG-->
            <?php echo $this->formHidden("hdn_filter_xml_value_list", $this->filterXmlValueList, null); ?>
            <input type="hidden" name="showLeftMenu" id="showLeftMenu"/>
        </tr>
    </table>
    <!--HIen thi tieu de man hinh danh sach!-->
    <table width='100%' border='0' cellspacing='0' cellpadding='0' class="table_title">
        <tr>
            <td class="normal_title" style="padding-left:7px;text-align:left;">
                <?= $this->bodyTitle; ?><br>
            </td>
        </tr>
        <tr>
            <td style="height:10px;"></td>
        </tr>
    </table>
    <?php //var_dump($_SESSION['SesGetAllOwner']);?>
    <div id="contentXml">
        <?php echo $this->generateFormHtml; ?>
    </div>
    <!--Hien thi nut!-->
    <div class="button-container">
        <input name="btn_update" act_event="next" id="btn_update" type="button"
               value="<?= $arrConst['_GHI_THEM_MOI'] ?>" class="link-button clsave">
        <input name="btn_update" act_event="prev" id="btn_update" type="button"
               value="<?= $arrConst['_GHI_QUAY_LAI'] ?>" class="link-button clsave">
        <input name="btn-back" id="btn-back" type="button" value="<?= $arrConst['_QUAY_LAI'] ?>"
               class="link-button clback">
    </div>
</form>
<script>
    var chkAutoGenerateObjectStatus = "<?=$this->chkAutoGenerateObjectStatus;?>";
    if (chkAutoGenerateObjectStatus) {
        document.getElementById('list_name_update').focus();
        var now = new Date();
        var outStr = now.getHours() + '' + now.getMinutes() + '' + now.getSeconds();
        $('#list_code_update').attr("value", '<?=$this->sAutoGenerateObjectCode;?>' + '.' + outStr);
    } else {
        document.getElementById('list_code_update').focus();
    }
</script>