<head>
<script type="text/javascript">
function setFocus(){
	document.getElementById("textsearch").focus();
}
</script>
</head>
<body onload="setFocus();">
<form name="frm_search_result" action="" method="post" autocomplete="on">
	<?php echo $this->formHidden("hdn_id_record","",null); ?>
<table width="100%"%" border="0" align="center" class="menu_top_seach">
	<tr>
		<td width="110px" class="td_menu_top_seach_id" align="left">&nbsp;Nhập mã hồ sơ</td>
		<td width="250px" style=""><input type='text' id='textsearch' name='hdn_id_record' class='td_menu_left_search_id'></td>
		<td ><input type='submit' id='btn_seach' class='td_menu_right_search_id' name='submit' value=''></td>
		<td  class="td_menu_top_time_id" align="center"><SCRIPT language="JavaScript">writeTime();</SCRIPT></td>
	</tr>
</table>
</form>
<?php 
	$arrSeach = $this->arrResult;
	$arrWork = $this-> arrWork;
?>
<table width="100%" border="0" align="center" >
	<tr height="5pt">
		<td colspan="2"></td>
	</tr>
	<tr>
		<td width="100%" colspan="2" class="td_conten_record_tile" style="padding-left:12px;">TH&#212;NG TIN H&#7890; S&#416;</td>
	</tr>
</table>
<table cellpadding="0" cellspacing="0" border="0" width="98%" align="center">
	<tr  height=25pt;>
		<td width="16%" class="td_conten_record_one">M&#227; h&#7891; s&#417;:</td>
		<td width="84%" class="td_conten_record_two"><?= $arrSeach['C_CODE'] ?></td>
	</tr>
	<tr height=25pt;>
		<td width="16%" class="td_conten_record_one">T&#234;n t&#7893; ch&#7913;c, c&#225; nh&#226;n:</td>
		<td width="84%" class="td_conten_record_two"><?= $arrSeach['C_NAME'] ?></td>
	</tr>
	<tr height=25pt;>
		<td width="16%" class="td_conten_record_one">&#272;&#7883;a ch&#7881;:</td>
		<td width="84%" class="td_conten_record_two"><?= $arrSeach['C_ADDRESS'] ?></td>
	</tr>
	<tr height=25pt;>
		<td width="16%" class="td_conten_record_one">Lo&#7841;i h&#7891; s&#417;:</td>
		<td width="84%" class="td_conten_record_two"><?= $arrSeach['C_NAME_RECORDTYPE'] ?></td>
	</tr>
	<tr height=25pt;>
		<td width="16%"class="td_conten_record_one">Ng&#224;y ti&#7871;p nh&#7853;n:</td>
		<td width="84%" class="td_conten_record_two"><?= $arrSeach['C_RECEIVED_DATE'] ?></td>
	</tr>
	<tr height=25pt;>
		<td width="16%" class="td_conten_record_one">Ng&#224;y h&#7865;n tr&#7843; k&#7871;t qu&#7843;:</td>
		<td width="84%" class="td_conten_record_two"><?= $arrSeach['C_APPOINTED_DATE'] ?></td>
	</tr>
	<tr height=25pt;>
		<td width="16%" class="td_conten_record_one2" >Tr&#7841;ng th&#225;i h&#7891; s&#417;:</td>
		<td width="84%" class="td_conten_record_two2"><?= $arrSeach['C_CURRENT_STATUS'] ?></td>
	</tr>
</table>
<table cellpadding="0" cellspacing="0" border="0" width="99%" align="center">
	<tr height=10pt;><td></td></tr>
	<tr >
		<td width="100%"%" colspan="2" class="td_conten_record_tile">&nbsp;TI&#7870;N &#272;&#7896; GI&#7842;I QUY&#7870;T</td>
	</tr>
	<tr>
		<td width="100%" colspan="2">
			<div id="viewAllSentDocument">
			<table cellpadding="0" cellspacing="0" border="0" width="99%" align="center" class="list_table2" id="table1">
				<?php			
				$delimitor = $this->delimitor;//Lay ky tu phan cach giua cac phan tu
				//Hien thi cac cot cua bang hien thi du lieu
					$StrHeader = explode("!~~!", Extra_Util::_GenerateHeaderTable("5%" . $delimitor . "20%" . $delimitor . "30%" . $delimitor . "45%"
													,'STT' . $delimitor ."Ngày thực hiện"  . $delimitor . "Tên công việc" . $delimitor . "Kết quả giải quyết" 
													,$delimitor));
				echo $StrHeader[0];				
				echo $StrHeader[1]; //Hien thi <col width = 'xx'><...		
				//Dinh nghia URL
				$sUrView  = "view";
				$sCurrentStyleName = "round_row";
				for($index = 0;$index < sizeof($arrWork) ;$index++){
					$sPk = $arrWork[$index]['PK_RECORD_WORK'];
				if ($sCurrentStyleName == "odd_row"){
						$sCurrentStyleName = "round_row";
					}else{
						$sCurrentStyleName = "odd_row";					
					}?>		
				<tr   class="<?=$sCurrentStyleName?>"  >	
					<td align="center" style="padding-left:3px;padding-right:3px;" class="normal_label" >					
						<?=$index+1?>			
					</td>
					<td align="center" style="padding-left:3px;padding-right:3px;"  class="normal_label" >
						<?=Extra_Util::_yyyymmddToDDmmyyyy($arrWork[$index]['C_WORK_DATE'])?>
					</td>	
					<td align="left" style="padding-left:3px;padding-right:3px;" class="normal_label"  ><?=$arrWork[$index]['C_WORKTYPE_NAME'] ?></td>
					<td align="left" style="padding-left:3px;padding-right:3px;" class="normal_label" ><?=$arrWork[$index]['C_RESULT']?></td>		
				</tr><?php }
				//Tu dien cac dong trang trong truong hop du lieu tra ve < so row _CONST_NUMBER_OF_ROW_PER_LIST	
				echo Extra_Util::_addEmptyRow(10,15 -sizeof($arrWork),$sCurrentStyleName,4); ?>
			</table>	
		</div>	
		</td>
	</tr>
	<tr height=10pt;><td></td></tr>
</table>
</body>
