<?php
    $myNamespace = new Zend_Session_Namespace('authtoken');
    $myNamespace->setExpirationSeconds(900);
    $myNamespace->authtoken = $hash = md5(uniqid(rand(),1));
    $data = $this->data;
?>
<div id="local_update">
    <div class="head normal_title">DUYỆT TÀI KHOẢN</div>
    <div class="update_area large_area frmxml" style="overflow: hidden;">
        <form id="frm_approve" name="frm_approve" class="item" method="POST" autocomplete = "off">
            <input type="hidden" name="authtoken" value="<?=$hash?>" />
            <input type="hidden" name="ID" value="<?=$data['ID']?>" />
            <div class="frm">
                <div class="row">
                    <label>Họ*</label>
                    <input type="text" id="sFirstName" name="sFirstName" value="<?=$data['sFirstName']?>" class="w25" required />
                    <label class="lb2">Tên*</label>
                    <input type="text" id="sLastName" name="sLastName" value="<?=$data['sLastName']?>" class="w25 normal" required/>
                </div>
                <div class="row">
                    <label>Ngày sinh</label>
                    <input type="text" id="dBirthday" name="dBirthday" value="<?=$data['dBirthday']?>" class="w25"
                           onkeyup="DateOnkeyup(this,event)" date="isdate"/>
                    <label class="lb2">Giới tính</label>
                    <select name="iSex" id="iSex" style="width:26%;" class="normal text_formfield">
                        <option id="" value="" name="">--Chọn giới tính--</option>
                        <option id="male" value="1" name="Nam"  <?php echo ($data['iSex'] == '1' ? 'selected' : '' )?>>Nam</option>
                        <option id="female" value="2" name="Nữ" <?php echo ($data['iSex'] == '2' ? 'selected' : '' )?>>Nữ</option>
                    </select>
                </div>
                <div class="row">
                    <label>Địa chỉ</label>
                    <input type="text" id="sAddress" name="sAddress" value="<?=$data['sAddress']?>" class="w70"/>
                </div>
                
                <div class="row">
                    <label>Số CMND</label>
                    <input type="text" id="sIdCard" name="sIdCard" value="<?=$data['sIdCard']?>" class="w25"/>
                </div>
                <div class="row">
                    <label>Số điện thoại</label>
                    <input type="text" id="sMobile" name="sMobile" value="<?=$data['sMobile']?>" class="w25" required/>
                    <label class="lb2">Email</label>
                    <input type="email" id="sEmail" name="sEmail" value="<?=$data['sEmail']?>" class="w25 normal" required/>
                </div>                
            </div>
        </form>
    </div>
</div>
<style>
    .w25 {
        width: 25%
    }

    .w70 {
        width: 70%
    }
</style>