<script>
    if (typeof(Admin_Account) != 'function') {
        var arrJsCss = $.parseJSON('<?=$this->arrJsCss; ?>');
        loadfileJsCss(arrJsCss);
    }
</script>
<div id="IndexFrm">
    <form action="index" method="POST" id="frmaccount">
        <!--Sinh mot hidden luu list ID ma NSD chon!-->
        <?php
        echo $this->formHidden("hdn_current_page", $this->iCurrentPage, null);
        echo $this->formHidden("hdn_record_number_page", $this->iNumberRecordPerPage, null);
        echo $this->formHidden("hdn_object_id_list", "", null);
        ?>

        <div class="searh-fixed">
            <div class="normal_title">
                <?= $this->bodyTitle; ?>
            </div>
            <!--Màn hình tìm kiếm!-->
            <div class="search-container">
                <table id="table-search">
                    <col width="25%"></col>
                    <col width="10%"></col>
                    <col width="10%"></col>
                    <col width="10%"></col>
                    <col width="15%"></col>
                    <col width="30%"></col>
                    <tr>
                        <td style="text-align: center;">
                            <label class="normal_label" for="fromDate">Ngày đăng ký, Từ ngày</label>
                        </td>
                        <td>
                            <input onchange="ResetSearch()" type="text" id="fromDate" optional="true"
                                   value="01/01/<?= date('Y') ?>" name="fromDate" class="textbox" date="isdate"
                                   onkeyup="DateOnkeyup(this,event)"  style="width: 90%;"/>
                        </td>
                        <td style="padding-left:10px;text-align: center;">
                            <label class="normal_label" for="toDate">Đến ngày</label>
                        </td>
                        <td>
                            <input onchange="ResetSearch()" type="text" id="toDate" optional="true"
                                   value="<?= date('d/m/Y') ?>" name="toDate" class="textbox" date="isdate"
                                   onkeyup="DateOnkeyup(this,event)"  style="width: 90%;"/>
                        </td>

                        <td style="padding-left:10px;text-align: center;">
                            <label class="normal_label" for="fulltextsearch">Từ khóa tìm kiếm</label>
                        </td>
                        <td>
                            <input onchange="ResetSearch()" type="text" id="fulltextsearch" optional="true" value=""
                                   name="fulltextsearch" class="textbox" style="width: 90%;"/>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="button-link-container" align="right">
                <div class="blc-left">
                    <input name="btn_filter" id="btn_filter" type="button" value="Tìm kiếm"
                           class="but_formfield clsearch">

                    <ul class="gr_01" id="tab-menu">
                        <input type="radio" value="CHO_DUYET" name="status" id="choduyet" class="normal_textbox" checked="">
                        <label class="normal_radio" for="choduyet">Chờ duyệt</label>
                        <input type="radio" value="DA_DUYET" name="status" id="daduyet" class="normal_textbox">
                        <label class="normal_radio" for="daduyet">Đã duyệt</label>
                    </ul>
                </div>
                <div class="blc-right">
                    <input name="btn_delete" id="btn_delete" type="button" value="Xóa" class="but_formfield cldelete">
                </div>
            </div>
        </div>
        <!-- Màn hình danh sách -->
        <div id="table-container">
            <table cellpadding="0" cellspacing="0" border="0" align="center" class="list-table-data" id="table-data">
                <?php
                $delimitor = "!~~!";//Lay ky tu phan cach giua cac phan tu
                $StrHeader = explode("!~~!", G_Gen::_GenerateHeaderTable("3%"
                    . $delimitor . "10%"
                    . $delimitor . "15%"
                    . $delimitor . "20%"
                    . $delimitor . "10%"
                    . $delimitor . "34%"
                    . $delimitor . "8%"
                    , '<input optional = "true" type="checkbox" name="chk_all_item_id" value="" onclick="checkbox_all_item_table(this,\'chk_item_id\');">'
                    . $delimitor . 'Ngày đăng ký'
                    . $delimitor . 'Tài khoản'
                    . $delimitor . 'Họ tên'
                    . $delimitor . 'Số điện thoại'
                    . $delimitor . 'Địa chỉ'
                    . $delimitor . 'Tác vụ'
                    , $delimitor));
                echo $StrHeader[0];
                echo G_Gen::_addEmptyRow($this->iCountElement, 15, 'odd_row', 7);
                ?>
            </table>
        </div>
        <table class="table-page-number" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td class="left-col small_label" valign="top">
                    <small class="small_starmark" id="sdocpertotal"></small>
                </td>
                <td class="center-col" align="center" id="generateStringNumberPage"></td>
                <td class="right-col normal_label" id="generateHtmlSelectBoxPage">
                Hiển thị 
                <select class="textbox" id="cbo_nuber_record_page" name="cbo_nuber_record_page" optional="true" style="width:60">
                    <option value="15">15</option>
                    <option value="50">50</option>
                    <option value="100">100</option>
                    </select>Hồ sơ/1 trang
                </td>
            </tr>
        </table>
        <!-- Các tùy chọn -->
        <div class="button-container">
            <input name="btn_delete" id="btn_delete" type="button" value="Xóa" class="but_formfield cldelete">
        </div>
    </form>
</div>
<div id="modal_info" class="modal_info"></div>
<script type="text/javascript">
    if (typeof(Admin_Account) === 'function') {
        var objAdmAccount = new Admin_Account(baseUrl, 'admin', 'account');
    }

    $('form#frmaccount').process_paging({
        getData: function (callback) {
            objAdmAccount.ldmod(callback);
        },
        obj: objAdmAccount
    });
    objAdmAccount.loadIndex();
</script>
<style type="text/css">
    div#form-content div label {
        float: left;
    }
    #tab-menu label.normal_radio {padding-left: 3px}
</style>