<div id="note-process" class="vY nq" style="display: none;">
    <div id="load_data">
        <img src="<?= $this->baseUrl() ?>/public/images/ajax-loader1.gif"><br>

        <div class="txtloading">Đang tải dữ liệu</div>
    </div>
    <div id="file_export">
        <div title="Tên file bao gồm ngày, tháng, năm, giờ, phút giây" class="file_export-title"></div>
        <a class="file_export-icon"></a>

        <p class="file_export_close"></p>
    </div>
    <div id="smallLoadIcon"></div>
    <div id="fade"></div>
    <div id="modalnotify">
        <img id="loader" src="<?= $this->baseUrl() ?>/public/images/img_skin/loading.gif" />
    </div>
</div>