<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>HE THONG PHAN MEM MOT CUA DIEN TU</title>
<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl?>style/style.css">
<?= $this->JSPublicConst;?>
<script src="<?= $this->baseUrl?>js/util.js" type="text/javascript"></script>
<?php
	echo $this->LoadAllFileJsCss;
?>
</head>
<body topmargin="0" leftmargin="0" marginheight="0" marginwidth="0" rightmargin="0" width="100%">
 <?php
 if($this->currentModulCode != "RECORD-NET"){?>
	<div id="searchrecordresult">
    <table width="100%" border="0" cellpadding="0" cellspacing="0"  height="100%" align="center">
        <tr>
			<td valign="top">
				<table width="100%" cellpadding="0" cellspacing="0"  align="center" id="header">
					  <tr>
							<?
							if ($this->hideDisplayMenuHeader != ""){?>
		    					<td colspan="10" width="20%" valign="top" bgcolor="#fff8e3" style="display:none">
									<?=$this->layout()->header;?>								</td>
		    				<?}else{?>
		    					<td  colspan="10" width="5%" valign="top">
									<?=$this->layout()->header;?>
								</td>
		    				<?}?>		
					  </tr>
					  <tr>
					    <td width="100%" valign="top" >
					    	<table  width="100%" cellpadding="0" cellspacing="0" class="body1" border="0">
					    		<tr>
				    				<td  width="100%" style="background:#fff;" valign="top">
					    				<?=$this->layout()->content;?>
					    			</td>
					    		</tr>						    		
					    	</table>		    	
						</td>
					  </tr>
					  <tr>
							<?
							if ($this->hideDisplayMenuFooter != ""){?>
		    					<td colspan="10" width="20%" valign="top" bgcolor="#fff8e3" style="display:none">
									<?=$this->layout()->footer;?>
								</td>
		    				<?}else{?>
		    					<td  colspan="10" width="5%" valign="top">
									<?=$this->layout()->footer;?>
								</td>
		    				<?}?>
				      </tr>					
				</table>
			</td>
		</tr>
	</table>
    </div><?php
}?>
	<SCRIPT type="text/javascript"> 
	</SCRIPT>
</body>
</html>
