<form action="index " method="POST" autocomplete="off" name="formreceive" id="formreceive">
    <div id='divList'><?php
        $arrConst = $this->arrConst;
        $arrRecordType = $this->arrRecordType;
        //var_dump($arrRecordType);
        ?>
        <table width='100%' border='0' cellspacing='0' cellpadding='0' class="table_title">
            <tr>
                <td class="large_title" style="padding-left:7px;text-align:left;">
                    <!--Cac doi tuong hidden tren form-->
                    <?php echo $this->formHidden("hdn_current_page", $this->iCurrentPage, null); ?>
                    <?php echo $this->formHidden("cbo_nuber_record_page", $this->iNumRowOnPage, null); ?>
                    <?php echo $this->formHidden("hdn_record_number_page", $this->iNumRowOnPage, null); ?>
                    <?php echo $this->formHidden("hdn_object_id_list", "", null); ?>
                    <?php echo $this->formHidden("hdn_list_id", "", null); ?>
                    <?php echo $this->formHidden("hdn_filter_xml_tag_list", $this->filterXmlTagList, null); ?>
                    <?php echo $this->formHidden("hdn_filter_xml_value_list", $this->filterXmlValueList, null); ?>
                    <?php echo $this->formHidden("hdn_object_id", '', null); ?>
                    <?php echo $this->formHidden("hdn_XmlTagValueList", $this->XmlTagValueList, null); ?>
                    <!-- Tim kiem -->
                    <?php echo $this->formHidden("txtfullTextSearch", "", null); ?>
                    <!-- Trang thai-->
                    <?php echo $this->formHidden("hdn_status", $this->sStatus, null); ?>
                    <!-- ID TTHC -->
                    <?php echo $this->formHidden("recordType", $this->sRecordTypeId, null); ?>
                    <!--Cac doi tuong hidden tren form-->
                    <?= $this->bodyTitle; ?>
                </td>
            </tr>
        </table>

        <?php echo $this->filter_form; ?>
        <div style="text-align:right; width:99%;margin: 0 5px 5px;">
            <label>
                <a class="add_large_button process"><?= $arrConst['_CHUYEN_XU_LY'] ?></a>
                <a class="add_large_button submitorder"><?= $arrConst['_TRINH_KY'] ?></a>
                <a class="add_large_button"
                   onclick="btn_update_onclick(document.getElementsByName('chk_item_id'),'../license/index'); "><?= $arrConst['_CAP_NHAT_ND_GIAY_PHEP'] ?></a>
            </label>
        </div>
        <?php echo $this->genlist; ?>
        <!--Hien thi trang can xem!-->
        <table style="padding-bottom: 20px;padding-top: 12px;" width="100%" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td style="color:red;width:30%;padding-left:1%;" class="small_label">
                    <small class="small_starmark"><?= $this->sdocpertotal; ?></small>
                </td>
                <td align="center" style="width=" 50%
                ">
                <table width="10%"><?php echo $this->generateStringNumberPage; ?></table>
                </td>
                <td width="30%" align="right" style="font-size:13px; padding-right:1%; font:tahoma"
                    class="normal_label"><?php echo $this->generateHtmlSelectBoxPage; ?></td>
            </tr>
        </table>
    </div>
    <div id="loadingViewDetailsRecord" class="small_link" style="display:none;height:20px;">
        <img src="<?= $this->baseUrl() ?>/public/images/searching.gif" style="vertical-align: middle;"> Loading...
    </div>
    <div id='divViewDetailsRecord'>
    </div>
</form>
<script type="text/javascript">
    var baseUrl = "<?=$this->baseUrl();?>";
    var obj_record_handle = new record_handle(baseUrl, 'record', 'handle');
    jQuery(document).ready(function ($) {
        obj_record_handle.loadIndex();
    });
</script>