<?php
$objrecordfun = new Efy_Function_RecordFunctions();
$sRecordIdList = $this->sRecordIdList;
$arrinfoRecordType = $this->arrinfoRecordType;
$sLeaderList = $arrinfoRecordType['C_APPROVE_LEADER_ID_LIST'];
//$sRoleList = $arrinfoRecordType['C_ROLES_CODE_LIST'];
$arrLeader = explode(',',$sLeaderList);
//$arrRole = explode(',',$sRoleList);
$icount = sizeof($arrLeader);
$check = '';
if($icount===1){
    $check = 'checked="checked"';
}
$sUnitId = $objrecordfun->_get_item_attr_by_id($_SESSION['arr_all_staff'],$_SESSION['staff_id'],'unit_id');
?>
<form action="index" method="POST" id="frmSubmitorder" autocomplete="off" enctype="multipart/form-data">
    <?php echo $this->formHidden("hdn_record_id_list",$this->sRecordIdList,null); ?>
    <!--Bien hdn_deleted_new_file_id_list dung de luu Id cua nhung doi tuong file dinh kem se xoa-->
    <?php echo $this->formHidden("hdn_deleted_new_file_id_list","",null); ?>
    <!--Bien hdn_deleted_exist_file_id_list dung de ...-->
    <?php echo $this->formHidden("hdn_deleted_exist_file_id_list","",null); ?>
    <?php echo $this->formHidden("hdn_update","1",null); ?>

    <div style="width: 99%;padding-left: 5px;">
        <div class="normal_title">DANH SÁCH HỒ SƠ TRÌNH DUYỆT</div>
        <div class="general_information" id="general_information">
            <?=$this->general_information?>
        </div>
        <div class="normal_title">NỘI DUNG TRÌNH</div>
        <div id="contentXml" style="margin: 0;">
            <div id="header_update_form">
                <div style="padding-top: 15px;">
                    <label>Lãnh đạo duyệt<span class="requiein">*</span></label>
                    <div style="display: inline-block;width: 75%;">
                        <?
                        foreach($arrLeader as $key => $sleaderid) {
                            $sleadername = $objrecordfun->getNamePositionStaffByIdList($sleaderid);
                            $sunitid = $objrecordfun->_get_item_attr_by_id($_SESSION['arr_all_staff'], $sleaderid,'unit_id');
                            if($sunitid==$sUnitId) {
                                ?>
                                <div style="display: inline-block;width: 100%;">
                                    <input style="float: left;" type="radio" class="normal_radiobutton"
                                           value="<?= $sleaderid; ?>" <?= $check ?> name="chk_leader"
                                           id="chk_leader<?= $key; ?>">
                                    <label style="float: left;padding-left: 5px;" for="chk_leader<?= $key; ?>"
                                           class="normal_label"><?= $sleadername; ?> </label>
                                </div>
                            <?
                            }
                        }
                        ?>
                    </div>
                </div>
                <div style="padding-top: 15px;">
                    <label>Ý kiến<span class="requiein">*</span></label>
                    <textarea style="width:70%;font-family: arial;font-size: 10pt;" name="idea" id="idea" class="normal_textarea">Trình lãnh đạo duyệt hồ sơ!</textarea>
                </div>
                <div style="padding-top: 15px;">
                    <label>File đính kèm</label>
                    <div style="display: inline-block;width: 75%;"><?php echo $this->AttachFile;?></div>
                </div>
                <div id="clear"></div>
            </div>
        </div>
    </div>
    <div style="width: 99%;padding-top: 12px;text-align: center;">
        <input type="button" style="margin-left:0px;" name="btnSubmit" id="btnSubmit" value="Cập nhật" class="add_large_button">
        <input type="button" style="margin-left:0px;" name="btnback" id="btnback" value="Quay lại" class="add_large_button">
    </div>
</form>
<script type="text/javascript">
    var baseUrl = "<?=$this->baseUrl();?>";
    var obj_record_handle = new record_handle(baseUrl, 'record', 'handle');
    jQuery(document).ready(function ($) {
        obj_record_handle.loadSubmitorderEven('index');
    });
</script>