<form action="index" method="POST" id="mailresult" enctype="multipart/form-data" autocomplete="off">
<?php
	$arrConst = $this->arrConst;
	$arrMailRecordList = $this->arrMailRecordList;
?>
	<table cellpadding="0" cellspacing="0" width="100%" border="0">
		<!--tao tac hidden!-->
		<tr>
			<td>
				<?php echo $this->formHidden("hdn_xml_tag_list","",null); ?>
				<?php echo $this->formHidden("hdn_xml_value_list","",null); ?>
				<?php echo $this->formHidden("hdn_XmlTagValueList","",null); ?>
				<!--Sinh mot hidden luu ID HS!-->
				<?php echo $this->formHidden("hdn_object_id",$this->sRecordPk,null); ?>		
				<!--Bien hdn_deleted_new_file_id_list dung de luu Id cua nhung doi tuong file dinh kem se xoa-->	
				<?php echo $this->formHidden("hdn_deleted_new_file_id_list","",null); ?>	
				<!--Bien hdn_deleted_exist_file_id_list dung de ...-->	
				<?php echo $this->formHidden("hdn_deleted_exist_file_id_list","",null); ?>					 
				<?php echo $this->formHidden("hdh_option","",null); ?>	
				<?php echo $this->formHidden("recordType",$this->recordType,null); ?>
			</td>
		</tr>
	</table>
	<!--HIen thi tieu de man hinh danh sach!-->
	<div id ="contentXml">
        <div style="margin:auto;padding:10px 5px;width:98%;">
			<div class = 'large_title' style='padding-left: 1px; text-align: left; float: left;'><?=$arrConst['_THONG_TIN_HS']?></div>
            <?=$this->general_information;?>
		</div>
		<div id ="content">
			<div id="header_conten" style="height:20px;">
				<div class="large_title" style="padding-left:1px;text-align:left;float:left;"> <?=$this->bodyTitle;?> </div>
			</div>
			<?php 
				$i = 0;
				foreach ($arrMailRecordList as $arrMailRecord){ ?>
			<div id="body_conten1" style="padding-top:5px;">			
				<div class='normal_label'>
					<label>&nbsp;<?=$arrConst['_MA_HO_SO']?></label>
					<?= $arrMailRecord['code']?>
				</div>
				<div>
					<label>&nbsp;<?=$arrConst['_DIA_CHI']?> email</label>
					<input style="width:30%"  type="text" class="textbox normal_textarea" id="mail_<?=$i?>"  name="mail_<?=$i?>" optional = "true"  value="<?= $arrMailRecord['email_nk']?>" >
				</div>
				<div >
					<label>&nbsp;<?=$arrConst['_THONG_BAO']?></label>
					<textarea  style="width:67%"  class="textbox normal_textarea" id="note_<?=$i?>" name="note_<?=$i?>" optional = "true" rows="2" >K/g: Ông(bà): <?= $arrMailRecord['registor_name']?>; Địa chỉ: <?= $arrMailRecord['registor_address']?>. Hồ sơ <?=$this->sRecordTypeName?> của ông/bà đã được giải quyết</textarea>
				</div>
			</div>
			<?php 
			$i = $i +1;
			}?>
		</div>
	</div>	
	<!--Hien thi nut!-->				
	<table 	width='99%'  border='0' cellspacing='0' cellpadding='0' align="center" class="table_title">		
		<tr>
			<td align="center">	
				<?=$this->formButton("btn_update",$arrConst['_GHI'],array("type"=>"button","class"=>"add_large_button","onClick"=>"document.getElementById('hdh_option').value='GHI',btn_save_result(document.getElementsByName('hdn_xml_tag_list'),document.getElementsByName('hdn_xml_value_list'),'');"))?>								
				<?=$this->formsubmit('button',$arrConst['_QUAY_LAI'],array("onClick"=>"document.getElementById('hdh_option').value='QUAY_LAI',actionUrl('../wreceive/result');","class"=>"add_large_button"))?>
			</td>
		</tr>			
	</table>	
</form>
