<form action="index" method="POST" id="formreceive" autocomplete="off">
	<!--Cac doi tuong hidden tren form-->
	<?php echo $this->formHidden("hdn_current_page",$this->iCurrentPage,null); ?>
	<?php echo $this->formHidden("cbo_nuber_record_page",$this->iNumRowOnPage,null); ?>
	<?php echo $this->formHidden("hdn_record_number_page",$this->iNumRowOnPage,null); ?>
	<?php echo $this->formHidden("hdn_object_id_list","",null); ?>
    <?php echo $this->formHidden("hdn_object_id",$this->pSendReceiveDocumentId,null); ?>
	<?php echo $this->formHidden("hdn_list_id","",null); ?>
	<?php echo $this->formHidden("hdn_filter_xml_tag_list",$this->filterXmlTagList,null); ?>
	<?php echo $this->formHidden("hdn_filter_xml_value_list",$this->filterXmlValueList,null); ?>
	<?php echo $this->formHidden("hdn_XmlTagValueList",$this->XmlTagValueList,null); ?>
	<?php echo $this->formHidden("p_hidden_obj","",null);?>
	<?php
		$arrConst = $this->arrConst;
		$sUrlEdit  = "../edit/";
	?>
	<div class = "large_title">
		<?=$this->titleBody;?>
	</div>
	<?php echo $this->filter_form;?>
	<?php echo $this->genlist;?>
	<!--Hien thi trang can xem!-->
	<table style="padding-bottom: 20px;padding-top: 12px;" width="100%" cellpadding="0" cellspacing="0" border="0">
		<tr><td style="color:red;width:30%;padding-left:1%;" class="small_label"><small class="small_starmark"><?=$this->sdocpertotal;?></small></td>
			<td align="center" style="width="50%"><table width="10%"><?php echo $this->generateStringNumberPage;?></table></td>
			<td width="30%" align="right" style="font-size:13px; padding-right:1%; font:tahoma" class="normal_label"><?php echo $this->generateHtmlSelectBoxPage;?></td>
		</tr>
	</table>
</form>
<div id = "div_ajax" style = "display:none;"></div>