<form action="index" method="POST" id="approve" enctype="multipart/form-data" autocomplete="off">
<?php 
	$urlCalendar = $this->urlCalendar;
	$arrConst = $this->arrConst; 
?>
	<table cellpadding="0" cellspacing="0" width="100%" border="0">
		<!--tao tac hidden!-->
		<tr>
			<td>
				<?php echo $this->formHidden("hdn_xml_tag_list","",null); ?>
				<?php echo $this->formHidden("hdn_xml_value_list","",null); ?>
				<?php echo $this->formHidden("hdn_XmlTagValueList","",null); ?>
				<!--Sinh mot hidden luu ID HS!-->
				<?php echo $this->formHidden("hdn_object_id",$this->sRecordPk,null); ?>		
				<!--Bien hdn_deleted_new_file_id_list dung de luu Id cua nhung doi tuong file dinh kem se xoa-->	
				<?php echo $this->formHidden("hdn_deleted_new_file_id_list","",null); ?>	
				<!--Bien hdn_deleted_exist_file_id_list dung de ...-->	
				<?php echo $this->formHidden("hdn_deleted_exist_file_id_list","",null); ?>					 
				<?php echo $this->formHidden("hdh_option","",null); ?>	
				<?php echo $this->formHidden("recordType",$this->recordType,null); ?>
			</td>
		</tr>
	</table>
	<!--HIen thi tieu de man hinh danh sach!-->
	<div style="height:3px;"></div>
	<div id ="contentXml">
		<div style="margin:auto;padding:10px 5px;width:98%;"><?php echo Extra_Ecs::eCSRecordBasicGetSingle($this->sRecordPk,$this->iFkUnit,$this->sOwnerCode);?></div>
		<div id ="content">
			<div id="header_conten" style="height:20px;">
				<div class="large_title" style="padding-left:1px;text-align:left;float:left;"> <?=$this->bodyTitle;?> </div>
			</div>
			<div id="body_conten1" style="padding-top:5px;">
				<div>
					<label>&nbsp;<?=$arrConst['_NGAY_TKQ']?><span class="requiein">*</span></label> 
					<input style="width:15%" class="textbox" id ="C_RESULT_DATE" name="C_RESULT_DATE" type="text" isdate="true" value="<?=date('d/m/Y')?>" option = "true"  xml_tag_in_db="" xml_data="false" column_name="C_RESULT_DATE" message="NGAY TRA KET QUA khong dung dinh dang ngay/thang/nam!" onKeyDown="change_focus(document.forms[0],this)">						 					
				</div>				
				<div>
					<label>&nbsp;<?=$arrConst['_HO_TEN_CONG_DAN']?><span class="requiein">*</span></label>
					<input style="width:67%"  type="text" class="textbox normal_textarea" id="C_REGISTOR_NAME" option = "false"  name="C_REGISTOR_NAME" message="Phai xac dinh TEN CONG DAN TO CHUC!" value="<?=$this->sRegistorName?>" onchange="set_upcase_value(this);">

				</div>
				<div class="normal_label">
					<label>&nbsp;<?=$arrConst['_LE_PHI']?></label>
					<input style="width:15%"  type="text" class="textbox normal_textarea" id="C_COST"  name="C_COST" optional = "true"  value="<?=$this->sMoneyNo?>" onkeyup="AddComma(this,event);"> đồng 
					<div  style="float:right;padding-right:100px;">(Lệ phí đã nộp:  <?=$this->sMoneyYes?> đồng) </div>
				</div>
				<div >
					<label>&nbsp;<?=$arrConst['_GHI_CHU']?></label>
					<textarea  style="width:67%;"  class="textbox normal_textarea" id="C_REASON" name="C_REASON" optional = "true" rows="2" ></textarea>
				</div>
			</div>
		</div>
	</div>	
	<!--Hien thi nut!-->				
	<table 	width='99%'  border='0' cellspacing='0' cellpadding='0' align="center" class="table_title">		
		<tr>
			<td align="center">	
				<?=$this->formButton("btn_update",$arrConst['_GHI'],array("type"=>"button","class"=>"add_large_button","onClick"=>"document.getElementById('hdh_option').value='GHI',btn_save_result(document.getElementsByName('hdn_xml_tag_list'),document.getElementsByName('hdn_xml_value_list'),'');"))?>								
				<?=$this->formsubmit('button',$arrConst['_QUAY_LAI'],array("onClick"=>"document.getElementById('hdh_option').value='QUAY_LAI',actionUrl('../wreceive/result');","class"=>"add_large_button"))?>
			</td>
		</tr>			
	</table>	
</form>
<script type="text/javascript">
$(function() {
	$("#C_RESULT_DATE").datepicker({
	changeMonth: true,
	gotoCurrent: true,
	minDate: new Date(1945, 1 - 1, 1),
	changeYear: true
	});	
});
</script>