<form action="" method="POST" enctype="multipart/form-data" autocomplete="off">
    <?php
    $arrConst = $this->arrConst;
    $arrWork = $this->arrWork;
    $ojbEfyLib	= new Efy_Library();
    ?>
    <!--HIen thi tieu de man hinh danh sach!-->
    <div style="height:3px;"></div>
    <div id ="contentXml">
        <div style="margin:auto;padding:10px 5px;width:98%;">
            <?php
            echo $this->generalhtmlinfo;
            ?>
        </div>

        <div class="large_title" style="padding-left:10px;text-align:left;float:left;">THÔNG TIN QUÁ TRÌNH XỬ LÝ</div>
        <table width='99%'  border='0' cellspacing='0' cellpadding='0' class="table_title">
            <tr>
                <td style="text-align:RIGHT;padding-left:8px;" valign="bottom">
                </td>
            </tr>
        </table>
        <div id="viewAllSentDocument">
            <table cellpadding="0" cellspacing="0" border="0" width="98%" align="center" class="list_table2" id="table1">
                <?php
                $delimitor = '!~~!';
                $StrHeader = explode($delimitor, $ojbEfyLib->_GenerateHeaderTable("16%" . $delimitor . "18%" . $delimitor . "23%" . $delimitor . "21%". $delimitor . "23%"
                    ,$arrConst['_NGAY_THUC_HIEN']  . $delimitor . $arrConst['_CONG_VIEC'] . $delimitor . $arrConst['_KQ_GIAI_QUYET'] . $delimitor . $arrConst['_CAN_BO_THUC_HIEN']. $delimitor . $arrConst['_DON_VI']
                    ,$delimitor));
                echo $StrHeader[0].$StrHeader[1];
                //Dinh nghia URL
                $sUrView  = "view";
                $sCurrentStyleName = "round_row";
                for($index = 0;$index < sizeof($arrWork) ;$index++){
                    $sPk = $arrWork[$index]['PK_RECORD_WORK'];
                    $iUnitId = Efy_Function_RecordFunctions::GetUnitIdListFromStaffIdList($arrWork[$index]['FK_STAFF'],$_SESSION['arr_all_staff_keep']);
                    $sUnitName = Efy_Function_RecordFunctions::getNameUnitByIdUnitList($iUnitId,'arr_all_unit_keep');
                    //lay file dinh kem
                    $strFileName = $arrWork[$index]['C_FILE_NAME'];
                    $sFile = '';
                    if(trim($strFileName) != '') $sFile = $ojbEfyLib->_getAllFileAttach($strFileName,"!#~$|*","!~!",$this->baseUrl . "attach-file/");
                    if ($sCurrentStyleName == "odd_row"){
                        $sCurrentStyleName = "round_row";
                    }else{
                        $sCurrentStyleName = "odd_row";
                    }?>
                <tr class="<?=$sCurrentStyleName?>">
                    <td align="center" style="padding-left:3px;padding-right:3px;"  class="normal_label" ><?=$ojbEfyLib->_yyyymmddToDDmmyyyyhhmm($arrWork[$index]['C_WORK_DATE'])?></td>
                    <td align="left" style="padding-left:3px;padding-right:3px;" class="normal_label"  ><?=$arrWork[$index]['C_WORKTYPE_NAME'] ?></td>
                    <td align="left" style="padding-left:3px;padding-right:3px;" class="normal_label" ><?=  $arrWork[$index]['C_RESULT'].' '.$sFile ?></td>
                    <td align="left" style="padding-left:3px;padding-right:3px;" class="normal_label" ><?= $arrWork[$index]['C_POSITION_NAME'] ?></td>
                    <td align="left" style="padding-left:3px;padding-right:3px;" class="normal_label" ><?= $sUnitName ?></td>
                    </tr><?php } ?>
            </table>
        </div>
        <table width='100%'  border='0' cellspacing='0' cellpadding='0' align="center">
            <tr>
                <td style="padding-top: 15px; padding-bottom: 5px;" align="center" valign="middle">
                    <input id="btn_add" name="btn_add" type="button" class="add_large_button" value="<?= $arrConst['_QUAY_LAI']?>" onclick="history.back(-1);">
                </td>
            </tr>
        </table>
    </div>
</form>