<div id="IndexFrm">
    <form id="frmreminder_index" accept-charset="utf-8" method="" action="">
        <?php
        echo $this->formHidden("hdn_current_page", $this->iCurrentPage, null);
        echo $this->formHidden("hdn_record_number_page", $this->iNumberRecordPerPage, null);
        ?>
        <?= $this->htmlRss; ?>
        <div id="reminder_cancel"></div>
    </form>
</div>
<div id="UpdateFrm" style="display: none"></div>
<div class="modal_tempo"></div>
<script type="text/javascript">
    baseUrl = "<?=$this->baseUrl();?>";
    $('body').find('input[date="isdate"]').each(function () {
        $(this).datepicker({
            changeMonth: true,
            gotoCurrent: true,
            minDate: new Date(1945, 1 - 1, 1),
            changeYear: true
        });
    })
    var d = new Date();
    var dd = d.getDate();
    var mm = d.getMonth() + 1;
    if (dd < 10) {
        dd = '0' + dd
    }
    if (mm < 10) {
        mm = '0' + mm
    }
    $('#txtFromDate').val('01/01/' + d.getFullYear());
    $('#txtToDate').val(dd + '/' + mm + '/' + d.getFullYear());
    createModalDialog("div.modal_tempo", function () {
        $("div.modal_tempo").dialog({
            autoOpen: false,
            title: 'THÔNG TIN TIẾN ĐỘ GIẢI QUYẾT CỦA HỒ SƠ',
            modal: true,
            resizable: true,
            width: document.documentElement.clientWidth * 0.9,
            height: document.documentElement.clientHeight * 0.8,
            autoResize: false,
            dialogClass: 'dialog-class',
            draggable: true,
            overlay: {
                opacity: 0.5,
                background: 'blue'
            },
            buttons: [
                {
                    text: "Quay lại",
                    click: function () {
                        $(this).dialog("close");
                    }
                }
            ]
        });
    })
    function viewtempo_cancel(obj) {
        var url = baseUrl + '/main/ajax/viewtempo/';
        var myClass = this;
        var oCheckbox = $(obj).parent().parent().find('input[type="hidden"][name="chk_item_id"]');
        $(oCheckbox).attr('checked', true);
        var pkrecord = $(oCheckbox).val();
        var data = {
            pkrecord: pkrecord
        };
        $.ajax({
            url: url,
            type: 'POST',
            data: data,
            success: function (string) {
                $('div.modal_tempo').html(string);
                hideloadpage();
                $(".modal_tempo").dialog("open");
            },
            beforeSend: showloadpage()
        });
        return !history.pushState;
    }

    function reminderCancel() {
        $('div#reminder_cancel').remove();
        var url = baseUrl + '/main/ajax/reminderCancel';
        if (this.loadding)  return false;
        var oForm = $('form#form-reminder-right');
        var data = $(oForm).serialize();
        var fromDate = $('input#txtFromDate').val();
        var toDate = $('input#txtToDate').val();
        data += '&fromDate=' + fromDate;
        data += '&toDate=' + toDate;
        $.ajax({
            url: url,
            type: "POST",
            data: data,
            success: function (htmlstring) {
                $('div#reminder-content-right').append(htmlstring);
            }
        })
    }
</script>