<div class="row_01">
	<div class="header">
		<p class="title">
			Dịch vụ công trực tuyến UBND huyện Lệ Thủy
		</p>
	</div>
	<div class="content">
		<p>
			Hệ thống dịch vụ công trực tuyến UBND Huyện Lệ Thủy - Quảng Bình là hệ thống thông tin thực hiện dịch vụ "một cửa" cho công dân, doanh nghiệp và cán bộ.
		</p>
		<p>
			Công dân, doanh nghiệp sau khi đăng nhập bằng tài khoản đã được đăng ký có thể thực hiện các dịch vụ hành chính công một cách đơn giản và thuận tiện. Công dân, doanh nghiệp quản lý được hồ sơ cá nhân (thông tin cá nhân, giấy tờ số) và toàn bộ các giao dịch với cơ quan nhà nước thông qua việc nộp, theo dõi tình hình xử lý và nhận kết quả xử lý hồ sơ thực hiện dịch vụ hành chính công trực tiếp tại bộ phận một cửa hoặc trực tuyến tại Hệ thống dịch vụ công trực tuyến UBND Huyện Lệ Thủy - Quảng Bình. Ngoài ra, công dân và doanh nghiệp còn dễ dàng khai thác các dịch vụ công.
		</p>
		<p>
			Cán bộ có thể theo dõi, tổng hợp các báo cáo về tình hình tiếp nhận và giải quyết hồ sơ của công dân và doanh nghiệp.
		</p>
		
		<div class="image_about">
			<img src="<?=$this->baseUrl()?>/public/images/img_content/cau_le_thuy.jpg">
		</div>
	</div>
</div>