<div class="row_01">
							
	<div class="content">
		<div class="cl_left">								
			<div class="row_01">
				<p class="title">
					Hướng dẫn
				</p>
				<ul>
					<li class="active">
						<a href="">Đăng ký tài khoản công dân</a>
					</li>
					<li class="">
						<a href="">Đổi mật khẩu</a>
					</li>
					<li class="">
						<a href="">Công dân sử dụng dịch vụ công trực tuyến</a>
					</li>
					<li class="">
						<a href="">Công dân quản lý hồ sơ các dịch vụ công</a>
					</li>
					
				</ul>
				
			</div>
			<div class="row_02">
				<p class="title">
					Videos Hướng dẫn
				</p>
				<ul>
					<li class="">
						<a href="">Đăng ký tài khoản công dân</a>
					</li>
					<li class="">
						<a href="">Tạo hồ sơ và gửi hồ sơ</a>
					</li>
					<li class="">
						<a href="">Sử dụng điện thoại chụp các tài liệu đính kèm</a>
					</li>
					
					
				</ul>
				
			</div>
		</div>
		<div class="cl_right">
			<div class="content">
				<p class="header">
					Đăng ký tài khoản
				</p>
				<div class="help_content_detail">
					<ul>
						<li>
							<div class="cl_left">
								<span class="number">
									1
								</span>
							</div>
							<div class="cl_right">													
								<span class="text">
									Công dân chọn và click vào Đăng ký trên Trang chủ của Hệ thống, sau đó nhập đầy đủ các thông tin: Họ tên, ngày sinh, số CMND và địa chỉ email. Tiếp theo click vào Đăng ký tài khoản.
								</span>
							</div>
						</li>
						<li>
							<div class="cl_left">
								<span class="number">
									2
								</span>
							</div>
							<div class="cl_right">													
								<span class="text">
									Hệ thống kiểm tra các thông tin công dân nhập vào và yêu cầu hoàn thành nhập bổ sung thêm các thông tin chi tiết.
								</span>
							</div>
						</li>
						<li>
							<div class="cl_left">
								<span class="number">
									3
								</span>
							</div>
							<div class="cl_right">													
								<span class="text">
									Hệ thống gửi mail vào địa chỉ email công dân đăng ký và yêu cầu kích hoạt, công dân click theo link hướng dẫn.
								</span>
							</div>
						</li>
						<li>
							<div class="cl_left">
								<span class="number">
									4
								</span>
							</div>
							<div class="cl_right">													
								<span class="text">
									Sau khi tài khoản được xác thực, công dân sử dụng tài khoản này để thực hiện các Dịch vụ công trực tuyến trên Hệ thống.
								</span>
							</div>
						</li>
					</ul>
					<div class="download_documents">
						<a href="" class="btn btn_download">Tải tài liệu đính kèm</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	
</div>