<form action="" method="POST" id="formreceive" autocomplete="off">
	<!--Cac doi tuong hidden tren form-->
	<?php echo $this->formHidden("hdn_current_page",$this->iCurrentPage,null); ?>
	<?php echo $this->formHidden("cbo_nuber_record_page",$this->iNumRowOnPage,null); ?>
	<?php echo $this->formHidden("hdn_record_number_page",$this->iNumRowOnPage,null); ?>
	<?php echo $this->formHidden("hdn_object_id_list","",null); ?>
	<?php echo $this->formHidden("hdn_list_id","",null); ?>
	<?php echo $this->formHidden("hdn_filter_xml_tag_list",$this->filterXmlTagList,null); ?>
	<?php echo $this->formHidden("hdn_filter_xml_value_list",$this->filterXmlValueList,null); ?>
	<?php echo $this->formHidden("hdn_object_id",$this->pSendReceiveDocumentId,null); ?>
	<?php echo $this->formHidden("hdn_XmlTagValueList",$this->XmlTagValueList,null); ?>
	<!--Bien hdn_deleted_new_file_id_list dung de luu Id cua nhung doi tuong file dinh kem se xoa-->	
	<?php echo $this->formHidden("hdn_deleted_new_file_id_list","",null); ?>	
	<!--Bien hdn_deleted_exist_file_id_list dung de ...-->	
	<?php echo $this->formHidden("hdn_deleted_exist_file_id_list","",null);?>
	<?php
		$arrConst = $this->arrConst;
		$sUrlEdit  = "../edit/";
	?>
	<div class = "large_title">
		<?=$this->titleBody;?>				
	</div>
	<?php echo $this->filter_form;?>
	<table width='99%'  border='0' cellspacing='0' cellpadding='0' class="table_title">
		<col width="85%" align="left"/><col width="15%" align="right"/>
		<tr>
			<td align="right" colspan="2">
				<div style="text-align:right; width:98%;">
					<label>
							<a   class="small_link"  onclick="btn_update_onclick(document.getElementsByName('chk_item_id'),'../orderonnet/viewrecord')">  <?=$arrConst['_DUYET']?> | </a>
                        <?php
                        if(in_array(Extra_User::getInstance()->getIdentity()->C_ROLE, array('ADMIN', 'ADMIN_SYSTEM'))){?>
                            <a   class="small_link"  onclick="btn_delete_onclick(document.getElementsByName('chk_item_id'),document.getElementById('hdn_object_id_list'),'../delete/','<?=$this->UrlAjax?>','HO_SO','T_eCS_NET_RECORD');">  <?=$arrConst['_XOA']?> | </a>
                        <?php
                        }?>
							<a   class="small_link"  onclick="btn_update_onclick(document.getElementsByName('chk_item_id'),'../orderonnet/sendmail')"><?=$arrConst['_GUI_THONG_BAO']?></a>

					</label>
				</div>	
			</td>
		</tr>
	</table>
	<?php echo $this->genlist;?>				
	<!--Hien thi trang can xem!-->
	
	<table width="100%" cellpadding="0" cellspacing="0" border="0">
		<tr>
			<td style="color:red;width:30%;padding-left:1%;" class="small_label">
				<small class="small_starmark"><?=$this->sdocpertotal;?></small>
			</td>
			<td align="center" style="width:50%">
				<table width="10%">
				<?php
					echo $this->generateStringNumberPage;?>
				</table>
			</td>
			<td width="30%" align="right" style="font-size:13px; padding-right:1%; font:tahoma" class="normal_label"><?php
				//Hien thi so trang
				echo $this->generateHtmlSelectBoxPage;?>
			</td>
		</tr>
	</table>
<div>	
	<table width='100%'  border='0' cellspacing='0' cellpadding='0' align="center">
		<tr>
			<td style="padding-top: 10px; padding-bottom: 10px;" align="center" valign="middle">
				<input type="button" class="add_large_button" value="<?=$arrConst['_DUYET']?>" onclick="btn_update_onclick(document.getElementsByName('chk_item_id'),'../viewrecord/')">
				<input type="button" class="add_large_button" value="<?=$arrConst['_GUI_THONG_BAO']?>" onclick="btn_update_onclick(document.getElementsByName('chk_item_id'),'../senmail/')">
			</td>
		</tr>
	</table>
</div>
</form>
<script type="text/javascript">

shortcut.add("Ctrl+K",function() {
	document.getElementById('txtfullTextSearch').focus();
	document.getElementById('txtfullTextSearch').select();
});
function ResetSearch(){
	document.getElementById('hdn_current_page').value = "1";
}
function checkvalue(){
	if(document.getElementById('txtfullTextSearch').value != ""){
		actionUrl('');
	}
}
function btn_print_record_onclick(p_hidden_obj, p_checkbox_obj, printType, recordTransitionId, p_url){
	v_value_list = checkbox_value_to_list(p_checkbox_obj,",");
	if (!v_value_list){
		alert("Chưa có đối tượng nào được chọn");
	}else{
		arr_value = v_value_list.split(",");
		if (arr_value.length > 1){
			alert("Chỉ được chọn một đối tượng để in")
			return;
		}
		else{
			p_url = p_url + '/?hdn_object_id=' + v_value_list + '&printType=' + printType + '&recordTypeCode=' + '<?= $this->sRecordTypeCode?>' + '&recordType=' + '<?= $this->srecordType?>';
			sRtn = showModalDialog(p_url,"","dialogWidth=1px;dialogHeight=1px;status=no;scroll=no;dialogCenter=yes");			
		    if (sRtn!=""){
				window.open(sRtn);
		    }	
		}
	}
}
</script>