<script src="/efy-doc-boxd/public/js/jquery-1.4.2.min.js" type="text/javascript"></script>
<form action="index" method="POST" id="frmReceived" autocomplete="off" enctype="multipart/form-data">
	<?php echo $this->formHidden("hdn_type","",null); ?>
	<!--Cac doi tuong hidden tren form-->
	<?php echo $this->formHidden("hdn_current_page",$this->iCurrentPage,null); ?>
	<?php echo $this->formHidden("cbo_nuber_record_page",$this->iNumRowOnPage,null); ?>
	<?php echo $this->formHidden("hdn_record_number_page",$this->iNumRowOnPage,null); ?>
	<?php echo $this->formHidden("hdn_object_id_list","",null); ?>
	<?php echo $this->formHidden("hdh_option","",null); ?>
	<?php echo $this->formHidden("hdn_is_update","",null); ?>
	<?php echo $this->formHidden("hdn_record_type_id",$this->RecordTypeId,null); ?>
	<?php echo $this->formHidden("hdn_filter_xml_tag_list",$this->filterXmlTagList,null); ?>
	<?php echo $this->formHidden("hdn_filter_xml_value_list",$this->filterXmlValueList,null); ?>
	<?php echo $this->formHidden("hdn_object_id",$this->srecordId,null); ?>
	<?php echo $this->formHidden("hdn_xml_tag_list","",null); ?>
	<?php echo $this->formHidden("hdn_xml_value_list","",null); ?>
	<?php echo $this->formHidden("hdn_XmlTagValueList","",null); ?>
	<!--Bien hdn_deleted_new_file_id_list dung de luu Id cua nhung doi tuong file dinh kem se xoa-->	
	<?php echo $this->formHidden("hdn_deleted_new_file_id_list","",null); ?>	
	<?php echo $this->formHidden("htn_leftModule",$this->currentModulCodeForLeft,null); ?>	
	<!--Bien hdn_deleted_exist_file_id_list dung de ...-->	
	<?php echo $this->formHidden("hdn_deleted_exist_file_id_list","",null);?>
	<!--Bien hdn_back_option dung de quay tro lai man hinh danh sach da dinh...-->	
	<?php echo $this->formHidden("hdn_back_option",$this->sBackOption,null);?>
	<?php
		$arrConst = $this->arrConst;
		$sUrlEdit  = "../edit/";
		$urlCalendar = $this->urlCalendar;
		$arrSingleRecord = $this->arrSingleRecord;
	?>
	<table width="100%" id="workadd" align="center" border="0">
		<col width="85%">	
		<tr>		
			<td class="left" valign="top">
				<div class = "large_title">
					<?=$this->titleBody;?>			
				</div>
				<table width='99%'  border='0' cellspacing='0' cellpadding='0' class="table_title">
					<col width="85%" align="left"/><col width="15%" align="right"/>
					<tr>
						<td align="right" colspan="2">
							<div style="text-align:right; width:98%;">
								<label>
									<a  class="small_link"  onclick="document.getElementById('hdh_option').value='GHI_THEMMOI';btn_save_record(document.getElementById('hdn_xml_tag_list'),document.getElementById('hdn_xml_value_list'),'../index/','<?=$this->UrlAjax?>');"><?='C&#7853;p nh&#7853;t'?></a>									
									<a  class="small_link"  onclick="actionUrl('../index/');"><?='Quay l&#7841;i'?></a> 
								</label>
							</div>	
						</td>
					</tr>
				</table>
				<div id="contentXml">
					<div id= "header_update_form">
						<div>
							<label><?php echo $arrConst['_LOAI_HO_SO'];?></label>
							<input disabled value = "<?=$this->RecodeTypeName?>" class="textbox" style="width:60%;"  id ="C_RECORDTYPE" name="C_RECORDTYPE" type="text"  xml_tag_in_db="" xml_data="false" column_name="C_RECORDTYPE"  />
						</div>
											
						<div>
							<label><?php echo $arrConst['_MA_HO_SO'];?></label>
							<input readonly class="textbox" style="width:20%;" value = "<?= $this->RecodeCode?>"  id ="C_CODE" name="C_CODE" type="text" option = "false"  xml_tag_in_db="" xml_data="false" column_name="C_CODE"  />
						</div>
						<div>
							<label><?=$arrConst['_NGAY_GUI']?></label>
							<input class="textbox" style="width:15%;"  id ="C_RECEIVED_DATE" name="C_RECEIVED_DATE" type="text" isdate="true" option = "false"  xml_tag_in_db="" xml_data="false" column_name="C_RECEIVED_DATE" message="<?php echo "NGÀY TIẾP NHẬN không đúng định dạng ngày/tháng/năm!";?>" value = "<?=date("d/m/Y")?>"  onKeyUp="DateOnkeyup(this,event)" />
							<img src="<?= $this->baseUrl?>images/calendar.gif" border="0" onclick="DoCal('<?= $urlCalendar;?>',document.getElementById('C_RECEIVED_DATE'));" style="cursor:pointer">							
						</div> 
					</div>
						<?php echo $this->generateFormHtml;?>
						
					<div id= "header_update_form">
						<div>
							<label>Duyệt hồ sơ</label>
							<div style = "float:right;width:70%">
								<input type='radio' id = 'optionduyet' name='optionduyet' onclick= 'showHideOriginalApplicationDate(1,"C_ORIGINAL_APPLICATION_DATE");' class='normal_checkbox'  value='1' title='Chấp thuận và hẹn công dân mang hồ sơ gốc đến' message='' />
								<label for = "option0" style = "display:inline;float:none;">Chấp nhận và hẹn công dân ngày đến lấy kết quả</label>
							<br />
								<input type='radio' id = 'optionduyet' name='optionduyet' onclick= 'showHideOriginalApplicationDate(2,"C_ORIGINAL_APPLICATION_DATE");' class='normal_checkbox'  value='2' title='Yêu cầu công dân sửa đổi' message='' />
								<label for = "option1" style = "display:inline;float:none;">Yêu cầu công dân sửa đổi</label>
							</div>
						</div>
						<div style = "clear:both;">
								<label>Nội dung thông báo</label>
								<input id='NOIDUNG' name='NOIDUNG' class="textbox" style="width:74%;height:10%;" message='Noi dung thong bao khong duoc bo trong'/ value='<?=$arrSingleRecord[0]['C_MESSAGE'];?>'>
						</div>
						<div id="C_ORIGINAL_APPLICATION_DATE_ID">
							<label><?=$arrConst['_NGAY_HEN_MANG_HO_SO_GOC']?></label>
							<input class="textbox" style="width:15%;"  id ="C_ORIGINAL_APPLICATION_DATE" name="C_ORIGINAL_APPLICATION_DATE" type="text" isdate="true" option = "false"  xml_tag_in_db="" xml_data="false" column_name="C_ORIGINAL_APPLICATION_DATE" message="<?php echo "NGAY HEN MANG HO SO GOC DEN GIAI QUYET khong duoc truoc ngay gui tiep nhan ho so";?>" value="<?=Efy_Library::_yyyymmddToDDmmyyyy($arrSingleRecord[0]['C_ORIGINAL_APPLICATION_DATE'])?>"  onKeyUp="DateOnkeyup(this,event)" />
							<img src="<?= $this->baseUrl?>images/calendar.gif" border="0" onclick="DoCal('<?= $urlCalendar;?>',document.getElementById('C_ORIGINAL_APPLICATION_DATE'));" style="cursor:pointer">							
						</div> 
						<div>
							<label>File đính kèm</label>
							<?php echo $this->AttachFile;?>
						</div>
					</div>
				</div>
				<!--Hien thi nut!-->
				<div id="button">
					<button name="btn_ghivathemmoi" id="btn_ghivathemmoi" type="button" value="Ghi&amp;Thêm mới" class="add_large_button" onClick="document.getElementById('hdh_option').value='GHI_THEMMOI',actionUrl('');"><?='C&#7853;p nh&#7853;t'?></button>					
					<input type="button" style="margin-left:0px;" name="quaylai" id="quaylai" value="<?='Quay l&#7841;i'?>" onClick="actionUrl('../index/');" class="add_large_button">						
				</div>	
			</td>
		</tr>	
	</table>
</form>
<script>
	appointed_date(document.getElementById('C_RECEIVED_DATE').value,document.getElementById('limit_date'),document.getElementById('C_APPOINTED_DATE'));
	//De an hien thong tin ngay hen mang ho so goc den giai quyet
	//option = 1: hien thong tin ngay hen mang ho so goc den giai quyet
	//option = 2: an thong tin ngay hen mang ho so goc den giai quyet
	function showHideOriginalApplicationDate(option,id){
		if (option == 1){
			document.getElementById(id).style.display = 'block';
		}else {
			document.getElementById(id).style.display = 'none';
		}
	}
</script>
<div id = "ajax" style = "display:none;"></div>

