
<?php
	$arrConst = $this->arrConst;
	$sUrlEdit  = "../edit/";
	$urlCalendar = $this->urlCalendar;
	$arrSingleRecord = $this->arrSingleRecord;
?>
<table width="100%" id="workadd" align="center" border="0">
	<col width="85%">	
	<tr>		
		<td class="left" valign="top">
			<div class = "large_title">
				<?=$this->titleBody;?>			
			</div>
			<table width='99%'  border='0' cellspacing='0' cellpadding='0' class="table_title">
				<col width="85%" align="left"/><col width="15%" align="right"/>
				<tr>
					<td align="right" colspan="2">
						<div style="text-align:right; width:98%;">
							<label>
								<a  class="small_link" href="javascript:{}" onclick="$('#frmReceived').trigger('submit')">Cập nhật</a> |
								<a  class="small_link"  onclick="actionUrl('../orderonnet/index');"><?='Quay l&#7841;i'?></a>
							</label>
						</div>	
					</td>
				</tr>
			</table>
			<div id="contentXml">
				<div id= "header_update_form">
					<div>
						<label><?php echo $arrConst['_LOAI_HO_SO'];?></label>
						<input disabled value = "<?=$this->RecodeTypeName?>" class="textbox" style="width:60%;"  id ="C_RECORDTYPE" name="C_RECORDTYPE" type="text"  xml_tag_in_db="" xml_data="false" column_name="C_RECORDTYPE"  />
					</div>
										
					<div>
						<label>Mã đăng ký</label>
						<input readonly class="textbox" style="width:20%;" value = "<?= $this->RecodeCode?>"  id ="C_CODE" name="C_CODE" type="text" option = "false"  xml_tag_in_db="" xml_data="false" column_name="C_CODE"  />
					</div>
					<div>
						<label>Ngày đăng ký</label>
						<input class="textbox" style="width:15%;"  id ="C_RECEIVED_DATE" name="C_RECEIVED_DATE" type="text" isdate="true" option = "false"  xml_tag_in_db="" xml_data="false" column_name="C_RECEIVED_DATE" message="<?php echo "NGÀY TIẾP NHẬN không đúng định dạng ngày/tháng/năm!";?>" value = "<?=date("d/m/Y")?>"  onKeyUp="DateOnkeyup(this,event)" />							
					</div> 
				</div>
                <?php echo $this->generateFormHtml;?>
				

				<!-- Form -->
			<form action="viewrecord" method="POST" id="frmReceived" autocomplete="off" enctype="multipart/form-data">
				<?php echo $this->formHidden("hdn_type","",null); ?>
				<!--Cac doi tuong hidden tren form-->
				<?php echo $this->formHidden("hdn_current_page",$this->iCurrentPage,null); ?>
				<?php echo $this->formHidden("cbo_nuber_record_page",$this->iNumRowOnPage,null); ?>
				<?php echo $this->formHidden("hdn_record_number_page",$this->iNumRowOnPage,null); ?>
				<?php echo $this->formHidden("hdn_object_id_list","",null); ?>
				<?php echo $this->formHidden("hdh_option","",null); ?>
				<?php echo $this->formHidden("hdn_is_update","",null); ?>
				<?php echo $this->formHidden("hdn_record_type_id",$this->RecordTypeId,null); ?>
				<?php echo $this->formHidden("hdn_filter_xml_tag_list",$this->filterXmlTagList,null); ?>
				<?php echo $this->formHidden("hdn_filter_xml_value_list",$this->filterXmlValueList,null); ?>
				<?php echo $this->formHidden("hdn_object_id",$this->srecordId,null); ?>
				<?php echo $this->formHidden("htn_leftModule",$this->currentModulCodeForLeft,null); ?>	
				<?php echo $this->formHidden("hdn_back_option",$this->sBackOption,null);?>
				<div id= "header_update_form">
					<div>
						<label>Duyệt nội dung đăng ký</label>
						<div style = "float:right;width:70%">
							<input type='radio' id = 'optionduyet1' name='optionduyet' class='normal_checkbox'  value="1" title="Chấp thuận và hẹn công dân mang hồ sơ gốc đến" message='' checked="checked"  />
							<label for = "optionduyet1" style = "display:inline;float:none;">Duyệt đăng ký</label>
						<br />
							<input type='radio' id = 'optionduyet2' name='optionduyet'  class='normal_checkbox'  value="2" title="Yêu cầu công dân sửa đổi" message='' />
							<label for = "optionduyet2" style = "display:inline;float:none;">Từ chối đăng ký</label>
						</div>
					</div>
					<div style = "clear:both;">
							<label>Nội dung thông báo<small class="normal_starmark">*</small></label>
							<input id='NOIDUNG' name='NOIDUNG' class="textbox" style="width:74%;height:10%;" message='Noi dung thong bao khong duoc bo trong'/ value='<?=$arrSingleRecord[0]['C_MESSAGE'];?>'>
					</div>
				</div>
			</form>
			</div>
			<!--Hien thi nut!-->
			<div id="button">
				<button name="btn_ghivathemmoi" id="btn_ghivathemmoi" type="button" onclick="$('#frmReceived').trigger('submit')" value="Cập nhật" class="add_large_button">Cập nhật</button>					
				<input type="button" style="margin-left:0px;" name="quaylai" id="quaylai" value="<?='Quay l&#7841;i'?>" onClick="actionUrl('../orderonnet/index');" class="add_large_button">
			</div>	
		</td>
	</tr>	
</table>

<script>
	$(function() { $( "#C_RECEIVED_DATE, #C_ORIGINAL_APPLICATION_DATE" ).datepicker({ changeMonth: true, gotoCurrent: true, minDate: new Date(1945, 1 - 1, 1), changeYear: true }); });
	
	$('[name="optionduyet"]').change(function() {
		if ($(this).val() == 1) {
			$('#C_ORIGINAL_APPLICATION_DATE').closest('div').show();
			$('#C_ORIGINAL_APPLICATION_DATE').removeAttr('optional');
            $('#NOIDUNG').val('Đăng ký giao dịch được duyệt!');
		} else {
			$('#C_ORIGINAL_APPLICATION_DATE').closest('div').hide();
			$('#C_ORIGINAL_APPLICATION_DATE').attr('optional', true);
            $('#NOIDUNG').val('Đăng ký giao dịch bị từ chối');
		}
	});
	$('[name="optionduyet"]:checked').trigger('change');

	$('form#frmReceived').submit(function() {
		if (verify(document.forms['frmReceived'])) {
			/*
				document.getElementById('hdh_option').value='GHI_THEMMOI';btn_save_record(document.getElementById('hdn_xml_tag_list'),document.getElementById('hdn_xml_value_list'),'../index/','<?=$this->UrlAjax?>');
			*/
		} else {
			return false;
		}
	})
</script>
<div id = "ajax" style = "display:none;"></div>

