<script>
    if (typeof(Admin_Log) != 'function') {
        var arrJsCss = $.parseJSON('<?=$this->arrJsCss; ?>');
        loadfileJsCss(arrJsCss);
    }
</script>
<div id="IndexFrm">
    <form action="index" method="POST" id="frmLog">
        <?php
        echo $this->formHidden("hdn_current_page", $this->iCurrentPage, null);
        echo $this->formHidden("hdn_record_number_page", $this->iNumberRecordPerPage, null);
        echo $this->formHidden("fkStaffhdn", '', null);
        ?>
        <div class="searh-fixed">
            <div class="normal_title">
                <?= $this->bodyTitle; ?>
            </div>
            <!--Màn hình tìm kiếm!-->
            <div class="search-container">
                <table id="table-search">
                    <col width="25%"></col>
                    <col width="8%"></col>
                    <col width="10%"></col>
                    <col width="8%"></col>
                    <col width="10%"></col>
                    <col width="15%"></col>
                    <col width="9%"></col>
                    <col width="15%"></col>
                    <tr>
                        <td style="text-align: center;">
                            <label class="normal_label" for="fromDate">Ngày đăng nhập, Từ ngày</label>
                        </td>
                        <td>
                            <input onchange="ResetSearch()" type="text" id="fromDate" optional="true"
                                   value="01/<?= date('m/Y') ?>" name="fromDate" class="textbox" date="isdate"
                                   onkeyup="DateOnkeyup(this,event)"  style="width: 90%;"/>
                        </td>
                        <td style="padding-left:10px;text-align: center;">
                            <label class="normal_label" for="toDate">Đến ngày</label>
                        </td>
                        <td>
                            <input onchange="ResetSearch()" type="text" id="toDate" optional="true"
                                   value="<?= date('d/m/Y') ?>" name="toDate" class="textbox" date="isdate"
                                   onkeyup="DateOnkeyup(this,event)"  style="width: 90%;"/>
                        </td>

                        <td style="padding-left:10px;text-align: center;">
                            <label class="normal_label" for="domain">Domain</label>
                        </td>
                        <td>
                            <input onchange="ResetSearch()" type="text" id="domain" optional="true" value=""
                                   name="domain" class="textbox" style="width: 90%;"/>
                        </td>

                        <td style="padding-left:10px;text-align: center;">
                            <label class="normal_label" for="ip">IP</label>
                        </td>
                        <td>
                            <input onchange="ResetSearch()" type="text" id="ip" optional="true" value=""
                                   name="ip" class="textbox" style="width: 90%;"/>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="button-link-container" align="right">
                <div class="blc-left">
                    <input name="btn_filter" id="btn_filter" type="button" value="Tìm kiếm"
                           class="but_formfield clsearch">
                </div>
                <div class="blc-right">
                    <input name="btn_delete" id="btn_delete" type="button" value="Xóa" class="but_formfield cldelete">
                </div>
            </div>
        </div>
        <!-- Màn hình danh sách -->
        <div id="table-container">
            <table cellpadding="0" cellspacing="0" border="0" align="center" class="list-table-data" id="table-data">
                <?php
                $delimitor = "!~~!";//Lay ky tu phan cach giua cac phan tu
                $StrHeader = explode("!~~!", G_Gen::_GenerateHeaderTable("3%"
                    . $delimitor . "20%"
                    . $delimitor . "20%"
                    . $delimitor . "35%"
                    . $delimitor . "12%"
                    , '<input optional = "true" type="checkbox" name="chk_all_item_id" value="" onclick="checkbox_all_item_table(this,\'chk_item_id\');">'
                    . $delimitor . 'Tên cán bộ'
                    . $delimitor . 'Địa chỉ truy cập'
                    . $delimitor . 'Tên miền'
                    . $delimitor . 'Thời điểm'
                    , $delimitor));
                echo $StrHeader[0];
                echo G_Gen::_addEmptyRow($this->iCountElement, 15, 'odd_row', 5);
                ?>
            </table>
        </div>
        <!-- Phân trang dữ liệu -->
        <table class="table-page-number" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td class="left-col small_label" valign="top">
                    <small class="small_starmark" id="sdocpertotal"></small>
                </td>
                <td class="center-col" align="center" id="generateStringNumberPage"></td>
                <td class="right-col normal_label" id="generateHtmlSelectBoxPage">
                    Hiển thị <select class='textbox' id='cbo_nuber_record_page' name='cbo_nuber_record_page' optional='true'
                                                                                                   style='width:60'>
                    <?php
                        echo G_Gen::getInstance()->_generateSelectOption($this->arrListItem, 'sCode', 'sCode', 'sName', $this->arrListItem[0]);
                        ?></select>Hồ sơ/1 trang
                </td>
            </tr>
        </table>
        <!-- Các tùy chọn -->
        <div class="button-container">
            <input name="btn_delete" id="btn_delete" type="button" value="Xóa" class="but_formfield cldelete">
        </div>
    </form>
</div>
<script type="text/javascript">
    baseUrl = '<?=$this->baseUrl();?>';
    if (typeof(Admin_Log) === 'function') {
        var objAdmin_Log = new Admin_Log(baseUrl, 'system', 'log');
    }

    $('form#frmLog').process_paging({
        getData: function (callback) {
            objAdmin_Log.loadList(callback);
        },
        obj: objAdmin_Log
    });
    objAdmin_Log.loadIndex();
</script>
<style type="text/css">
    div#form-content div label {
        float: left;
    }
</style>