<?php
$dir = $this->baseUrl() . '/public/js/crop-avatar/';
$sysConst = Zend_Registry::get('__sysConst__');
$userIdentity = Zend_Auth::getInstance()->getIdentity();
?>
<link href="<?= $dir ?>css/bootstrap.min.css" rel="stylesheet">
<link href="<?= $dir ?>css/cropper.min.css" rel="stylesheet">
<link href="<?= $dir ?>css/main.css" rel="stylesheet">
<link href="<?= $this->baseUrl() ?>/public/css/skill.css" rel="stylesheet">
<link href="<?= $this->baseUrl() ?>/public/css/skill_2.css" rel="stylesheet">
<h1 class="normal_title">CẬP NHẬT HÌNH ĐẠI DIỆN</h1>
<form action="" enctype="multipart/form-data" method="post">
    <input type="hidden" name="hdn_action" value="1"/>

    <div class="avatar-view" title="Thay đổi ảnh đại diện">
        <img src="<?= $this->urlavatr ?>" alt="Avatar">
        <input type="hidden" id="hdn-avatar" name="hdn-avatar" value="<?= $this->avatar ?>"/>
    </div>
    <div align="center">
        <input type="submit" class="but_formfield" value="Cập nhật"/>
    </div>
</form>
<div id="crop-avatar" class="container">
    <!-- Cropping modal -->
    <div class="modal fade" id="avatar-modal" aria-hidden="true" aria-labelledby="avatar-modal-label" role="dialog"
         tabindex="-1">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <form class="avatar-form" action="<?= $this->baseUrl() ?>/crop" enctype="multipart/form-data"
                      method="post">
                    <div class="modal-header">
                        <button class="close" data-dismiss="modal" type="button">&times;</button>
                        <h4 class="modal-title" id="avatar-modal-label">Thay đổi ảnh đại diện</h4>
                    </div>
                    <div class="modal-body">
                        <div class="avatar-body">

                            <!-- Upload image and data -->
                            <div class="avatar-upload">
                                <input class="avatar-src" name="avatar_src" type="hidden">
                                <input class="avatar-data" name="avatar_data" type="hidden">
                                <label for="avatarInput">Local upload</label>
                                <input class="avatar-input" id="avatarInput" name="avatar_file" type="file">
                            </div>

                            <!-- Crop and preview -->
                            <div class="row">
                                <div class="col-md-9">
                                    <div class="avatar-wrapper"></div>
                                </div>
                                <div class="col-md-3">
                                    <div class="avatar-preview preview-lg"></div>
                                    <div class="avatar-preview preview-md"></div>
                                    <div class="avatar-preview preview-sm"></div>
                                </div>
                            </div>

                            <div class="row avatar-btns">
                                <div class="col-md-9">
                                    <div class="btn-group">
                                        <button class="btn btn-primary" data-method="rotate" data-option="-90"
                                                type="button" title="Rotate -90 degrees">Rotate Left
                                        </button>
                                        <button class="btn btn-primary" data-method="rotate" data-option="-15"
                                                type="button">-15deg
                                        </button>
                                        <button class="btn btn-primary" data-method="rotate" data-option="-30"
                                                type="button">-30deg
                                        </button>
                                        <button class="btn btn-primary" data-method="rotate" data-option="-45"
                                                type="button">-45deg
                                        </button>
                                    </div>
                                    <div class="btn-group">
                                        <button class="btn btn-primary" data-method="rotate" data-option="90"
                                                type="button" title="Rotate 90 degrees">Rotate Right
                                        </button>
                                        <button class="btn btn-primary" data-method="rotate" data-option="15"
                                                type="button">15deg
                                        </button>
                                        <button class="btn btn-primary" data-method="rotate" data-option="30"
                                                type="button">30deg
                                        </button>
                                        <button class="btn btn-primary" data-method="rotate" data-option="45"
                                                type="button">45deg
                                        </button>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <button class="btn btn-primary btn-block avatar-save" type="submit">Done</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- <div class="modal-footer">
                      <button class="btn btn-default" data-dismiss="modal" type="button">Close</button>
                    </div> -->
                </form>
            </div>
        </div>
    </div>
    <!-- /.modal -->
    <!-- Loading state -->
    <div class="loading" aria-label="Loading" role="img" tabindex="-1"></div>
</div>
<script src="<?= $dir ?>js/bootstrap.min.js"></script>
<script src="<?= $dir ?>js/cropper.min.js"></script>
<script src="<?= $dir ?>js/main.js"></script>
<script type="text/javascript">
    var message = '<?=$this->message?>';
    $(function () {
        if (message) jAlert(message, 'Thông báo')
    })
</script>
<style>
   #avatar-modal img, .avatar-view img {
        max-width: 100%;
    }

    .avatar-view {
        margin: 5% auto;
    }

    .list_categories .row {
        margin-left: 0px;
        margin-right: 0px;
    }

    body {
        line-height: 1;
    }
</style>
