<script>
    if (typeof(Account_Profile) != 'function') {
        var arrJsCss = $.parseJSON('<?=$this->arrJsCss; ?>');
        loadfileJsCss(arrJsCss);
    }
</script>
<div id="local_update">
    <div class="head normal_title">Thay đổi mật khẩu</div>
    <div class="update_area large_area frmxml" style="overflow: hidden;">
        <form id="changepass" class="item" method="post">
            <div class="frm">
                <div class="row">
                    <label>Mật khẩu cũ</label>
                    <input type="password" class="text_box w25" id="passOld" name="passOld" value="" class="w25" required/>
                </div>
                <div class="row">
                    <label>Mật khẩu mới</label>
                    <input type="password" class="text_box w25" id="passNew" name="passNew" value="" class="w25" required/>
                </div>
                <div class="row">
                    <label>Nhập lại mật khẩu mới</label>
                    <input type="password" class="text_box w25" id="repassNew" name="repassNew" value="" class="w25"
                           required/>
                </div>
                <div style="padding: 5px 10px 2px 185px;" class="row">
                    <input type="submit" class="but_formfield" id="updatepass" name="updatepass" value="Cập nhật"/>
                </div>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript">
    var dProfile = new Account_Profile({module: 'user', controller: 'profile'});
    dProfile.initialize();
</script>
<style>
    .w25 {
        width: 25%
    }
</style>